### ISSUE TITLE
请问recv_window的计算公式

### ISSUE THREAD

**Issue by chika0801** [emptysuns/Hi_Hysteria#10]
recv_window_conn 和 recv_window (服务器端是 recv_window_client) 以确保它们至少不低于带宽-延迟的乘积。 比如如果想在一条 RTT 200ms 的线路上达到 500 MB/s 的速度，receive window 至少需要 100 MB (500*0.2)

看了一下你的脚本，官方的说明，没有搞明白。

为什么recv_window=200ms x 2（往反） x 100MB/s（我客户端下行最大带宽） / 1000（请问这除1000是什么原因） x 1024 x 1024 

recv_window_conn为什么是 除 4了？

**Comment by emptysuns** [comment]
buffer size = 超时时间*后台处理能力
/1000是为了把ms换成s，接收链接/4就是完全参考hysteria的wiki了

**Comment by chika0801** [comment]
感谢你
