### ISSUE TITLE
Hysteria协议是不是不支持dns解锁奈飞啊

### ISSUE THREAD

**Issue by datougua** [emptysuns/Hi_Hysteria#100]
Hysteria协议是不是不支持dns解锁奈飞啊
vps上用脚本测试，解锁的
但打开奈飞没有解锁

**Comment by emptysuns** [comment]
hihy没用系统dns，默认使用8.8.8.8
修改的话`/etc/hihy/conf/hihyServer.json`中`8.8.8.8`改成你的dns然后重启
