### ISSUE TITLE
脚本能不能支持ipv6 only啊

### ISSUE THREAD

**Issue by barney2022** [emptysuns/Hi_Hysteria#101]
脚本运行下来 因为没有IPV4地址, 服务器监听参数那里是空白的
自己折腾了很久, 改监听IP, 改DNS 都没成功连上

**Comment by emptysuns** [comment]
......建议使用warp增加个ipv4出栈后再用
没有特意适配过纯ipv6，但在脚本执行逻辑上应该没问题，不知道哪儿出bug了，主要是我没有测试环境。
https://github.com/fscarmen/warp

**Comment by barney2022** [comment]
谢谢指点
