### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by liuxyon** [emptysuns/Hi_Hysteria#106]
是否可以增加多密码管理,以及显示用户连接状态，最好能控制流量和到期暂停或删除. 因为这个速度确实快，很容易导致带宽饱和,所以需要监控各个用户的情况并可以采取措施.

**Comment by emptysuns** [comment]
.......
你要开机场吗？
hysteria有鉴权API，但是这不是一个脚本能很好控制的，需要设计一个后台或者给现成的panel写插件，这不在hihy考虑范围，或者你去新开一个仓库自己完成这部分功能。
