### ISSUE TITLE
请输入证书cert文件路径(需fullchain)

### ISSUE THREAD

**Issue by rkygogo** [emptysuns/Hi_Hysteria#107]
fullchain是什么意思？
证书路径是以下两个
/root/private.key
/root/cert.crt
怎么填？

**Comment by emptysuns** [comment]
请输入证书**cert文件**路径(需fullchain)

fullchain是什么意思？
证书路径是以下两个
/root/private.key
**/root/cert.crt**
怎么填？

这种提示还不够明显吗?
