### ISSUE TITLE
提示“Port: TCP/80 已经被 apache2(*:http) 占用,进程pid为: 459.  是否自动关闭端口占用?(y/N) ”

### ISSUE THREAD

**Issue by 860451472** [emptysuns/Hi_Hysteria#108]
在输入认证口令回车后，就会弹出提示“Port: TCP/80 已经被 apache2(*:http) 占用,进程pid为: 459. 
是否自动关闭端口占用?(y/N) ”，默认停止安装，按下y后解绑端口提示“
执行配置... 

Wait,test config...

未知错误:请手动运行:/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server  
查看错误日志,反馈到issue! ”

**Comment by 860451472** [comment]
我知道了，kill -9 在我的小鸡上被精简了，我用killall apache2杀了进程就能用了。。。

**Comment by emptysuns** [comment]
被精简具体是什么情况呢？能否详细说明一下
