### ISSUE TITLE
未知错误,wget无法获取版本信息

### ISSUE THREAD

**Issue by wang001200** [emptysuns/Hi_Hysteria#109]
脚本提示：未知错误，经查：下载程序的时候获取不到版本信息，导致appS是一个空文件
系统：debian10,wget版本：1.20.1-1.1
version=`wget -qO- -t1 -T2 --no-check-certificate "https://api.github.com/repos/HyNetwork/hysteria/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g'`

**Comment by emptysuns** [comment]
wget这段命令提示什么错误？

**Comment by wang001200** [comment]
返回值是空的，没有获取到内容发自我的iPhone------------------ 原始邮件 ------------------发件人: emptysuns  ***@***.***>发送时间: 2022年7月29日 00:43收件人: emptysuns/Hi_Hysteria ***@***.***>抄送: wang001200 ***@***.***>, Author ***@***.***>主题: Re: [emptysuns/Hi_Hysteria] 未知错误,wget无法获取版本信息 (Issue #109)
wget这段命令提示什么错误？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/emptysuns/Hi_Hysteria/issues/109#issuecomment-1198389162",
"url": "https://github.com/emptysuns/Hi_Hysteria/issues/109#issuecomment-1198389162",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by emptysuns** [comment]
你的ip被github拉黑了吗？

**Comment by wang001200** [comment]
应该没有。我今天运行成功了😂。中间有印象的操作可能是：重启….然后开了cf的warp。再问下：生成的配置里，IP居然是cf的泛播（百度的），这是怎么回事？这个IP既不是我vps的公私网ip，也不是我获得的cf的warp endpoint ip发自我的iPhone------------------ 原始邮件 ------------------发件人: emptysuns  ***@***.***>发送时间: 2022年7月29日 11:28收件人: emptysuns/Hi_Hysteria ***@***.***>抄送: wang001200 ***@***.***>, Author ***@***.***>主题: Re: [emptysuns/Hi_Hysteria] 未知错误,wget无法获取版本信息 (Issue #109)
你的ip被github拉黑了吗？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/emptysuns/Hi_Hysteria/issues/109#issuecomment-1198842240",
"url": "https://github.com/emptysuns/Hi_Hysteria/issues/109#issuecomment-1198842240",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by emptysuns** [comment]
那个只是通过外部API获得你的公网ip，如果使用了cloudflare warp隐藏真实ip时就会显示你代理后的，把配置文件改成你真实的ip地址就行了
