### ISSUE TITLE
求指教，linux系统，dns配置问题

### ISSUE THREAD

**Issue by buitt34** [emptysuns/Hi_Hysteria#113]
服务端和客户端dns要怎么配置？服务端配置dns的文件在哪里？客户端我用的是passwall或者clash，该去哪里配置dns？求大神指教，万分感激!

**Comment by emptysuns** [comment]
直接修改服务端dns吧，`/etc/hihy/conf/hihyServer.json`,修改后重启

**Comment by buitt34** [comment]
我修改了以后不行，不知道为什么，客户端要做什么动作吗？

**Comment by emptysuns** [comment]
passwall有自己的dns解析，需设置通过服务器解析，具体看你的配置
clash_meta如果你用的hihy生成的，则是默认将代理规则集里域名直接交给服务器解析

**Comment by buitt34** [comment]
有passwall的相关服务器解析设置教程吗？clash meta我是一键生成的

**Comment by emptysuns** [comment]
https://lmstfy.net/?q=cGFzc3dhbGwgZG5z6YWN572u

**Comment by buitt34** [comment]
多谢大佬，万分感激
