### ISSUE TITLE
hy更新为1.2.0后安装配置出错

### ISSUE THREAD

**Issue by terryz89** [emptysuns/Hi_Hysteria#115]
输入自签证书后，公网ip显示为“公网ip:<!DOCTYPE ”
配置文件显示："server": "[<!DOCTYPE html>
一键链接为：hysteria://[<!DOCTYPE 
![1660560125734](https://user-images.githubusercontent.com/43930160/184621636-c2c29e5a-8c5b-4d9a-a995-c9902e46bff2.jpg)

**Comment by emptysuns** [comment]
hmmm....
获取公网ip的接口用的ip.sb的，你该不会碰到这个网站防火墙规则了吧？
 原因是公网ip获取失败，没对接口返回的数据做判断导致的错误，如果是自签证书手动替换为你正确的ip即可

**Comment by terryz89** [comment]
这么说的话racknerd跟这个防火墙协议有冲突吧，用其他的vps没有这个问题
