### ISSUE TITLE
今早升级CORE到1.2.0之后的机器都不通了

### ISSUE THREAD

**Issue by xiaowanggg** [emptysuns/Hi_Hysteria#116]
没有升级core的日志是这样
[1;32m2022-08-16 10:16:20 INF:[0m [main] server address: 127.0.0.1#2080
[1;32m2022-08-16 10:16:20 INF:[0m [main] listen address: 0.0.0.0#1041
[1;32m2022-08-16 10:16:20 INF:[0m [main] listen address: ::#1041
[1;32m2022-08-16 10:16:20 INF:[0m [main] udp cache maximum size: 256
[1;32m2022-08-16 10:16:20 INF:[0m [main] udp socket idle timeout: 60
[1;32m2022-08-16 10:16:20 INF:[0m [main] number of worker threads: 1
[1;32m2022-08-16 10:16:20 INF:[0m [main] enable tcp transparent proxy
[1;32m2022-08-16 10:16:20 INF:[0m [main] use redirect instead of tproxy
[1;32m2022-08-16 10:16:20 INF:[0m [main] verbose mode (affect performance)
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.5.147#54346
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_tproxy_accept_cb] target socket address: 52.25.180.34#443
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080 succeeded
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_send_authreq_cb] send to 127.0.0.1#2080, nsend:3
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_recv_authresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_recv_authresp_cb] send to 127.0.0.1#2080, nsend:10
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:4
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:4
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_recv_proxyresp_cb] recv from 127.0.0.1#2080, nrecv:2
[1;32m2022-08-16 10:16:22 INF:[0m [tcp_socks5_recv_proxyresp_cb] tunnel is ready, start forwarding ...

升级了core的机器的日志是这样

[1;32m2022-08-16 10:17:21 INF:[0m [main] server address: 127.0.0.1#2080
[1;32m2022-08-16 10:17:21 INF:[0m [main] listen address: 0.0.0.0#1041
[1;32m2022-08-16 10:17:21 INF:[0m [main] listen address: ::#1041
[1;32m2022-08-16 10:17:21 INF:[0m [main] udp cache maximum size: 256
[1;32m2022-08-16 10:17:21 INF:[0m [main] udp socket idle timeout: 60
[1;32m2022-08-16 10:17:21 INF:[0m [main] number of worker threads: 1
[1;32m2022-08-16 10:17:21 INF:[0m [main] enable tcp transparent proxy
[1;32m2022-08-16 10:17:21 INF:[0m [main] use redirect instead of tproxy
[1;32m2022-08-16 10:17:21 INF:[0m [main] verbose mode (affect performance)
[1;32m2022-08-16 10:17:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.5.147#54367
[1;32m2022-08-16 10:17:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 52.25.180.34#443
[1;32m2022-08-16 10:17:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...
[1;35m2022-08-16 10:17:23 ERR:[0m [tcp_socks5_connect_cb] connect to 127.0.0.1#2080: Connection refused
[1;32m2022-08-16 10:17:23 INF:[0m [tcp_tproxy_accept_cb] source socket address: 192.168.5.147#54368
[1;32m2022-08-16 10:17:23 INF:[0m [tcp_tproxy_accept_cb] target socket address: 52.25.180.34#443
[1;32m2022-08-16 10:17:23 INF:[0m [tcp_tproxy_accept_cb] try to connect to 127.0.0.1#2080 ...

其中的区别是少了一句  tunnel is ready, start forwarding ...
多了一句  Connection refused

升级的办法是在使用脚本升级core 从1.1.0到1.2.0  openwrt客户端也升级到了1.2.0   
情况是 连接升级了core的机器不通 没有升级的则一切正常 
使用的是SSL证书加UDP模式 所有机器都一样。

**Comment by xiaowanggg** [comment]
当然所有的参数都没有任何的更改，唯一做的事情就是用脚本升级了core，并且用脚本重启了hy服务（意图让新的core生效）

**Comment by xiaowanggg** [comment]
之前也升级过，同样流程，没有任何问题...= = 难不成是core本身的问题

**Comment by xiaowanggg** [comment]
|**********      Hi Hysteria       **********|
|**********    Author: emptysuns   **********|
|**********     Version: 0.4.0     **********|
 -------------------------------------------
Tips:hihy 命令再次运行本脚本.
............................................. 
############################### 

..................... 
1)  安装 hysteria 
2)  卸载 
..................... 
3)  启动 
4)  暂停 
5)  重新启动 
6)  运行状态 
..................... 
7)  更新Core 
8)  查看当前配置 
9)  重新配置 
10) 切换ipv4/ipv6优先级 
11) 更新hihy 
12) 完全重置所有配置 
13) 修改当前协议类型 

############################### 



0)退出 
............................................. 
请选择:6
Dead!hysteria未正常运行! 


貌似问题是升级1.2.0 的CORE之后 hy直接挂了...= =

**Comment by xiaowanggg** [comment]
貌似也算解决了，解决的方式是，用脚本的的卸载功能完全卸载之后，再重新安装1.2.0即可

**Comment by emptysuns** [comment]
0.4.0的更新日志里说明原因了
一句话概括就是新版core不兼容老版配置，如果更新了core，需要更新hihy后重新配置才能生成新版配置文件。
