### ISSUE TITLE
如何使用ipv6连接？

### ISSUE THREAD

**Issue by idragonet** [emptysuns/Hi_Hysteria#118]
Oracle机器开通IPV6但是修改配置里面的IPV4地址为IPV6发现VrayN连接不上。

**Comment by emptysuns** [comment]
我猜你ipv6地址没加[]，例如`[2001:4860:4801:48::7]:123456`

**Comment by idragonet** [comment]
> 

是的没有加。

**Comment by idragonet** [comment]
> 我猜你ipv6地址没加[]，例如`[2001:4860:4801:48::7]:123456`

解决了，谢谢！
