### ISSUE TITLE
emptysuns大佬，求救

### ISSUE THREAD

**Issue by buitt34** [emptysuns/Hi_Hysteria#119]
bash <(curl -fsSL https://git.io/hysteria.sh)
能不能帮我修改一下这个一键脚本，让他不自动下载最新版本的hy，让他永远下载1.1.0版本就行，我用的dns解锁方式，更新了1.2.0版本以后就用不了了，求救，万分感激

**Comment by buitt34** [comment]
还有一个问题就是1.2.0版本生成的yaml文件，导入openwrt的clash以后，淘宝搜索商品，再点进去，会提示使用了vpn而造成打不开的情况。1.1.0版本的yaml文件没有这个问题

**Comment by emptysuns** [comment]
> bash <(curl -fsSL https://git.io/hysteria.sh) 能不能帮我修改一下这个一键脚本，让他不自动下载最新版本的hy，让他永远下载1.1.0版本就行，我用的dns解锁方式，更新了1.2.0版本以后就用不了了，求救，万分感激

把resolver配置改成`udp://1.2.3.4:53`形式就行，没必要降版本，1.2.0之后变动的就是dns的写法，或者直接删除这一项直接使用系统dns也可以。



> 还有一个问题就是1.2.0版本生成的yaml文件，导入openwrt的clash以后，淘宝搜索商品，再点进去，会提示使用了vpn而造成打不开的情况。1.1.0版本的yaml文件没有这个问题

分流规则使用第三方的，可能部分有异常，看日志把不想加入代理的域名自己改成直连

**Comment by buitt34** [comment]
好的，我试试看，多谢，试完了我再过来留言

**Comment by buitt34** [comment]
你说的这个reslver配置，是改服务端的还是客户端的？还是两个一起改呢？

**Comment by buitt34** [comment]
我把/etc/hihy/conf/hihyServer.json里面的resolver删掉了，最后一部分变成
},
"alpn": "h3",
"acl": "/etc/hihy/acl/hihyServer.acl",
"recv_window_conn": 3407872,
"recv_window_client": 13631488,
"max_conn_client": 4096,
"disable_mtu_discovery": true
"resolve_preference": "46"
}
我用手机的shadowrocket的一键链接试了下，不能解锁奈飞。
然后我又把/etc/hihy/result/hihyClient.json里面的resolver删掉了，最后一部分变成
},
"alpn": "h3",
"acl": "acl/routes.acl",
"mmdb": "acl/Country.mmdb",
"auth_str": "123321",
"server_name": "popsop.wlslls.xyz",
"insecure": false,
"recv_window_conn": 3407872,
"recv_window": 13631488,
"disable_mtu_discovery": true,
"retry": 3,
"retry_interval": 3
}
我用shadowrocket试了下，还是不能解锁奈飞，帮忙看下哪里设置错了？这台服务器我用xray的vless协议，用系统dns是可以正常解锁奈飞的。之前如果是1.0版本，我用openwrt的clash挂一个hy协议，再用passwall挂一个vless协议，就能实现同一台服务器，能享受到hy协议的高速，又能享受到vless协议dns解锁奈飞，但是升级了1.2.0版本以后这样做就不行了

**Comment by buitt34** [comment]
我又试了把那两个hihyClient.json里的resolver改成我的dns，也不行，还是不能解锁

**Comment by buitt34** [comment]
我把/etc/hihy/conf/hihyServer.json的resolver改成我要的dns，重启hy服务，就可以解锁了，多谢大佬指点！刚开始改完没有重启服务，一直不行

**Comment by buitt34** [comment]
大佬，请教一下，你说的日志在哪里看？我用的clash日志里面没有访问网站这些记录
