### ISSUE TITLE
大佬，求助下 openclash下用hy，每天都会出现一次或两三次无法翻墙

### ISSUE THREAD

**Issue by datougua** [emptysuns/Hi_Hysteria#120]
大佬，求助下 openclash下用hy，每天都会出现一次或两三次无法翻墙，必须重启openclash 或者切换到其他节点再切回来，请问如何解决

**Comment by emptysuns** [comment]
没遇到过不知道，你当地运营商断流？

**Comment by buitt34** [comment]
是不是你线路或者服务器有问题，我也是openclash，目前用了10来天了，还没有出现过你这个情况
