### ISSUE TITLE
升级后不能正常运行

### ISSUE THREAD

**Issue by mongoliabao555** [emptysuns/Hi_Hysteria#121]
您好！用脚本更新hihy显示有两行出错，然后更新core到1.2.0后主程序无法正常运行，终止重启后也不能解决问题。证书我是2,使用本地证书文件 。请问如何解决？谢谢

**Comment by emptysuns** [comment]
升级hihy后，使用选项9或者12更新一下配置

**Comment by mongoliabao555** [comment]
谢谢，重新配置解决了。
