### ISSUE TITLE
最近断流比较厉害

### ISSUE THREAD

**Issue by Belly0919** [emptysuns/Hi_Hysteria#122]
前半个月用的体验很好，但最近开始经常断流，不知道怎么回事

**Comment by emptysuns** [comment]
大胆点，最近几天只要出国流量都会阻断，乱杀

**Comment by Belly0919** [comment]
最近是啥大喜日子吗

**Comment by emptysuns** [comment]
> 最近是啥大喜日子吗

https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E5%85%B1%E4%BA%A7%E5%85%9A%E7%AC%AC%E4%BA%8C%E5%8D%81%E6%AC%A1%E5%85%A8%E5%9B%BD%E4%BB%A3%E8%A1%A8%E5%A4%A7%E4%BC%9A

何止大喜，简直比过年还要隆重捏

**Comment by haikouwang** [comment]
> > 最近是啥大喜日子吗
> 
> https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E5%85%B1%E4%BA%A7%E5%85%9A%E7%AC%AC%E4%BA%8C%E5%8D%81%E6%AC%A1%E5%85%A8%E5%9B%BD%E4%BB%A3%E8%A1%A8%E5%A4%A7%E4%BC%9A
> 
> 何止大喜，简直比过年还要隆重捏

哈哈哈哈哈

**Comment by haikouwang** [comment]
哈哈哈哈
