### ISSUE TITLE
一台vps開三種協議 udp,faketcp,wechat ,可否作到？

### ISSUE THREAD

**Issue by Job28703** [emptysuns/Hi_Hysteria#123]
一台vps開三種協議 udp,faketcp,wechat ,以不同的port分開可否作到？
這樣比較可避開封殺！！

**Comment by emptysuns** [comment]
可以做到，但是这样和一个有区别？

**Comment by Job28703** [comment]
支持大佬，请问大佬，可捐助你下，如何汇？

**Comment by emptysuns** [comment]
> 支持大佬，请问大佬，可捐助你下，如何汇？

谢谢，不需要，点个星星就行了
