### ISSUE TITLE
不支持该系统

### ISSUE THREAD

**Issue by wxjer** [emptysuns/Hi_Hysteria#126]
Linux version 5.10.0-11-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.92-1 (2022-01-18)
请大佬指示

**Comment by emptysuns** [comment]
`arch`返回结果是什么

**Comment by wxjer** [comment]
x86_64

**Comment by emptysuns** [comment]
支持啊...有详细log吗？

**Comment by wxjer** [comment]
莫得， 
![image](https://user-images.githubusercontent.com/13941095/187220631-36f7df34-4edf-4637-b171-65027190f255.png)

**Comment by emptysuns** [comment]
这商家乱改镜像...dd一下系统吧，懒得适配这种奇奇怪怪的问题

**Comment by wxjer** [comment]
哈哈好吧，用它提供的几个镜像重装了几次都不行，搞不好都改了，先用xui了
