### ISSUE TITLE
搭建的游戏代理，延迟不错。但为什么PS5一直显示NAT3

### ISSUE THREAD

**Issue by longxx** [emptysuns/Hi_Hysteria#127]
同样的服务器用trojan就是NAT2，用的路由器passwall，tcp,udp全部转发，全局模式
不知道是协议的问题，还是脚本问题，还是passwall设置不对？

**Comment by emptysuns** [comment]
脚本什么也没做，不背锅，hy的代理udp貌似有问题来着，之前看到过issue不知道解决了吗

**Comment by longxx** [comment]
> 脚本什么也没做，不背锅，hy的代理udp貌似有问题来着，之前看到过issue不知道解决了吗

好的，我排查一下看问题再哪里再来反馈

**Comment by longxx** [comment]
什么办法都试了，不行。最后本地套socks5得到nat2。联机真爽，感谢脚本主

**Comment by zhezhe168** [comment]
> 同样的服务器用trojan就是NAT2，用的路由器passwall，tcp,udp全部转发，全局模式 不知道是协议的问题，还是脚本问题，还是passwall设置不对？

你这个问题解决了么？我也有这个问题

**Comment by longxx** [comment]
> > 同样的服务器用trojan就是NAT2，用的路由器passwall，tcp,udp全部转发，全局模式 不知道是协议的问题，还是脚本问题，还是passwall设置不对？
> 
> 你这个问题解决了么？我也有这个问题

上面说了，套个socks5
