### ISSUE TITLE
下载文件路由器卡死，红米2100

### ISSUE THREAD

**Issue by teddy780102** [emptysuns/Hi_Hysteria#129]
非常奇怪的问题，paswall或openclas使用hysteria节点，只要下载国外文件路由器就卡死，但是下载国内文件没事，
换用v2ray节点国内国外下载一切正常
求高手解惑！！

**Comment by emptysuns** [comment]
quic开销比tcp cpu开销大多了，路由器就别想了hy了，上卵漏由吧

**Comment by teddy780102** [comment]
但是看油管视频速度也很快呀，看视频跟下载有区别吗？

**Comment by teddy780102** [comment]
多谢大佬提醒，已经解决，把up down 参数改小一些可以了，说明hysteria确实暴力

**Comment by teddy780102** [comment]
再次感谢大佬指点迷津
