### ISSUE TITLE
使用过程中出现断流现象，间歇性出现无法连接的问题

### ISSUE THREAD

**Issue by quanjindeng** [emptysuns/Hi_Hysteria#13]
在两台vps上（一台racknerd，一台couldcone）安装了可以正常使用，但是会间歇性出现无法连接的问题。比如油管看评论时，下滑着突然刷不出剩余评论。此时检查连接，客户端显示无法连接，此时测试这台vps上其他协议的节点正常。间隔大概是十几分钟到几十分钟，大概一分钟左右恢复正常。
使用的udp模式，测速能达到100-200mbps，ping延迟200ms左右。在路由器passwall和安卓客户端Sager Net均出现此问题。
请问这是正常的吗，有什么办法优化下吗？速度确实提升明显，但遇到这个问题还是挺影响使用的。

**Comment by quanjindeng** [comment]
忘了补充了，用的是移动宽带

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/9
你可能需要的是这个...
我单方面猜测是你本地移动对udp策略就是和你如上描述的一样，保证你的上行速度和下行速度不乱写的话(因为hysteria的对udp的发包非常暴力，唯一的刹车就是那个客户端的上下行速度限制),这种情况可以尝试用faketcp模式or开启obfs试试。

**Comment by quanjindeng** [comment]
感谢，看来我这就是被本地运营商限制了
