### ISSUE TITLE
请问如何查看服务端的日志

### ISSUE THREAD

**Issue by slcf2003** [emptysuns/Hi_Hysteria#131]
这两天感觉遇到了断流，想试着看看服务器端日志有没有具体的报错信息

**Comment by emptysuns** [comment]
有人在hysteria仓库提过issue，原作者不希望在配置里指定输出log文件
想要用systemd还能看log就要重定向输出到某个文件里，hihy目前不支持直接查看日志。

你可以先用`hihy`命令，停止systemd创建的守护进程

然后用`/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server`，查看详细日志

准备以后加入看日志的选项

**Comment by slcf2003** [comment]
非常感谢。我是在hysteria的issue里看见有人用journalctl去看日志 [https://github.com/HyNetwork/hysteria/issues/426](url)

**Comment by emptysuns** [comment]
> 
journalctl也可以，不过你可能需要改一下hihy.service因为它默认日志等级是warn

**Comment by moranno** [comment]
> > 
> 
> journalctl也可以，不过你可能需要改一下hihy.service因为它默认日志等级是warn

请问如何修改默认的日志等级？
