### ISSUE TITLE
电脑、软路由都可以使用，最近更新之后，用苹果（小火箭）和安卓（clashmetafor 安卓）无法使用

### ISSUE THREAD

**Issue by datougua** [emptysuns/Hi_Hysteria#135]
电脑、软路由都可以使用，最近更新之后，用苹果（小火箭）和安卓（clashmetafor 安卓）无法使用
"protocol": "wechat-video",
"server_name": "wechat.com"

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/main/md/issues.md#20220910

**Comment by sdshdv** [comment]
每次更新版本都要再重新配置一次，不然就会出现不能用的情况
