### ISSUE TITLE
双端更新正常 passwall 121版本无法正常启动

### ISSUE THREAD

**Issue by KsaNL** [emptysuns/Hi_Hysteria#136]
![image](https://user-images.githubusercontent.com/73447685/190881191-6764b6a3-13b1-4dbd-9482-3010c3cd99de.png)

**Comment by emptysuns** [comment]
单看日志是2080端口不知道为什么拒绝访问
这和升级hysteria版本无关，应该是你passwall的问题

**Comment by KsaNL** [comment]
![image](https://user-images.githubusercontent.com/73447685/190899732-9d21ba36-6861-4f1f-bb1f-25df8dab2c6f.png)

**Comment by KsaNL** [comment]
解决了 passwall导入 没有更新三个个字段 
"insecure": false,
"recv_window_conn": 22282240,
"recv_window": 89128960,
![image](https://user-images.githubusercontent.com/73447685/190899992-dfcc73c2-cdb8-4370-b98a-93e03d490736.png)
