### ISSUE TITLE
升级问题，昨天升级之后openclash不能用了，同样节点passwall可以使用

### ISSUE THREAD

**Issue by teddy780102** [emptysuns/Hi_Hysteria#137]
升级问题，昨天升级之后openclash不能用了，同样节点passwall可以使用

**Comment by teddy780102** [comment]
手机端clash meta也挂了

**Comment by emptysuns** [comment]
你需要更新一下你客户端，保证它们hysteria版本是大于1.2.1的
否则wechat-video无法正常用，如果你的客户端版本没有跟进最新的版本，请从它们的仓库去提issue。
你可以先用udp协议替代wechat-video
