### ISSUE TITLE
passwall Hysteria

### ISSUE THREAD

**Issue by alegoho** [emptysuns/Hi_Hysteria#14]
配置完服务端后怎么搞passwall都不通，不知道那里出错

**Comment by alegoho** [comment]
> 先保证不用passwall是可以通的，然后再照着config填，虽然hysteria提倡过标准的分享链接形式，但是没一个客户端兼容，就搁置了，可以考虑接下来在readme里面加一个passwall的example。

是用官方那个客户端吗？

**Comment by emptysuns** [comment]
![hysteria-passwall](https://static01.imgkr.com/temp/c666c1ea9878482ab15f52c647c3ce41.png)

**Comment by alegoho** [comment]
感谢回复，搞了一个上午，无域名自签还是有域名，还是不通。

**Comment by emptysuns** [comment]
提供一些详细信息吧...

**Comment by alegoho** [comment]
我就在PASSWALL上，都按你上面的东西填，就是不通，我也不知道能提供什么信息了

**Comment by emptysuns** [comment]
1. `systemctl status hysteria`
2. `iptables -L`
3. 保证你服务商的**面板**防火墙是打开的
4. 或者你本地就是锁死udp连接，那么请保证udp是可以连接的，用iperf测试一下 https://github.com/emptysuns/Hi_Hysteria/issues/9

能出错就如上几个方面了...

**Comment by alegoho** [comment]
● hysteria.service - hysteria:Hello World!
   Loaded: loaded (/etc/systemd/system/hysteria.service; enabled; vendor preset: disabled)
   Active: active (running) since 日 2022-03-06 04:00:01 GMT; 4h 35min ago
 Main PID: 5098 (hysteria)
   CGroup: /system.slice/hysteria.service
           └─5098 /etc/hysteria/hysteria --log-level warn -c /etc/hysteria/config.json server

3月 06 04:00:01 instance-20220305-1140 systemd[1]: Started hysteria:Hello World!.





ACCEPT     udp  --  anywhere             anywhere             udp dpt:10099 /* allow udp(hihysteria) */

**Comment by emptysuns** [comment]
那就是你的服务提供商把udp限死了，试试faketcp吧

**Comment by alegoho** [comment]
还是不行，放弃了

**Comment by alegoho** [comment]
感谢大佬的一键，我更新了PASSWALL现在已经连通了

**Comment by jtzylxb** [comment]
我也遇到了同样的问题，桌面客户端能正常使用，就是PASSWALL用HY协议怎么也上不去，换其他协议能正常使用

**Comment by github-office** [comment]
> 我也遇到了同样的问题，桌面客户端能正常使用，就是PASSWALL用HY协议怎么也上不去，换其他协议能正常使用

更新一下openwrt，现在问题少多了，而且有更多的插件支持hy了。

**Comment by jtzylxb** [comment]
> > 我也遇到了同样的问题，桌面客户端能正常使用，就是PASSWALL用HY协议怎么也上不去，换其他协议能正常使用
> 
> 更新一下openwrt，现在问题少多了，而且有更多的插件支持hy了。

我目前用的是OpenWrt R22.7.7 Buddha V5 [2022] Compiled by eSir / LuCI Master (git-22.211.60098-feaa27a)这个版本，因为没有能力自己打包，用的网上的大佬打包的固件
