### ISSUE TITLE
重装之后服务端貌似正常但实际不通

### ISSUE THREAD

**Issue by ydqsbfsyi** [emptysuns/Hi_Hysteria#142]
又重装vps了。 hihy安装之后, server up and running. 但实际上不能翻------ 尝试看视频， socks5 tcp error. 高手指点一下?

**Comment by emptysuns** [comment]
看什么视频？

**Comment by ydqsbfsyi** [comment]
> 看什么视频？

youtube

**Comment by ZevAlain** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/main/md/issues.md#20220910
