### ISSUE TITLE
[Question] <查看当前配置> 可能存在问题

### ISSUE THREAD

**Issue by QIN2DIM** [emptysuns/Hi_Hysteria#143]
## Description

配置初始化后，重新进入脚本选择 `13) 修改当前协议类型` 之后再选择 `8)查看当前配置` 打印的是初始化时的配置，即，协议名称仍是初始化时的内容。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/09f25029825e27451bb5de16bc9cc2d360005c8e

**Comment by QIN2DIM** [comment]
虽然但是，只有 copy 的配置信息变了，打印的一键链接和 meta 配置文件还是没跟上

**Comment by emptysuns** [comment]
感谢再次提醒，很是抱歉，最近现实生活中有点琐事
修改bug时很着急，想着尽快适配新的更新，注意力不集中，没注意到还有问题
