### ISSUE TITLE
acl存在问题

### ISSUE THREAD

**Issue by Hasakiii8808** [emptysuns/Hi_Hysteria#146]
使用v2rayn客户端，但是看样子目前路由规则依然动用了acl文件夹中的route文件，目前发现zhihu.com无法正常访问，问如何使用v2rayn自己的路由规则，谢谢

**Comment by emptysuns** [comment]
v2n据我了解，没办法，如果想更方便自定义路由规则，建议使用nekoray。

但根据您描述的问题，zhihu.com访问不正常应该不是acl问题。

**Comment by Hasakiii8808** [comment]
v2rayn返回的问题如下：
2022-10-18T11:44:42+08:00[36m [INFO] [dst:www.zhihu.com:443] [error:dial tcp [2409:8c20:28c1:100:6c::23]:443: connectex: A socket operation was attempted to an unreachable network.] [0mHTTP error
我试着在json文件中把"acl": "acl/routes.acl",这一行删除之后，v2rayn端显示所有链接全走proxy，zhihu恢复正常。
我也去route.acl里面看了看，zhihu的规则是direct，把这一行注释掉或者是删掉还是无法访问。
最新尝试，把zhihu.com改成proxy就可以访问了，不过是走代理访问的zhihu。目前只发现了这一个网站有这个问题，别的都正常，可能是zhihu.com自己的问题吧

**Comment by Hasakiii8808** [comment]
> v2n据我了解，没办法，如果想更方便自定义路由规则，建议使用nekoray。
> 
> 但根据您描述的问题，zhihu.com访问不正常应该不是acl问题。

使用了nekoray，非常好用，谢谢
