### ISSUE TITLE
v2rayN可以连上，Openwrt passwall无法连接。

### ISSUE THREAD

**Issue by h40st3r** [emptysuns/Hi_Hysteria#148]
用脚本安装好后，将配置复制到config.json，windows 系统中使用v2rayn可以连上并正常使用。
但是在Openwrt中，passwall无法连接到节点，显示“超时”。Openwrt的配置我参考了wiki中的openwrt客户端配置，也与config.json中的内容核对了，请问是怎么回事呢？
<img width="905" alt="屏幕截图 2022-10-30 115909" src="https://user-images.githubusercontent.com/11023703/198861956-bec3e5ac-d1fc-460f-b4bc-077029d3cb17.png">

**Comment by emptysuns** [comment]
提供一下出错的log吧

**Comment by h40st3r** [comment]
> 

passwall的日志没有相关内容。

**Comment by emptysuns** [comment]
直接用op命令行用hysteria核心运行看看

`/usr/bin/hysteria -c config.json client`

**Comment by mingmenmama** [comment]
混淆密码清空就好了

**Comment by francis5959** [comment]
paswall链接超时，看服务端似正常

**Comment by francis5959** [comment]
换成faketcp协议可连接了，其他udp、wechat-video都连接失败

**Comment by madyounghe** [comment]
passwall似乎对tls的证书要求更高，必须是fullchain.cer。

**Comment by stefma2** [comment]
我找到原因了。  openwrt时间不准确  你节点有时间验证

**Comment by emptysuns** [comment]
> 2025/07/30 16:44:27.907300 [Warning] common/errors: This feature WebSocket transport (with ALPN http/1.1, etc.) is deprecated and being migrated to XHTTP H2 & H3. Please update your config(s) according to release note and documentation before removal. 日志提示这个，是怎么回事

xray的warn和hy2没任何关系
