### ISSUE TITLE
DNS流媒体解锁

### ISSUE THREAD

**Issue by zhaolu1206** [emptysuns/Hi_Hysteria#149]
hysteria无法使用DNS流媒体解锁，能否出一个教程？或者在脚本中增加使用DNS解锁流媒体的功能？

**Comment by emptysuns** [comment]
修改服务端`/etc/hihy/conf/hihyServer.json`
找到dns配置`resolver`，修改为`udp://你的dns解锁ip:53`

**Comment by zhaolu1206** [comment]
> 修改服务端`/etc/hihy/conf/hihyServer.json` 找到dns配置`resolver`，修改为`udp://你的dns解锁ip:53`，重启生效。

谢谢，请问这种方法支持填写域名吗？

**Comment by emptysuns** [comment]
....

> > 修改服务端`/etc/hihy/conf/hihyServer.json` 找到dns配置`resolver`，修改为`udp://你的dns解锁ip:53`，重启生效。
> 
> 谢谢，请问这种方法支持填写域名吗？
要不删掉resolver，重启hy
然后用系统dns

**Comment by zhaolu1206** [comment]
> 

谢谢，这样好，解锁不影响定时脚本更新IP
