### ISSUE TITLE
hysteria 是否像kcptun一样, 靠流量换速度?

### ISSUE THREAD

**Issue by Etherealblade** [emptysuns/Hi_Hysteria#15]
emptysuns, 您好. 
如题, 想向您请教一下, hysteria 是否像kcptun一样, 靠流量换速度? 我的意思是, 我用过kcptun, 它就是靠大量地发包, 用vps很多流量来换取速度, 那hysteria是不是也用流量换速度?

**Comment by emptysuns** [comment]
不是，hysteria基于quic，最主要的区别是将quic的拥塞控制改的非常暴力，才得以在恶劣网络下有好的表现，它并不向kcptun一样多倍发包。
但是hysteria的“流量利用率”也不是100%。由于udp是无连接的，当你发生丢包时，hysteria会采用重传的方式来弥补。所以流量利用率是取决于你的丢包率的。
