### ISSUE TITLE
多用户问题

### ISSUE THREAD

**Issue by alegoho** [emptysuns/Hi_Hysteria#150]
作者好像加入了多用户功能，你能不能添加上？单端口多用户或者多端口多用户，谢谢!

https://github.com/HyNetwork/hysteria/issues/41#issuecomment-1275877560

**Comment by emptysuns** [comment]
多端口多用户，需要启动不同进程
单端口多用户，充其量只是认证口令不一致

hysteria虽然提供了流量统计功能，但是hihy目前不支持。
所以我不理解为什么需要多用户
