### ISSUE TITLE
v2rayN可以连上，clash-meta连接不上

### ISSUE THREAD

**Issue by unborn-chy** [emptysuns/Hi_Hysteria#151]
config.json去掉了 "acl"、"mmdb"使用v2rayN能连上。
使用默认生成的 metaHys.yaml，不管是win还是andorid都连不上
![image](https://user-images.githubusercontent.com/52943447/199764796-180954bc-0e27-42f6-acc0-8c134785f4d3.png)
![image](https://user-images.githubusercontent.com/52943447/199764911-ac9c5768-c7d6-4b6d-a7ff-7ab76caeccb5.png)
![image](https://user-images.githubusercontent.com/52943447/199764949-e7a18c4e-5264-4b7c-950a-465f53e0b725.png)
没有日志信息的

**Comment by emptysuns** [comment]
贴出metaHys.yaml的配置看看，因为这个配置里使用了ghproxy.com的服务加速分流规则获取，请保证访问这个网站没问题

**Comment by unborn-chy** [comment]
配置如下：
`mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 114.114.114.114
    - 223.5.5.5

proxies:
  - name: "Hys-www.62655777.xyz"
    type: hysteria
    server: www.62655777.xyz
    port: 10032
    auth_str: 62655777
    alpn: h3
    protocol: wechat-video
    up: 55
    down: 110
    sni: www.62655777.xyz
    skip-cert-verify: false
    recv_window_conn: 10223616
    recv_window: 40894464
    disable_mtu_discovery: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
     - Hys-www.62655777.xyz

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
`

**Comment by emptysuns** [comment]
你meta是什么版本的？如果你更新了服务端，wechat-video需要配合hysteria 1.2.1以上版本，**我猜**是这个问题

**Comment by unborn-chy** [comment]
![image](https://user-images.githubusercontent.com/52943447/199973157-fed01412-c739-45f3-99f4-7798e2944515.png)
![image](https://user-images.githubusercontent.com/52943447/199973282-e07c3568-4b92-48a9-b490-ed15fb9971cb.png)
放弃了，现在好像有个更严重的问题，昨天刚搭建的，今早上端口就被封了。因为不太懂 刚接触这个，端口被封一般有那些情况呢

**Comment by emptysuns** [comment]
https://github.com/MetaCubeX/Clash.Meta/releases/tag/Prerelease-Alpha
尝试这个版本
关于封端口的问题大概率是单端口的udp QoS，目前hy正在测试服务端多端口监听，可以期待一下

**Comment by unborn-chy** [comment]
谢谢你，因为我在**常见问题** 那里看到了相关的回答，同时也会报这个错误 `[error:timeout: no recent network activity] Failed to initialize client`,所以就把之前的回答删掉了，想试试看能不能解决，没问题的话后面再回答，没想到还是被看到之前的回答了。目前手机端使用**Matsuri**是没有问题的，再次感谢。
