### ISSUE TITLE
【疑问】使用不同网络时速度和延迟的设定

### ISSUE THREAD

**Issue by 2ndMessiah** [emptysuns/Hi_Hysteria#155]
首先谢谢OP写的脚本，很省心。

有关于Hy配置的疑问：同一个小鸡，我三大运营商都在用，带宽和延迟差别有点大。比如移动网络，下行最大50Mbps，家里宽带可能有500Mbps。这种情况下应该怎么合理的设定参数？

请指教。

谢谢。

**Comment by emptysuns** [comment]
hy在不同网络下表现都非常好

您输入的上下行速度会影响客户端的访问速度，如果您设置的速度过大，导致服务端给您发送的速率过快，会影响峰值速度。

输入的延迟会影响hy服务端发送窗口的调节

我的建议是您只需要调节不同网络下的上下行速度就行了，hihy设置buffer size留下了相当多的空余

**Comment by QIN2DIM** [comment]
## Ignore

@2ndMessiah 你可以在晚高峰/闲时挂这个节点的代理跑一下 Speedtest，Netflix Fast，以及 YouTube ConnectionSpeed 如果下行速度能顶满 50Mbps，就逐步上调单客户端的最大下行的数值（每 50Mbps 试一次）。

脚本运行时接收的 delay 和 download 用于设置协商窗口。

https://github.com/emptysuns/Hi_Hysteria/blob/efc001bfce450261bf6b1b94c07f0d2560414a1b/server/install.sh#L385-L388

一般情况下，设置到 110Mbps 最大下行，协商窗口保持默认，已经能满足大多数场景的网络冲浪，如果你要执行高速的代理下载，你还得看 VPS 本身是否有带宽下行限制。一些给到 CN2 GIA 线路的美洲服务器一般都是 1Gbps 下行，但也有不少（亚洲）设备是 20~500Mbps。

## TL;TD

你的最大下行应为 `down_mbps = min(家宽, vps下行带宽)`
最大上行应为 `up_mbps = down_mbps / 10`

在满足最佳实践的情况下，网上冲浪瓶颈一般来自客户端配置。

**Comment by 2ndMessiah** [comment]
TY'all !!!

 Crystal clear now!
