### ISSUE TITLE
更新Clash.meta后，提示proxy 0: 'alpn' is not a slice

### ISSUE THREAD

**Issue by UncleUncleWang** [emptysuns/Hi_Hysteria#156]
rt，更新clash.meta for Android 2.5.12之后，出现proxy 0: 'alpn' is not a slice，重新配置无法解决

**Comment by emptysuns** [comment]
clash_meta更新了配置，新版本客户端改变了alpn配置写法，等我更新一下

**Comment by emptysuns** [comment]
已修复
请通过选项`11`更新hihy后
通过选项`12`重置或者选项`9`重新配置即可
