### ISSUE TITLE
在ipv6单栈机无法使用，必须依靠warp。

### ISSUE THREAD

**Issue by gnz1123** [emptysuns/Hi_Hysteria#157]
要怎样配置才能在纯ipv6机使用，比如scaleway星辰这类的？

**Comment by emptysuns** [comment]
使用wgcf之后再用，起码有个v4出口，只有纯v6也没什么意义去适配

**Comment by gnz1123** [comment]
> 使用wcf再用，起用v4之后的出口，只有v6没有什么有意义去纯码



> 使用wgcf之后再用，起码有个v4出口，只有纯v6也没什么意义去适配

一些低价纯v6机配好NAT64后速度非常不错，或者直接warp也很好，但是warp+hy会明显减速。

**Comment by emptysuns** [comment]
配置文件在`/etc/hihy/conf/hihyServer.json`,将下方有**中文**的配置，根据原来的配置修改一下，然后替换掉，重启hysteria即可
```
{
"listen": ":端口",
"protocol": "udp",
"disable_udp": false,
"cert": "证书",
"key": "证书",
"auth": {
	"mode": "password",
	"config": {
	"password": "密码"
	}
},
"alpn": "h3",
"acl": "/etc/hihy/acl/hihyServer.acl",
"recv_window_conn": 123456.,
"recv_window_client": 654321,
"max_conn_client": 4096,
"disable_mtu_discovery": true,
}
```

**Comment by gnz1123** [comment]
> 配置文件在`/etc/hihy/conf/hihyServer.json`,将下方有**中文**的配置，根据原来的配置修改一下，然后替换掉，重启hysteria即可
> 
> ```
> {
> "listen": ":端口",
> "protocol": "udp",
> "disable_udp": false,
> "cert": "证书",
> "key": "证书",
> "auth": {
> 	"mode": "password",
> 	"config": {
> 	"password": "密码"
> 	}
> },
> "alpn": "h3",
> "acl": "/etc/hihy/acl/hihyServer.acl",
> "recv_window_conn": 123456.,
> "recv_window_client": 654321,
> "max_conn_client": 4096,
> "disable_mtu_discovery": true,
> }
> ```

谢谢大佬！！
