### ISSUE TITLE
导入配置错误

### ISSUE THREAD

**Issue by fadedFantastic** [emptysuns/Hi_Hysteria#158]
使用release提供的clashverge，按文档导入metaHys.yaml配置，右键点使用提示failed to update clash config with status 400
![image](https://user-images.githubusercontent.com/9108382/201463384-80d8afd2-39a3-4f40-bd56-9819891de0b8.png)

**Comment by emptysuns** [comment]
https://docs.metacubex.one/function/proxy/hysteria
看看是不是alpn写法变更的问题

**Comment by fadedFantastic** [comment]
> https://docs.metacubex.one/function/proxy/hysteria 看看是不是alpn写法变更的问题

![image](https://user-images.githubusercontent.com/9108382/201465359-54c53d9d-7702-4314-be6a-cada6655b3da.png)
看了下似乎写的没问题？

**Comment by emptysuns** [comment]
> > https://docs.metacubex.one/function/proxy/hysteria 看看是不是alpn写法变更的问题
> 
> ![image](https://user-images.githubusercontent.com/9108382/201465359-54c53d9d-7702-4314-be6a-cada6655b3da.png) 看了下似乎写的没问题？

用cli直接运行核心看看，具体哪错了

**Comment by fadedFantastic** [comment]
> > > https://docs.metacubex.one/function/proxy/hysteria 看看是不是alpn写法变更的问题
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/9108382/201465359-54c53d9d-7702-4314-be6a-cada6655b3da.png) 看了下似乎写的没问题？
> 
> 用cli直接运行核心看看，具体哪错了

啊 具体咋操作 菜鸡流泪
刚刚又试了下release里提供的v2rayN，也不行，下面是报错。 手机上用sagerNet导入配置的倒是连上了。
![image](https://user-images.githubusercontent.com/9108382/201466160-860a6097-153d-419f-bc0d-410a8b47f5c4.png)

**Comment by fadedFantastic** [comment]
v2rayN直接用的服务器上生成的config.json文件。clash用的下面的metaHys.yaml。
![image](https://user-images.githubusercontent.com/9108382/201467166-96d3e0fe-99f1-4c11-9733-12a0f0256bb8.png)

**Comment by emptysuns** [comment]
https://hysteria.network/zh/docs/common-problems/#erro-errortimeout-no-recent-network-activity

**Comment by fadedFantastic** [comment]
最后转战nekoray，用生成的链接是没问题的

**Comment by andy0532** [comment]
一模一样的问题！

**Comment by andy0532** [comment]
改了一下配置文件，然后又该回去，其实就是什么都没改，然后就好了。
应该是自动生成的配置文件问题。

**Comment by andy0532** [comment]
原因找到了，是配置文件的alpn字段有问题，改成alpn: h3就可以了。

**Comment by emptysuns** [comment]
> 原因找到了，是配置文件的alpn字段有问题，改成alpn: h3就可以了。

你不是1.13.2以上版本吧，最新版写法变了
https://docs.metacubex.one/function/proxy/hysteria
不向下兼容，这也没什么好办法，只能跟着更新走
