### ISSUE TITLE
FIREWALLD OPEN FAIL

### ISSUE THREAD

**Issue by en0xh** [emptysuns/Hi_Hysteria#159]
firewalld服务的状态是正常 centos7
使用的最新版本的脚本
关闭firewalld后正常

**Comment by emptysuns** [comment]
检测逻辑是这个`firewall-cmd --list-ports --permanent | grep -q $yourPort`
说明没有成功添加防火墙规则?
能否打开firewalld后，手动运行下方命令然后查看一下是否成功增加规则?
```
firewall-cmd --zone=public --add-port=yourPort/udp --permanent
firewall-cmd --reload
```

**Comment by en0xh** [comment]
显示already_enabled
说明脚本能够打开此端口

**Comment by emptysuns** [comment]
> 显示already_enabled 说明脚本能够打开此端口

https://github.com/emptysuns/Hi_Hysteria/blob/92e53a2f9726fb5b491f1b0bc57fefad52f858f2/server/install.sh#L786

如果能打开成功，那或许是**再**检测端口是否放行的这个条件出了问题
```
firewall-cmd --list-ports --permanent | grep -q "$1"
```
把`$1`换成端口数值看看返回什么
