### ISSUE TITLE
HyNetwork/hysteria更名为了apernet/hysteria，安装失败

### ISSUE THREAD

**Issue by hu-min** [emptysuns/Hi_Hysteria#162]
Debian9/10，在安装BT后，再用脚本安装Hysteria后报错，安装失败
`您选择跳过端口跳跃/多端口(Port Hopping)功能 `
`请输入您到此服务器的平均延迟,关系到转发速度(默认200,单位:ms): `
`80`
``
`期望速度,这是客户端的峰值速度,服务端默认不受限。Tips:脚本会自动*1.10做冗余，您期望过低或者过高会影响转发效率,请如实填写! `
`请输入客户端期望的下行速度:(默认50,单位:mbps): `
`200`
`请输入客户端期望的上行速度(默认10,单位:mbps):`
`50`
`请输入认证口令: `
`128993209`
``
`配置录入完成!`
 ``
`执行配置... `
`UFW OPEN FAIL: 18024`

**Comment by emptysuns** [comment]
你本地ufw开着吗？

**Comment by hu-min** [comment]
开了，ufw disable后，同样错误。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/92e53a2f9726fb5b491f1b0bc57fefad52f858f2/server/install.sh#L808

只有检测ufw是active才会向它添加规则，请问你的脚本是最新版吗`0.4.3.b`

**Comment by hu-min** [comment]
> https://github.com/emptysuns/Hi_Hysteria/blob/92e53a2f9726fb5b491f1b0bc57fefad52f858f2/server/install.sh#L808
> 
> 只有检测ufw是active才会向它添加规则，请问你的脚本是最新版吗`0.4.3.b`

> 你好，我看了一下，本版号：`Version: 0.4.3.b`

> 因为之前服务器上没安装宝塔，安装宝塔后，发现宝塔有问题，于是我就在新创建的服务器上先安装宝塔试试，结果Debian9/10都是一样的问题。我hihy，选5会提示`重启成功`，选6提示`Dead!hysteria未正常运行!`，在`/etc/hihy/`下会创建目录目录，只有`bin`文件夹中存在`aapS`文件，其他都是空文件。如果大佬需要什么日志，可以告知，我会贴出来的。

**Comment by emptysuns** [comment]
这个**重启成功**没有对**是否**成功做判断，只是重启了systemd的守护进程。
根据描述，你的文件或许被所用的面板给删除了，我不清楚这个面板做了什么，无法给你帮助。

**Comment by hu-min** [comment]
不是被面板删除了，而是安装宝塔后，无法再安装hihy了

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/e30be013189e34721bc70febac65190d92abccfd
