### ISSUE TITLE
使用现在的脚本 下载hy的包 大小为0

### ISSUE THREAD

**Issue by fireinrain** [emptysuns/Hi_Hysteria#163]
试了好多次 /etc/hihy/bin/appS的大小为0.
无法下载到正确的程序大小
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14249262/202852882-b174daaf-2b18-4814-90a5-ad34a47d24c6.png">

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/162

**Comment by fireinrain** [comment]
> #162

使用最新的脚本依然是没办法安装 之前是可以的(昨天使用大佬您的脚本可以)

**Comment by fireinrain** [comment]
> > #162
> 
> 使用最新的脚本依然是没办法安装 之前是可以的(昨天使用大佬您的脚本可以)

<img width="879" alt="image" src="https://user-images.githubusercontent.com/14249262/202856411-2f61b5d0-d1fc-4957-9992-09356623af53.png">
按照最新的脚本一步一步安装hysteria 没办法启动  查看脚本下载的hysteria编译文件  如下图：

<img width="956" alt="image" src="https://user-images.githubusercontent.com/14249262/202856483-9db843f4-ee61-44e5-a3d2-887b373aa145.png">

之前的hy这个文件夹我都是删除的 所以这个配置文件 都是新的脚本下载的 但是没办法下载到完整的hysteria文件

系统环境 debian11  平台amd64

**Comment by emptysuns** [comment]
**12) 完全重置所有配置**
用这个选项重置一下呢，我刚才试了`0.4.3.c`没问题
hysteria仓库变更了用户名，也没有什么好解决办法，只能跟着兼容

**Comment by fireinrain** [comment]
> **12) 完全重置所有配置** 用这个选项重置一下呢，我刚才试了`0.4.3.c`没问题 hysteria仓库变更了用户名，也没有什么好解决办法，只能跟着兼容

我试一下重置

**Comment by fireinrain** [comment]
> **12) 完全重置所有配置** 用这个选项重置一下呢，我刚才试了`0.4.3.c`没问题 hysteria仓库变更了用户名，也没有什么好解决办法，只能跟着兼容

Tips:hihy 命令再次运行本脚本.
............................................. 
############################### 

..................... 
1)  安装 hysteria 
2)  卸载 
..................... 
3)  启动 
4)  暂停 
5)  重新启动 
6)  运行状态 
..................... 
7)  更新Core 
8)  查看当前配置 
9)  重新配置 
10) 切换ipv4/ipv6优先级 
11) 更新hihy 
12) 完全重置所有配置 
13) 修改当前协议类型 
14) 查看实时日志 

############################### 



0)退出 
............................................. 
请选择:12
Start Uninstall!


--2022-11-19 23:01:32--  https://git.io/rmhysteria.sh
Resolving git.io (git.io)... 140.82.113.22
Connecting to git.io (git.io)|140.82.113.22|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/emptysuns/Hi_Hysteria/main/server/uninstall.sh [following]
--2022-11-19 23:01:32--  https://raw.githubusercontent.com/emptysuns/Hi_Hysteria/main/server/uninstall.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2136 (2.1K) [text/plain]
Saving to: ‘/tmp/uninstall.sh’

/tmp/uninstall.sh                100%[=======================================================>]   2.09K  --.-KB/s    in 0s      

2022-11-19 23:01:32 (21.0 MB/s) - ‘/tmp/uninstall.sh’ saved [2136/2136]
 -------------------------------------------
|**********      Hi Hysteria       **********|
|**********    Author: emptysuns   **********|
|**********     Version: 0.4.3.c     **********|
 -------------------------------------------
Tips:hihy 命令再次运行本脚本.
............................................. 
############################### 

..................... 
1)  安装 hysteria 
2)  卸载 
..................... 
3)  启动 
4)  暂停 
5)  重新启动 
6)  运行状态 
..................... 
7)  更新Core 
8)  查看当前配置 
9)  重新配置 
10) 切换ipv4/ipv6优先级 
11) 更新hihy 
12) 完全重置所有配置 
13) 修改当前协议类型 
14) 查看实时日志 

############################### 



0)退出 
............................................. 
请选择:1
Ready to install.
 

Update.wait... 
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                                                                           
Hit:3 https://download.docker.com/linux/debian bullseye InRelease                                                               
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease                                                       
Hit:5 https://nginx.org/packages/mainline/debian bullseye InRelease
Reading package lists... Done             
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.

Done.
Install wget curl lsof 
*wget 
Installed.Ignore. 
*curl 
Installed.Ignore. 
*lsof 
Installed.Ignore. 

Done. 
The Latest hysteria version: 
Download...

Download completed. 
开始配置: 
请选择证书申请方式:

1、使用ACME申请(推荐,需打开tcp 80/443)
2、使用本地证书文件
3、自签证书

输入序号:
3
请输入自签证书的域名(默认:wechat.com): 
hysteria.131433.xyz

您已选择自签hysteria.131433.xyz证书加密.公网ip:173.249.198.24 


请输入你想要开启的端口,此端口是server端口,建议10000-65535.(默认随机) 
53423
选择协议类型:

1、udp(QUIC,可启动端口跳跃)
2、faketcp
3、wechat-video(默认)

输入序号:
1
传输协议:udp 

您选择udp协议,可使用[端口跳跃/多端口](Port Hopping)功能 
强烈推荐,但是处于beta测试中,目前hihy对此功能支持尚不完善,后续会慢慢修改更新,如有问题请反馈给作者,谢谢!
目前客户端仅V2rayN/Nekoray支持此功能,其他客户端请等待后续更新支持.
 
Tip: 长时间单端口 UDP 连接容易被运营商封锁/QoS/断流,启动此功能可以有效避免此问题.
更加详细介绍请参考: https://github.com/emptysuns/Hi_Hysteria/blob/main/md/portHopping.md

选择是否启用:

1、启用(默认)
2、跳过

输入序号:
2
您选择跳过端口跳跃/多端口(Port Hopping)功能 
请输入您到此服务器的平均延迟,关系到转发速度(默认200,单位:ms): 

delay:200 ms


期望速度,这是客户端的峰值速度,服务端默认不受限。Tips:脚本会自动*1.10做冗余，您期望过低或者过高会影响转发效率,请如实填写! 
请输入客户端期望的下行速度:(默认50,单位:mbps): 
70
请输入客户端期望的上行速度(默认10,单位:mbps):
20
请输入认证口令: 
fireinrain

配置录入完成!
 
执行配置... 
SIGN...
 
Generating RSA private key, 2048 bit long modulus (2 primes)
....................................................................................................................................................................................+++++
......+++++
e is 65537 (0x010001)
Generating a RSA private key
....................+++++
....+++++
writing new private key to '/etc/hihy/cert/hysteria.131433.xyz.key'
-----
Signature ok
subject=C = CN, ST = GuangDong, L = ShenZhen, O = PonyMa, OU = Tecent, emailAddress = admin@qq.com, CN = Tencent Root CA
Getting CA Private Key
SUCCESS.
 

Test config...

未知错误:请手动运行:/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server  
查看错误日志,反馈到issue! 
Reinstall Complete!

**Comment by fireinrain** [comment]
发现依然appS的大小为0

**Comment by fireinrain** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/14249262/202857380-36e3fdfa-f277-471f-b6f2-c22254792e04.png">

**Comment by fireinrain** [comment]
> <img alt="image" width="738" src="https://user-images.githubusercontent.com/14249262/202857380-36e3fdfa-f277-471f-b6f2-c22254792e04.png">

如果我手动去下载hysteria的编译包 然后重命名为appS 放在bin目录下  是能够运行的

**Comment by emptysuns** [comment]
您有其他服务器吗，能换一个试试吗，我也无法定位这个问题出在哪儿了，好奇怪

**Comment by fireinrain** [comment]
> 您有其他服务器吗，能换一个试试吗，我也无法定位这个问题出在哪儿了，好奇怪

我用其他服务器试一试看看 我也觉得好奇怪

**Comment by fireinrain** [comment]
> 您有其他服务器吗，能换一个试试吗，我也无法定位这个问题出在哪儿了，好奇怪

问题vps debian11
<img width="641" alt="image" src="https://user-images.githubusercontent.com/14249262/202858414-a8e6d891-e1cf-461f-9854-aa1a5aadf3d1.png">

另一台vps: centos7
<img width="744" alt="image" src="https://user-images.githubusercontent.com/14249262/202858454-8309b457-09aa-4dc8-b8d0-9234b6581556.png">

**Comment by fireinrain** [comment]
> > 您有其他服务器吗，能换一个试试吗，我也无法定位这个问题出在哪儿了，好奇怪
> 
> 问题vps debian11 <img alt="image" width="641" src="https://user-images.githubusercontent.com/14249262/202858414-a8e6d891-e1cf-461f-9854-aa1a5aadf3d1.png">
> 
> 另一台vps: centos7 <img alt="image" width="744" src="https://user-images.githubusercontent.com/14249262/202858454-8309b457-09aa-4dc8-b8d0-9234b6581556.png">

已经发现问题了  这台vps curl https://api.github.com/repos/apernet/hysteria/releases/latest  竟然是没有响应的状态。。。
另外一台是有响应

**Comment by fireinrain** [comment]
vps的网络环境问题  打扰up了，我关了这个issue

**Comment by emptysuns** [comment]
算是个小bug吧，没有考虑到获取不到版本信息的问题
