### ISSUE TITLE
安装好后无法使用

### ISSUE THREAD

**Issue by Dicksoi** [emptysuns/Hi_Hysteria#164]
以前安装脚本后可以上网现在不能了 不知道什么情况 作者有电报群吗 我采用不带域名的脚本可以上网 乌龟壳 jp以前部署的都可以用 就最近10天的不行 原来部署的升级内核什么的都没有问题

**Comment by emptysuns** [comment]
服务端客户端是不是都尽可能更新到最新版呢？

因为hysteria更新过程中，有时候新版本的配置无法向下兼容

**Comment by Dicksoi** [comment]
最新部署都是最新的呀!大佬你的脚本提示没有更新了呀! 我试过了用域名的都不能用 只有ip的可以用不知道什么情况

**Comment by emptysuns** [comment]
> 最新部署都是最新的呀!大佬你的脚本提示没有更新了呀! 我试过了用域名的都不能用 只有ip的可以用不知道什么情况

证书没申请成功？

**Comment by Dicksoi** [comment]
申请成功了
 我换了好几个客户端都是最新版的核心还是不能用  用IP 的就可以用

**Comment by Dicksoi** [comment]
域名证书在网站上都可以用 x-ui也是可以的就是大佬的新版本不能用 以前的老版本直接升级没有重装的就可以用 郁闷死了

**Comment by emptysuns** [comment]
server和client log贴上看看

**Comment by Dicksoi** [comment]
谢谢大佬问题已经搞定了！域名在cf上开了小云朵 可能卡的原因关掉后就好了
