### ISSUE TITLE
生成的配置文件没有server端口

### ISSUE THREAD

**Issue by Satan023** [emptysuns/Hi_Hysteria#166]
服务端hi_hysteria版本：0.4.3.c
服务端hysteria core版本：v1.3.0
发现一个问题，使用脚本配置完毕之后显示的server配置缺少端口号，包括root\config.json里也是。

{
"server": "XXX.173.155.156:",
"protocol": "wechat-video",
"up_mbps": 11,
"down_mbps": 55,

config.json里添加配置过程中指定的server端口就能用了。是bug还是啥？
对了，server端我是0.3.x的版本升级到0.4.3.c的。

**Comment by emptysuns** [comment]
直接用选项12完全重置，重新来一遍试试
这个端口号是你输入或者random取的

**Comment by Satan023** [comment]
> 直接用选项12完全重置，重新来一遍试试 这个端口号是你输入或者random取的

试了下不行，配置中冒号后面是空白的，还是得手动加端口
"server": "107.173.155.156:",

**Comment by emptysuns** [comment]
感谢提醒bug，这个错误是由0.4.3兼容portHopping时引入的
推送了0.4.3.d已修复: https://github.com/emptysuns/Hi_Hysteria/commit/0b9f0d6afe6ca4054f68499851c312c638a53c9f
请更新

**Comment by Satan023** [comment]
老哥牛逼！：）
