### ISSUE TITLE
端口跳跃bug吗？

### ISSUE THREAD

**Issue by yqk100** [emptysuns/Hi_Hysteria#167]
Hysteria在服务端启用了动态端口，在vps未重启前能正常使用；
vps一重启，所有客户端都没法连接上了。。。
几台jj都试过了，相同问题！
客户端使用的是Matsuri和NekoRay

**Comment by emptysuns** [comment]
重新配置一下吧，应该是iptables规则没有保存，重启失效，下个版本会修复

**Comment by a9k1n9** [comment]
自己解决了；安装iptables-persistent或者完全删除iptables～

**Comment by emptysuns** [comment]
该bug已经被0.4.4修复，但是仍在测试中https://github.com/emptysuns/Hi_Hysteria/commit/c9133ddf2a51232a2b5e42eae5b332a7b8381185
