### ISSUE TITLE
对ipv6的支援存在问题

### ISSUE THREAD

**Issue by fengguowudi** [emptysuns/Hi_Hysteria#17]
这是系统生成的配置：
{
"server": "[2a01:4f8:242:4986:face:face:c73:1]:16159",
"protocol": "wechat-video",
"up_mbps": 12,
"down_mbps": 62,
"http": {
"listen": "127.0.0.1:8888",
"timeout" : 300,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:8889",
"timeout": 300,
"disable_udp": false,
"user": "pekora",
"password": "pekopeko"
},
"alpn": "h3",
"acl": "acl/routes.acl",
"mmdb": "acl/Country.mmdb",
"auth_str": "fengguo",
"server_name": "wechat.com",
"insecure": true,
"recv_window_conn": 12320768,
"recv_window": 49283072,
"disable_mtu_discovery": false,
"resolver": "119.29.29.29:53",
"retry": 5,
"retry_interval": 3
}

**Comment by fengguowudi** [comment]
这是实际的ip：
2a01:4f8:242:4986:face:face:0c73:0001

**Comment by fengguowudi** [comment]
可以观察到后面的0都被省略，导致连接不上

**Comment by emptysuns** [comment]
`::`在ipv6标准写法里，只能出现一次，但是可以代替多个0的...
连不上不应该考虑其他因素吗？

**Comment by fengguowudi** [comment]
这个也没:: 啊
2a01:4f8:242:4986:face:face:c73:1
