### ISSUE TITLE
The program will be terminated after watching telegram live, is there something wrong with the config setting?

### ISSUE THREAD

**Issue by landancloud** [emptysuns/Hi_Hysteria#171]
Nov 25 20:59:52 debian appS[847]: panic: runtime error: index out of range [0] with length 0
Nov 25 20:59:52 debian appS[847]: goroutine 43 [running]:
Nov 25 20:59:52 debian appS[847]: github.com/HyNetwork/hysteria/pkg/core.(*defragger).Feed(0xc0002bc6d8, {0x80000, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x24, 0x4, ...})
Nov 25 20:59:52 debian appS[847]:         github.com/HyNetwork/hysteria/pkg/core/frag.go:50 +0x2ae
Nov 25 20:59:52 debian appS[847]: github.com/HyNetwork/hysteria/pkg/core.(*serverClient).handleMessage(0xc0002bc620, {0xc00060ca80, 0x32, 0x32})
Nov 25 20:59:52 debian appS[847]:         github.com/HyNetwork/hysteria/pkg/core/server_client.go:134 +0x112
Nov 25 20:59:52 debian appS[847]: github.com/HyNetwork/hysteria/pkg/core.(*serverClient).Run.func1()
Nov 25 20:59:52 debian appS[847]:         github.com/HyNetwork/hysteria/pkg/core/server_client.go:83 +0x32
Nov 25 20:59:52 debian appS[847]: created by github.com/HyNetwork/hysteria/pkg/core.(*serverClient).Run
Nov 25 20:59:52 debian appS[847]:         github.com/HyNetwork/hysteria/pkg/core/server_client.go:77 +0x65
Nov 25 20:59:52 debian systemd[1]: hihy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 25 20:59:52 debian systemd[1]: hihy.service: Failed with result 'exit-code'.

**Comment by emptysuns** [comment]
It looks like a hysteria bug, not a config setting issue.
Using `/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server`, not the systemd log.
