### ISSUE TITLE
如何运行多个hysteria实例

### ISSUE THREAD

**Issue by reov** [emptysuns/Hi_Hysteria#172]
因为现在有3种协议，faketcp在本地实验中运行稳定，但是只允许在Linux和安卓root之后才能使用，我其他的安卓和win客户端无法使用，新版本增加UDP端口跳跃，想运行两种协议的hysteria互为备份，不知道脑洞是否合理。

**Comment by emptysuns** [comment]
这样我推荐你，用手搓个配置，挂个后台就行，暂时没有计划
