### ISSUE TITLE
求作者emptysuns联系方式，以及可能的合作

### ISSUE THREAD

**Issue by moranno** [emptysuns/Hi_Hysteria#173]
求作者emptysuns联系方式，一方面是想支持下好项目，另一方面是探寻可能的商业合作机会。我tg: @missmoranno

**Comment by emptysuns** [comment]
目前不接商业，如果要支持好项目，请捐赠一下hysteria开发者https://hysteria.network/docs/donations/
我只是写了个shell脚本方便使用，真正的贡献者是这些开发者，如果你向它们捐赠了，我也对你道谢
