### ISSUE TITLE
v2N启动报错

### ISSUE THREAD

**Issue by 5536086** [emptysuns/Hi_Hysteria#174]
启动服务(2022/11/27 22:25:56)...
2022-11-27T22:25:56+08:00[31m [FATA] [file:./config.json] [error:invalid character '"' after object key:value pair] [0mFailed to parse client

**Comment by emptysuns** [comment]
麻烦您贴上客户端的配置文件

**Comment by 5536086** [comment]
好像是geo文件丢失了，搞定了，但是好像现在三个协议都被某些运营商屏蔽了，本地电信和联通，都无法正确联网
v2N错误信息：
`2022-11-28T08:30:11+08:00[31m [ERRO] [error:faketcp is not supported on this platform] [0mFailed to initialize client`
服务端，vir和CloudCone都是这个结果

**Comment by emptysuns** [comment]
> 好像是geo文件丢失了，搞定了，但是好像现在三个协议都被某些运营商屏蔽了，本地电信和联通，都无法正确联网 v2N错误信息： `2022-11-28T08:30:11+08:00�[31m [ERRO] [error:faketcp is not supported on this platform] �[0mFailed to initialize client` 服务端，vir和CloudCone都是这个结果

`faketcp is not supported on this platform`
faketcp不能用在windwos上
