### ISSUE TITLE
更新hihy报错

### ISSUE THREAD

**Issue by mliyuanbiao** [emptysuns/Hi_Hysteria#175]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/16277378/204141315-eb67f365-fc0f-4c87-9a62-546a0bf7463d.png">

这种情况不是一次，基本上每次遇到更新都会碰到错误，虽然有错误，但是已经更新完成了

**Comment by narhalsom** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/117664859/204182179-380dc7e6-8383-4401-a029-fc5b441dc9fa.png">
这次的错误又不一样
