### ISSUE TITLE
域名解析IP有问题

### ISSUE THREAD

**Issue by i5g5vip** [emptysuns/Hi_Hysteria#176]
用Ping脚本很多纯V6的VPS显示IP不对
用nslookup

**Comment by emptysuns** [comment]
刚刚推了0.4.4.f，还是出错吗https://github.com/emptysuns/Hi_Hysteria/commit/7d3eb6ebfe43bdfcedcbad7004eb6d97465a57a3

**Comment by i5g5vip** [comment]
0.4.4.f修复了本地ＩＰ识别问题，域名解析有问题。
有的ＶＰＳ正常，象ＥＵｓｅｒｖ。　ｗｏｉｄｅｎ等ＶＰＳ不行

**Comment by emptysuns** [comment]
感谢反馈，不用nslookup是考虑到由于有些人域名解析了多个ip，处理起来麻烦
请问
```
ping 你的域名 -c 1 | sed '1{s/[^(]*(//;s/).*//;q}'
```
这个返回什么信息？能否提供一下详细的配置过程，方便排错

**Comment by i5g5vip** [comment]
![photo_2022-11-28_02-47-50](https://user-images.githubusercontent.com/58246606/204154096-48ed8f15-34ad-4ac1-9783-089f4fbac2f8.jpg)

**Comment by i5g5vip** [comment]
![photo_2022-11-28_02-53-39](https://user-images.githubusercontent.com/58246606/204154287-96f2bc1d-b9a8-44cb-8c25-f7f33860fe9a.jpg)

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/d845556d6c3d7f7a3db714bf7af471ba055f33e3
