### ISSUE TITLE
一个小建议，能否增加选择obfs验证的选择？stash方便使用

### ISSUE THREAD

**Issue by sw19999** [emptysuns/Hi_Hysteria#178]
iOS这边小火箭用这个没速度，用stash用auth模式base64也连不上，手工改成obfs加密就可以了。

安卓茉莉是正常。

老大酌情考虑吧，不改也没关系，自己手工改

**Comment by emptysuns** [comment]
虽然目前不开obfs没有遭到针对性的封锁，但是为了安全以后会提供对hysteria obfs支持

**Comment by emptysuns** [comment]
已更新, https://github.com/emptysuns/Hi_Hysteria/commit/03aecdfcfa926a086ada2dc82bb18fe5d281569e

**Comment by sw19999** [comment]
感谢老大更新支持obfs加密。另外汇报一下，iOS的Stash的auth模式可以用了，他的教程一直要求做base64，实测为直接明码密匙即可连接，白折腾这么多天
