### ISSUE TITLE
[bug] lsof判断端口占用时，没有区分LISTEN，也没有判断协议类型

### ISSUE THREAD

**Issue by wonleon** [emptysuns/Hi_Hysteria#179]
之前的版本都没有问题，更新到0.4.4.j以后就出问题了

Port: TCP/80 已经被 google_os(instance-1.asia-east2-a.c.norse-period-244803.internal:60634->metadata.google.internal:http) 占用,进程pid为: 397. 
是否自动关闭端口占用?(y/N) 
y
端口占用关闭失败,强制杀死进程后进程重启,请查看是否存在守护进程... 

重新建了主机，DB10/11都试了，都不行。
请问这个要怎么处理呢？谢谢

**Comment by emptysuns** [comment]
你本地80端口被占用了`lsof -i :80`，将所有PID 都kill掉`kill -9 pid号`

**Comment by emptysuns** [comment]
很蠢的bug, `lsof`判断端口占用时，没区分端口占用状态导致状态是`ESTABLISHED`也给算进去了

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/a6da638f43caa2668449d574cc98ed2b52c9df35,已修复
