### ISSUE TITLE
如何每次客户端启动后不要修改IE的代理？

### ISSUE THREAD

**Issue by idragonet** [emptysuns/Hi_Hysteria#18]
每次都要去改回来，麻烦。

**Comment by emptysuns** [comment]
不修改http代理没法直接用做浏览器代理啊！？而且当你回车退出的时候，自动就把代理清除了...

如果不喜欢把脚本里修改注册表的那部分删了就行了

**Comment by idragonet** [comment]
> 不修改http代理没法直接用做浏览器代理啊！？而且当你回车退出的时候，自动就把代理清除了...
> 
> 如果不喜欢把脚本里修改注册表的那部分删了就行了

都是用Proxy SwitchyOmega来管理浏览器代理，根本不需要动系统的代理配置。

脚本里修改注册表的那部分在哪里？

**Comment by emptysuns** [comment]
你如果使用的是那个bat“客户端”，run.bat里把修改注册表的全删掉
