### ISSUE TITLE
syntax error: invalid arithmetic operator (error token is  + 100 / 10")

### ISSUE THREAD

**Issue by gamexy** [emptysuns/Hi_Hysteria#181]
请输入客户端名称备注(默认使用域名/IP区分,例如输入test,则名称为Hys-test): 

配置录入完成!
 
执行配置... 
/dev/fd/63: line 510: 100 + 100 / 10: syntax error: invalid arithmetic operator (error token is  + 100 / 10")

执行到这里就跳出了

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/a6da638f43caa2668449d574cc98ed2b52c9df35/server/install.sh#L510
问题在这里，请问你是用bash执行的吗？
你的系统是什么？

**Comment by gamexy** [comment]
是用bash执行的，系统是Ubuntu 22.04 LTS

**Comment by gamexy** [comment]
重启重装了一遍，这次没出错。不过我这次是默认下载50M，上传10M，上次是选的下载100M，不知道这个会不会影响。

**Comment by emptysuns** [comment]
你上次输入的不是纯数字吧，是不是混入了其他字符？

**Comment by gamexy** [comment]
输入时确实使用了回退键，但我看下面给的确认信息是对的

**Comment by emptysuns** [comment]
> 输入时确实使用了回退键，但我看下面给的确认信息是对的

你在你的系统bash里，如我上面写的执行看看

**Comment by gamexy** [comment]
root@r:~# download=100
root@r:~# download=$(($download + $download / 10))
root@r:~# echo $download
110


好像没问题
