### ISSUE TITLE
bug反馈： "resolver": "https://223.5.5.5/dns-query"导致的客户端启动失败（自有域名证书的情况）

### ISSUE THREAD

**Issue by mebest100** [emptysuns/Hi_Hysteria#184]
问题描述：
我是自有域名，通过脚本安装：选择的是acme签发证书，但是安装完毕、获取客户端配置以后，在启动客户端以后，客户端始终报错：
error:lookup xxx域名 on 114.114.115.115:53: Post "https://223.5.5.5/dns-query": x509: certificate is valid for 223.5.5.5, 223.6.6.6, not 223.5.5.5] Failed to initialize client

然后，我选择手动指定本地已经签发生成的证书（自己通过acme命令行签发的）, 也是同样的报错

最后发现把客户端config.json里面的"resolver": "https://223.5.5.5/dns-query"配置删除就好了。
"resolver": "https://223.5.5.5/dns-query"这个不知道起什么作用，放在这里会导致客户端启动失败，去掉就好了，感觉应该是个bug。
但这个配置在自签证书wechat.com时没有问题，非常奇怪。

另外，我没有看到Hysteria通过acme签发的证书存储在哪里，Hysteria是否真的有签发acme证书，如果有，为什么没有看到证书文件？

**Comment by emptysuns** [comment]
1. 客户端使用`resolver`是为了某些本地运营商dns自带污染的用户，指定使用阿里公共dns的DoH解析`direct`域名，增加安全性。你无法正常使用的问题，我无法判断，需要提供更加详细的运行log
2. 是通过内置ACME模块签发的证书，并没有使用acme.sh，存储位置在`$HOME/.local/share/certmagic/certificates/`
如果你用的hihy则主目录是/root/

**Comment by mebest100** [comment]
我看了hysteria的官方文档：https://hysteria.network/zh/docs/advanced-usage/
里面给出的"resolver"是下面这样的格式
"resolver": "udp://1.1.1.1:53"
![image](https://user-images.githubusercontent.com/11530991/205419223-773431e5-2706-4d17-aa7e-1bbdbd5bd1eb.png)

改成这样的格式，问题就解决了不再报错。

**Comment by emptysuns** [comment]
你无法验证223.5.5.5的ip证书？
你手动浏览器打开https://223.5.5.5/dns-query
看看报错吗

**Comment by mebest100** [comment]
手动打开https://223.5.5.5/dns-query不会报错，返回： no 'dns' query parameter found

**Comment by emptysuns** [comment]
那没办法了，你是个例，我也不知道问题是什么

**Comment by mebest100** [comment]
把resolver换成这个也可以：https://dns.alidns.com/dns-query

**Comment by emptysuns** [comment]
> 把resolver换成这个也可以：https://dns.alidns.com/dns-query

直接使用域名会有个问题，当你无法解析这个DoH域名时，hysteria无法处理这个错误，实际上0.4.3版本就是这样用的，然后很多人反馈出错

**Comment by TuShan-Jing-XiaoHao** [comment]
我也有遇到类似的问题，服务端的resolver我填的是udp://1.1.1.1:53，服务器resolver.conf填的是1.1.1.1，客户端resolver填的是https://223.5.5.5/dns-query时，客户端报错是“无法在8.8.8.8:443上找到主机地址”，客户端resolver填写udp://1.1.1.1:53时，报错是“在223.5.5.5:443搜索主机dns超时”。我不太理解为什么会出现不相关的dns服务器。

**Comment by TuShan-Jing-XiaoHao** [comment]
> 我也有遇到类似的问题，服务端的resolver我填的是udp://1.1.1.1:53，服务器resolver.conf填的是1.1.1.1，客户端resolver填的是[https://223.5.5.5/dns-query时，客户端报错是“无法在8.8.8.8:443上找到主机地址”，客户端resolver填写udp://1.1.1.1:53时，报错是“在223.5.5.5:443搜索主机dns超时”。我不太理解为什么会出现不相关的dns服务器。](https://223.5.5.5/dns-query%E6%97%B6%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E6%97%A0%E6%B3%95%E5%9C%A88.8.8.8:443%E4%B8%8A%E6%89%BE%E5%88%B0%E4%B8%BB%E6%9C%BA%E5%9C%B0%E5%9D%80%E2%80%9D%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AFresolver%E5%A1%AB%E5%86%99udp://1.1.1.1:53%E6%97%B6%EF%BC%8C%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E5%9C%A8223.5.5.5:443%E6%90%9C%E7%B4%A2%E4%B8%BB%E6%9C%BAdns%E8%B6%85%E6%97%B6%E2%80%9D%E3%80%82%E6%88%91%E4%B8%8D%E5%A4%AA%E7%90%86%E8%A7%A3%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%B8%8D%E7%9B%B8%E5%85%B3%E7%9A%84dns%E6%9C%8D%E5%8A%A1%E5%99%A8%E3%80%82)

现在我换成了“https://dns.alidns.com/dns-query”，就没有任何问题了。

**Comment by TuShan-Jing-XiaoHao** [comment]
> > 我也有遇到类似的问题，服务端的resolver我填的是udp://1.1.1.1:53，服务器resolver.conf填的是1.1.1.1，客户端resolver填的是[https://223.5.5.5/dns-query时，客户端报错是“无法在8.8.8.8:443上找到主机地址”，客户端resolver填写udp://1.1.1.1:53时，报错是“在223.5.5.5:443搜索主机dns超时”。我不太理解为什么会出现不相关的dns服务器。](https://223.5.5.5/dns-query%E6%97%B6%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E6%97%A0%E6%B3%95%E5%9C%A88.8.8.8:443%E4%B8%8A%E6%89%BE%E5%88%B0%E4%B8%BB%E6%9C%BA%E5%9C%B0%E5%9D%80%E2%80%9D%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AFresolver%E5%A1%AB%E5%86%99udp://1.1.1.1:53%E6%97%B6%EF%BC%8C%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E5%9C%A8223.5.5.5:443%E6%90%9C%E7%B4%A2%E4%B8%BB%E6%9C%BAdns%E8%B6%85%E6%97%B6%E2%80%9D%E3%80%82%E6%88%91%E4%B8%8D%E5%A4%AA%E7%90%86%E8%A7%A3%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%B8%8D%E7%9B%B8%E5%85%B3%E7%9A%84dns%E6%9C%8D%E5%8A%A1%E5%99%A8%E3%80%82)
> 
> 现在我换成了“[https://dns.alidns.com/dns-query”，就没有任何问题了。](https://dns.alidns.com/dns-query%E2%80%9D%EF%BC%8C%E5%B0%B1%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98%E4%BA%86%E3%80%82)

好吧，这样处理还是有点问题。
我思考了一下，可能是因为alidns上没有解析到我的域名，就会向cloudflare的1.1.1.1或者谷歌的8.8.8.8发送请求，这样是否连接得到就是概率问题(?)，毕竟我的域名是放在cloudflare上解析dns的，谷歌的8.8.8.8解析不了(虽然按理来说不应该啊)。考虑到我的服务器只有ipv4没有ipv6，域名是放在cloudflare上解析的，所以我在配置文件里添加了"resolve_preference": "46"，优先使用ipv4，然后将dns的解析换成了官方文档里的”udp://1.1.1.1:53"。
这样貌似解决了问题，我测试了客户端重启十余次，均能秒连。
好吧，我服了，在我刚写完这篇回答时，我又重新试了连接，这次它又显示是"在223.5.5.5上搜索超时"，感觉像是客户端的问题。
当我写完上面那句话后，我又试了下重新连接，好了，能连接上了。我觉得连不上应该是运气问题或者客户端问题或者线路问题。
:(

**Comment by emptysuns** [comment]
> > > 我也有遇到类似的问题，服务端的resolver我填的是udp://1.1.1.1:53，服务器resolver.conf填的是1.1.1.1，客户端resolver填的是[https://223.5.5.5/dns-query时，客户端报错是“无法在8.8.8.8:443上找到主机地址”，客户端resolver填写udp://1.1.1.1:53时，报错是“在223.5.5.5:443搜索主机dns超时”。我不太理解为什么会出现不相关的dns服务器。](https://223.5.5.5/dns-query%E6%97%B6%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E6%97%A0%E6%B3%95%E5%9C%A88.8.8.8:443%E4%B8%8A%E6%89%BE%E5%88%B0%E4%B8%BB%E6%9C%BA%E5%9C%B0%E5%9D%80%E2%80%9D%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AFresolver%E5%A1%AB%E5%86%99udp://1.1.1.1:53%E6%97%B6%EF%BC%8C%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E5%9C%A8223.5.5.5:443%E6%90%9C%E7%B4%A2%E4%B8%BB%E6%9C%BAdns%E8%B6%85%E6%97%B6%E2%80%9D%E3%80%82%E6%88%91%E4%B8%8D%E5%A4%AA%E7%90%86%E8%A7%A3%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%B8%8D%E7%9B%B8%E5%85%B3%E7%9A%84dns%E6%9C%8D%E5%8A%A1%E5%99%A8%E3%80%82)
> > 
> > 
> > 现在我换成了“[https://dns.alidns.com/dns-query”，就没有任何问题了。](https://dns.alidns.com/dns-query%E2%80%9D%EF%BC%8C%E5%B0%B1%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98%E4%BA%86%E3%80%82)
> 
> 好吧，这样处理还是有点问题。 我思考了一下，可能是因为alidns上没有解析到我的域名，就会向cloudflare的1.1.1.1或者谷歌的8.8.8.8发送请求，这样是否连接得到就是概率问题(?)，毕竟我的域名是放在cloudflare上解析dns的，谷歌的8.8.8.8解析不了(虽然按理来说不应该啊)。考虑到我的服务器只有ipv4没有ipv6，域名是放在cloudflare上解析的，所以我在配置文件里添加了"resolve_preference": "46"，优先使用ipv4，然后将dns的解析换成了官方文档里的”udp://1.1.1.1:53"。 这样貌似解决了问题，我测试了客户端重启十余次，均能秒连。 好吧，我服了，在我刚写完这篇回答时，我又重新试了连接，这次它又显示是"在223.5.5.5上搜索超时"，感觉像是客户端的问题。 当我写完上面那句话后，我又试了下重新连接，好了，能连接上了。我觉得连不上应该是运气问题或者客户端问题或者线路问题。 :(

抱歉，我没办法重现这个问题，也没碰到过，提供不了什么帮助

**Comment by TuShan-Jing-XiaoHao** [comment]
> > > > 我也有遇到类似的问题，服务端的resolver我填的是udp://1.1.1.1:53，服务器resolver.conf填的是1.1.1.1，客户端resolver填的是[https://223.5.5.5/dns-query时，客户端报错是“无法在8.8.8.8:443上找到主机地址”，客户端resolver填写udp://1.1.1.1:53时，报错是“在223.5.5.5:443搜索主机dns超时”。我不太理解为什么会出现不相关的dns服务器。](https://223.5.5.5/dns-query%E6%97%B6%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E6%97%A0%E6%B3%95%E5%9C%A88.8.8.8:443%E4%B8%8A%E6%89%BE%E5%88%B0%E4%B8%BB%E6%9C%BA%E5%9C%B0%E5%9D%80%E2%80%9D%EF%BC%8C%E5%AE%A2%E6%88%B7%E7%AB%AFresolver%E5%A1%AB%E5%86%99udp://1.1.1.1:53%E6%97%B6%EF%BC%8C%E6%8A%A5%E9%94%99%E6%98%AF%E2%80%9C%E5%9C%A8223.5.5.5:443%E6%90%9C%E7%B4%A2%E4%B8%BB%E6%9C%BAdns%E8%B6%85%E6%97%B6%E2%80%9D%E3%80%82%E6%88%91%E4%B8%8D%E5%A4%AA%E7%90%86%E8%A7%A3%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%B8%8D%E7%9B%B8%E5%85%B3%E7%9A%84dns%E6%9C%8D%E5%8A%A1%E5%99%A8%E3%80%82)
> > > 
> > > 
> > > 现在我换成了“[https://dns.alidns.com/dns-query”，就没有任何问题了。](https://dns.alidns.com/dns-query%E2%80%9D%EF%BC%8C%E5%B0%B1%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98%E4%BA%86%E3%80%82)
> > 
> > 
> > 好吧，这样处理还是有点问题。 我思考了一下，可能是因为alidns上没有解析到我的域名，就会向cloudflare的1.1.1.1或者谷歌的8.8.8.8发送请求，这样是否连接得到就是概率问题(?)，毕竟我的域名是放在cloudflare上解析dns的，谷歌的8.8.8.8解析不了(虽然按理来说不应该啊)。考虑到我的服务器只有ipv4没有ipv6，域名是放在cloudflare上解析的，所以我在配置文件里添加了"resolve_preference": "46"，优先使用ipv4，然后将dns的解析换成了官方文档里的”udp://1.1.1.1:53"。 这样貌似解决了问题，我测试了客户端重启十余次，均能秒连。 好吧，我服了，在我刚写完这篇回答时，我又重新试了连接，这次它又显示是"在223.5.5.5上搜索超时"，感觉像是客户端的问题。 当我写完上面那句话后，我又试了下重新连接，好了，能连接上了。我觉得连不上应该是运气问题或者客户端问题或者线路问题。 :(
> 
> 抱歉，我没办法重现这个问题，也没碰到过，提供不了什么帮助

我想明白了，既然是dns解析的问题，那我直接把主机地址从域名换成实际ip就好了，绕过dns服务器直接连接。我吃早饭的前后都能秒连，感觉没什么问题了吧（大概）
