### ISSUE TITLE
Matsuri安卓客户端正常，但是passwall节点测试不通过

### ISSUE THREAD

**Issue by wangnimahahaha** [emptysuns/Hi_Hysteria#186]
![image](https://user-images.githubusercontent.com/119702801/205377025-f5f57e83-2ac9-4ae0-9e02-4dbe1bad9862.png)
同样的设置 安卓客户端可以  passwall就是不行

**Comment by emptysuns** [comment]
抱歉的是，我只能保证生成的配置是可以用的，这明显是你passwall或者openwrt配置有问题，请移步对应的地方去提issue

**Comment by sw19999** [comment]
混淆密码那行清空就可以了。显示ping不通，实际上已经可以联网了
