### ISSUE TITLE
使用脚本安装的时候输入的端口号和最后生成的配置文件的端口不一致

### ISSUE THREAD

**Issue by Dennis2022d** [emptysuns/Hi_Hysteria#187]
我在脚本安装的时候输入的端口号是25361，但实际生成的json文件中的端口号是错的
![image](https://user-images.githubusercontent.com/119730553/205433939-016ea4d0-33c0-49e7-ba5d-285cf22aaa43.png)

![image](https://user-images.githubusercontent.com/119730553/205433995-3ca89251-9e92-452f-bea4-2f621a4a2f2f.png)

**Comment by emptysuns** [comment]
已修复: https://github.com/emptysuns/Hi_Hysteria/commit/e083a36a4cfdf98b4726f4a25348182958618a45
