### ISSUE TITLE
socks5默认建议不要有账号密码

### ISSUE THREAD

**Issue by KagurasakaAkuryou** [emptysuns/Hi_Hysteria#19]
我服务端器生成的conf的socks5居然配置了认证账号和密码，虽然我很快发现了这个问题，但是对许多人来说很可能会摸不着头脑。

**Comment by emptysuns** [comment]
我觉得`config.json`是明文的，而且在执行的最后输出结果时上面也有文字提示socks5带密码。

不可否认带密码是多此一举的，考虑下个版本去掉，感谢建议～

**Comment by emptysuns** [comment]
[0.3.0](https://github.com/emptysuns/Hi_Hysteria/commit/ada9ec84c0b19d1f49c1f151af5e3f4b8a618942)
