### ISSUE TITLE
error opening database: invalid MaxMind DB file

### ISSUE THREAD

**Issue by Gnit-V** [emptysuns/Hi_Hysteria#191]
使用V2rayN,加载ACL时候出错
![error](https://user-images.githubusercontent.com/71635412/205807703-3bdd9996-db5c-4161-bf9c-ae288f9c8597.png)

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/main/acl/Country.mmdb

**Comment by Gnit-V** [comment]
解决了,感谢!!
