### ISSUE TITLE
再次出现itialize client，重新配置后恢复

### ISSUE THREAD

**Issue by dadaomei** [emptysuns/Hi_Hysteria#193]
昨晚每隔2小时就断流后重置，今天重启服务器再打开的时候，客户端又连不上，显示itialize client，重置后恢复。不知道是不是运营商的问题。
浙江杭州，移动

**Comment by emptysuns** [comment]
1. 是否自签证书?
2. 使用的什么协议？
3. 如果使用了udp，是否使用了端口跳跃？

**Comment by dadaomei** [comment]
使用ACME申请
udp
使用端口跳跃

**Comment by emptysuns** [comment]
移不动是这样的，因为运营商对udp限制**不同地区不同运营商各不不同**，很难有个统一标准
而且GFW对不同IDC机房的力度也不一样，是黑盒测试，只能慢慢摸索了
如果条件允许的话尝试一下faketcp或者换个其他冷门IDC机房的服务器尝试一下，期待您的反馈
