### ISSUE TITLE
【新功能】增加 `prometheus_listen` 的初始化配置

### ISSUE THREAD

**Issue by AnoyiX** [emptysuns/Hi_Hysteria#196]
详见 [https://hysteria.network/zh/docs/advanced-usage/](https://hysteria.network/zh/docs/advanced-usage/) 配置中的 `prometheus_listen` 参数

**Comment by emptysuns** [comment]
我个人认为增加流量统计功能，这是没必要的

**Comment by AnoyiX** [comment]
对于多用户来说，除了连接的必要配置，认证、流量统计都是非常重要的功能

**Comment by emptysuns** [comment]
这些需求可以根据个人喜好手动着来加吧，因为多用户说着简单，现有的基础上实现着麻烦:
1. hy的流量统计需要另外打开一个web端口没有任何鉴权，需要配置防火墙来避免主动探测
2. hihy目前的策略是一周重启两次，为了防止长期运行时内存占用高，此时统计的流量会失效
3. 多用户配置会对本来就很繁琐的配置过程再多一点

这些都是我认为多用户不该有的理由，可以手搓配置简单的实现，这并不是一个shell脚本该完成的功能

**Comment by AnoyiX** [comment]
好吧，我自己手动改吧
