### ISSUE TITLE
能不能增加命令直达功能呢？

### ISSUE THREAD

**Issue by lukemin** [emptysuns/Hi_Hysteria#197]
现在是ssh键入hihy，才能出现下面的选项？
1)  安装 hysteria 
2)  卸载 
..................... 
3)  启动 
4)  暂停 
5)  重新启动 
6)  运行状态 
..................... 
7)  更新Core 
8)  查看当前配置 
9)  重新配置 
10) 切换ipv4/ipv6优先级 
11) 更新hihy 
12) 完全重置所有配置 
13) 修改当前协议类型 
14) 查看实时日志
能不能增加这样一个功能，如hihy 7 直接完成更新Core的命令？

**Comment by leohougmail** [comment]
同意，因为证书会自动更新，目前没有办法通过命令行执行hihy 的重启，类似hihy reload之类的

**Comment by emptysuns** [comment]
> 同意，因为证书会自动更新，目前没有办法通过命令行执行hihy 的重启，类似hihy reload之类的

如果你只需要更新证书，那么不用重启hysteria，它会自动重新签发证书

其实现在有直达的命令: `hihy restart`

下次更新会优化这部分功能，感谢建议

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/30d724e855b0b72b7654effce6406aae273627a3
