### ISSUE TITLE
反馈一个小bug  多端口跳跃重启之后没了

### ISSUE THREAD

**Issue by sw19999** [emptysuns/Hi_Hysteria#199]
Ubuntu和Debian两台vps都这样，重启之后看 iptables -t nat -L PREROUTING 空的

用12重新配置，依旧如此，不知道是不是我的问题

**Comment by emptysuns** [comment]
防火墙规则没有保存
请问hihy是`0.4.5`吗？

**Comment by sw19999** [comment]
> 防火墙规则没有保存
> 请问hihy是`0.4.5`吗？

没错，已经试过0.45，用12功能全清，重新安装一样

**Comment by emptysuns** [comment]
```
netfilter-persistent save
```
看看返回什么,debian系的系统用netfilter-persistent做的iptables持久化

**Comment by sw19999** [comment]
> ```
> netfilter-persistent save
> ```
> 
> 
>      
>   
> 
> 看看返回什么,debian系的系统用netfilter-persistent做的iptables持久化

这个命令没任何提示，也没有报错，重启之后端口那行没有了，刚才偷懒，在rc.local 加一行命令，重启之后自己添加端口映射算了

**Comment by emptysuns** [comment]
没有任何返回说明保存了，不知道为什么没有生效

**Comment by emptysuns** [comment]
已修复, [0.4.5.a](https://github.com/emptysuns/Hi_Hysteria/commit/b933bddb2e6e97818c30e64961977da06c61411a)
bug出现详情[参照](https://github.com/Bpazy/blog/issues/199)
