### ISSUE TITLE
甲骨文VPS可以用吗，可以和其他XRAY脚本共存吗？

### ISSUE THREAD

**Issue by eightsheep67** [emptysuns/Hi_Hysteria#20]
现在甲骨文VPS已经安装了其他的XRAY XTLS一键脚本，可以直接安装这个Hysteria脚本共存吗？

**Comment by emptysuns** [comment]
x86和arm都可以，只要不和xray的端口冲突都行。

**Comment by yang12me** [comment]
可以共存，并且可以用安装XRAY是申请的证书

**Comment by yang12me** [comment]
可以共存，并且可以用安装XRAY时申请的证书
