### ISSUE TITLE
一个需要重启路由器的报错

### ISSUE THREAD

**Issue by dadaomei** [emptysuns/Hi_Hysteria#201]
运营商：移不动

使用ACME申请
udp
使用端口跳跃

客户端提示
 [addr:域名省略:39741,37389-39000] [error:timeout: no recent network activity] [0mConnection to server lost, reconnecting...

（个人推出内网对外被屏蔽）

配置如下
{
"server": "域名略去:39741,37389-39000",
"protocol": "udp",
"up_mbps": 11,
"down_mbps": 55,
"http": {
"listen": "127.0.0.1:10809",
"timeout" : 300,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:10808",
"timeout": 300,
"disable_udp": false
},
"obfs": "（此处略去）",
"alpn": "h3",

"auth_str": "",
"server_name": "域名略去",
"insecure": false,
"recv_window_conn": 5767168,
"recv_window": 23068672,
"disable_mtu_discovery": true,
"resolver": "https://223.5.5.5/dns-query",
"retry": 3,
"retry_interval": 3,
"quit_on_disconnect": false,
"handshake_timeout": 15,
"idle_timeout": 30,
"fast_open": true,
"hop_interval": 120
}

**Comment by emptysuns** [comment]
```
no recent network activity
```
如果正常使用过程中突然断开，出现这个日志，很可能是碰到本地运营商的udp QoS墙了

一般来说对于国内用户，移动的限制比联通和电信要更严格
这个策略是由你本地运营商规定的，所以没有一个标准，“因地制宜”

建议下面两点：
1. 查看配置发现，你使用了obfs，虽然会增加安全性，但是会混淆流量成未知udp，毕竟未知udp往往代表着对外攻击，这更加容易碰到udp QoS，建议换成另外两种已知，能被识别的协议
2. 尝试使用faketcp模式，这能解决大部分无法连接问题

**Comment by dadaomei** [comment]
> ```
> no recent network activity
> ```
> 
> 如果正常使用过程中突然断开，出现这个日志，很可能是碰到本地运营商的udp QoS墙了
> 
> 一般来说对于国内用户，移动的限制比联通和电信要更严格 这个策略是由你本地运营商规定的，所以没有一个标准，“因地制宜”
> 
> 建议下面两点：
> 
> 1. 查看配置发现，你使用了obfs，虽然会增加安全性，但是会混淆流量成未知udp，毕竟未知udp往往代表着对外攻击，这更加容易碰到udp QoS，建议换成另外两种已知，能被识别的协议
> 2. 尝试使用faketcp模式，这能解决大部分无法连接问题

2023年1月7日晚
现在不管是使用ACME申请和自签都被针对，不使用obfs会根本连不上，重启路由器，过几分钟又不用

**Comment by emptysuns** [comment]
能否提供你的服务器提供商是谁？

**Comment by dadaomei** [comment]
vultr
另外，现在我使用的是自签，ACME申请断的更快

**Comment by emptysuns** [comment]
> vultr 另外，现在我使用的是自签，ACME申请断的更快

参考这个
https://github.com/emptysuns/Hi_Hysteria/blob/main/md/blacklist.md
可以换一个服务器商家试试看看能不能连上，找一些冷门小众的，一般这些商家不会主动去限制UDP

**Comment by dadaomei** [comment]
最近2天网络响应越来越慢，之前看教程说用了obfs会加重服务器负担，重启会不会恢复
另外，每次更新端口，一般可以稳定使用一周，配置还和这个提问中说的配置一样
