### ISSUE TITLE
手机内置谷歌服务无法登录

### ISSUE THREAD

**Issue by Aexus** [emptysuns/Hi_Hysteria#202]
手机浏览器可以正常访问谷歌服务,但内置的谷歌账户无法登录

**Comment by emptysuns** [comment]
啥软件？如果是clash.meta请更新配置，这个问题已经解决了

**Comment by Aexus** [comment]
[shellclash](https://github.com/juewuy/ShellClash),使用的是clash.meta内核.订阅的机场没问题,使用自己海外服务器部署hysteria转换后出现这种情况😂

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/90#issuecomment-1219015890
