### ISSUE TITLE
导出链接无法使用

### ISSUE THREAD

**Issue by Fangliding** [emptysuns/Hi_Hysteria#205]
本人使用脚本一路回车最后复制黏贴进SN发现无法启动 经群友提醒是配置错误 但是我寻思 脚本还能有配置错误呢
无意中换一个ssh软件登录服务器 然后发现密码中还包含�字符 我之前用的termius似乎忽略了这些未知字符 我一看不对 就手动设置了密码 问题解决
没时间研究这玩意具体是啥 建议把password生成器修改为只输出数字和字母 或者直接偷懒 cat /proc/sys/kernel/random/uuid 弄个uuid来应该也不是不行

**Comment by chika0801** [comment]
233333

**Comment by emptysuns** [comment]
密码本就是从英文和数字里选的，不知道为什么会出现乱码，我也复现了，应该是系统镜像问题，因为水平有限原因不知，下版本看看怎么修复

**Comment by emptysuns** [comment]
原来是用`tr -cd '[:alnum:]' < /dev/urandom | fold -w50 | head -n1`取的密码
根据[gnu.org](https://www.gnu.org/software/grep/manual/html_node/Character-Classes-and-Bracket-Expressions.html#index-alnum-character-class)的解释:
>‘[:alnum:]’
Alphanumeric characters: ‘[:alpha:]’ and ‘[:digit:]’; in the ‘C’ locale and ASCII character encoding, this is the same as ‘[0-9A-Za-z]’.

相当于取的ASCII和数字混合，但是少部分用户用的系统取了一部分乱码文字，我目前不知道为什么会出现这种问题，希望了解的人可以回答我的疑问

更换表达式`[:alnum:]`换成`0-9A-Za-z`,正常了

```
root@ubuntu:~# tr -cd '[:alnum:]' < /dev/urandom | fold -w50 | head -n1
IC�tR��Sej���O��O�8�yF0ɵ81������La8�OZ�5�4�c����h
root@ubuntu:~# tr -cd '0-9A-Za-z' < /dev/urandom | fold -w50 | head -n1
yatwdVZhsCuppZpJ9V6jPEVZtAYqMMrj2dkGaNjSvJ4mTtOa0J
```

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/30d724e855b0b72b7654effce6406aae273627a3
