### ISSUE TITLE
Hysteria是否不支持ipv6连接？

### ISSUE THREAD

**Issue by XboxSoldier** [emptysuns/Hi_Hysteria#206]
服务端：全部默认配置
客户端：Clash for Windows + Meta核心，开启DNS，fake-ip模式，开启ipv6
域名解析到服务器ipv6地址，无法正常连接，Log内容：
[UDP] dial GLOBAL to mobile.events.data.microsoft.com:443 error: INTERNAL_ERROR: write udp 192.168.0.106:64775->[（服务器ipv6地址）]:40159: address （服务器ipv6地址）: non-IPv4 address
因为校园网计费机制，存在使用ipv6连接服务器的需要。请问这是因为Hysteria不支持ipv6连接，还是因为需要在服务端或客户端进行某些配置？希望能够得到解答，谢谢！

**Comment by emptysuns** [comment]
您好支持的，无需额外配置就能用，单看这一个log不知道有什么问题，能否贴出完整的server和client配置？

以及完整的clash或者hysteria日志

**Comment by XboxSoldier** [comment]
昨天配置了两边都不能连接，刚才重新配置了一下，发现可以连接了。
可能是哪里没注意搞错了，不好意思啊。
