### ISSUE TITLE
貌似目前新设备无法执行安装操作

### ISSUE THREAD

**Issue by wanginzh** [emptysuns/Hi_Hysteria#207]
测试日期：2023年1月18日20:20
我在使用此脚本安装hysteria时，出现了一个错误：
[Network error]: Failed to get the latest version of hysteria in Github!
请问是github的问题还是脚本的问题？
系统：centos7.9
[date.txt](https://github.com/emptysuns/Hi_Hysteria/files/10446176/date.txt)

**Comment by eightsheep67** [comment]
同样，但是其他脚本连接github正常呀。。。
