### ISSUE TITLE
关于IOS使用此协议

### ISSUE THREAD

**Issue by Belly0919** [emptysuns/Hi_Hysteria#208]
用脚本搭建好后在META FOR CLASH的各个平台上都能用，唯独把导入链接导入到IOS的小火箭或者把YAML文件放到STACH上都是测试连接超时，无论怎么改都不行，请求指教！

**Comment by emptysuns** [comment]
重要信息打码后，贴上配置

**Comment by sw19999** [comment]
iOS暂时只有美区Stash支持这个协议，小火箭早就试过了，非常卡，根本用不了
