### ISSUE TITLE
想问一下ios端小火箭使用hysteria的问题

### ISSUE THREAD

**Issue by e1lite** [emptysuns/Hi_Hysteria#209]
我使用了该脚本搭建的hysteria协议，电脑端上的v2rayN和手机端的matsuri都能正常使用。但导入到ios端的shadowrocket上时，虽然能正常连接，但非常卡，使用测速时显示几乎没速度，想问一下这是什么问题，怎么解决，谢谢了！

**Comment by emptysuns** [comment]
iOS系统层限制太严格的问题，udp性能发挥不好，我无法提供帮助

你可以尝试联系小火箭作者，但是有人也反映过没得到重视

**Comment by sw19999** [comment]
小火箭用不了这个协议，完全没速度，美区买Stash 就可以用了，修改一下clash的配置文件就可以用

**Comment by e1lite** [comment]
> iOS系统层限制太严格的问题，udp性能发挥不好，我无法提供帮助
> 
> 你可以尝试联系小火箭作者，但是有人也反映过没得到重视

好的明白了，谢谢您！

**Comment by sjk7524068** [comment]
> 是不是用小火箭的话就不建议udp呢
