### ISSUE TITLE
[INFO] [src:x.x.x.x:55570] [dst:1.1.1.1:53] [error:dial tcp 1.1.1.1:53: i/o timeout] TCP error

### ISSUE THREAD

**Issue by h605290713** [emptysuns/Hi_Hysteria#211]
[INFO] [src:x.x.x.x:55570] [dst:1.1.1.1:53] [error:dial tcp 1.1.1.1:53: i/o timeout] TCP error

当日志出现这个情况的时候 

同时去ping 1.1.1.1  延迟巨大

**Comment by emptysuns** [comment]
>同时去ping 1.1.1.1 延迟巨大

不觉得是你网络的问题吗？
