### ISSUE TITLE
【ERROR】纯ipv6小只因使用时客户端报错 network is unreachable

### ISSUE THREAD

**Issue by Yanqi7** [emptysuns/Hi_Hysteria#212]
内容如下：
hysteria 实时日志,等级:info,按Ctrl+C退出: 
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
time="2023-02-04T23:11:22-05:00" level=error msg="failed to open connection" addr="1.1.1.1:53" error="dial udp 1.1.1.1:53: connect: network is unreachable"
2023-02-04T23:11:22-05:00 [INFO] [src:[240e:388:73d1:e800:1145:b1a0:1419:cb9e]:58505] [dst:clients2.google.com:443] [error:lookup clients2.google.com on [2001:67c:2b0::6]:53: dial udp 1.1.1.1:53: connect: network is unreachable] TCP error
2023-02-04T23:11:53-05:00 [INFO] [src:[240e:388:73d1:e800:1145:b1a0:1419:cb9e]:58505] [error:timeout: no recent network activity] Client disconnected
只因本身能通Google等，防火墙关闭，系统是Debian11
Operating System: Debian GNU/Linux 11 (bullseye)
      Linux Kernel: 5.10.0-8-amd64
      Architecture: x86_64
    Virtualization: kvm
需要挂warp的v4通道吗？

**Comment by emptysuns** [comment]
先建议使用wgcf后获得一个v4地址后再用
或者删除server 上面dns 1.1.1.1，重启服务端，使用系统自带dns

这也是个问题，没考虑周全，下次会修复

**Comment by Yanqi7** [comment]
谢谢哥，我电脑刚关，晚上试一下看，我刚warp挂上v4的ip，好像也有点问题，我晚上再改一下看看来反馈

**Comment by emptysuns** [comment]
已修复: [0.4.6](https://github.com/emptysuns/Hi_Hysteria/commit/a74407fad73169c57d1e555533a0a7e8cedc686d)
