### ISSUE TITLE
netfilter-persistent在RHEL系从8开始就没有了

### ISSUE THREAD

**Issue by zyppe** [emptysuns/Hi_Hysteria#214]
iptables相关在重启后消失，是否影响正常使用？

**Comment by sw19999** [comment]
debian11 系统重启后动态端口确实没有了，全段时间我反馈过，0.45b看起来修复了，实际上没有修复。重新配置依旧

**Comment by emptysuns** [comment]
> debian11 系统重启后动态端口，实测确实没有了，前段时间我反馈过，0.45b看起来修复了，实际上没有修复。重新配置依旧

对于这个问题，下次会将规则写到开机脚本里，不使用第三方包来做持久化

**Comment by Jiraiya8** [comment]
我安装iptables-persistent后，重新执行脚本，动态端口失效的问题得到了解决。我使用的版本是0.4.6，系统是debian11和Ubuntu22

**Comment by sw19999** [comment]
Debian11系统，按照楼上的提示，安装：sudo apt-get install iptables-persistent

然后重新配置一次hyst，重启后可以了

**Comment by sw19999** [comment]
> > debian11 系统重启后动态端口，实测确实没有了，前段时间我反馈过，0.45b看起来修复了，实际上没有修复。重新配置依旧
> 
> 对于这个问题，下次会将规则写到开机脚本里，不使用第三方包来做持久化

Debian11系统，按照楼上的提示，安装：sudo apt-get install iptables-persistent

然后重新配置一次hyst，重启后可以了

**Comment by emptysuns** [comment]
因为在hihy之前的版本安装netfilter-persistent时没有安装iptables-persistent，导致netfilter-persistent没有生效，所以如果是老版本带来的问题，手动安装`sudo apt-get install iptables-persistent`就行了，如果在新的系统里运行最新的脚本是不会有问题的。

对于RHEL系一直使用的firewalld管理，almalinux当然也是，不知道你系统的firewalld是不是不小心被你关闭了？

**Comment by richhe678** [comment]
我是这样修的：

1.
sudo yum install epel-release

2.
sudo yum install netfilter-persistent

“Because 应为 On CentOS, the netfilter-persistent package is not available by default. Instead, CentOS uses iptables-services for managing firewall rules. If you specifically require netfilter-persistent。”

**Comment by emptysuns** [comment]
> 我是这样修的：
> 
> 
> sudo yum install epel-release
> 
> 
> sudo yum install netfilter-persistent
> 
> “Because 应为 On CentOS, the netfilter-persistent package is not available by default. Instead, CentOS uses iptables-services for managing firewall rules. If you specifically require netfilter-persistent。”

不是，rhel系后面用firewall-cmd来添加端口跳跃，不用装netfilter-persistent
