### ISSUE TITLE
终端上显示的链接导入到 Matsuri 有问题

### ISSUE THREAD

**Issue by iKangnakamuyi** [emptysuns/Hi_Hysteria#218]
刚用脚本弄完的 Hysteria，放到 Matsuri 发现服务器地址有问题，难怪一打开就连不上。
![IMG_20230217_200654](https://user-images.githubusercontent.com/47733293/219650155-3649a42b-ffda-4264-8601-03702a1bb265.jpg)

**Comment by emptysuns** [comment]
已修复: [0.4.6](https://github.com/emptysuns/Hi_Hysteria/commit/a74407fad73169c57d1e555533a0a7e8cedc686d)
