### ISSUE TITLE
请问tcp error的情况要怎么解决呢？

### ISSUE THREAD

**Issue by e1lite** [emptysuns/Hi_Hysteria#220]
我是前天hysteria突然断流，之前20几天都用的好好的，我查了下好像是因为hysteria底层的QUIC连接超时断开并重连了，但我也开了udp模式的端口跳跃，日志就显示client disconnected和大量的tcp error，如下图:
![7ABF@BM2C{4(Z1O{_9$G{@N.png](https://user-images.githubusercontent.com/119770322/219829682-9c0fb1f3-5481-44f0-b10b-21ba7ec56b7a.png)

然后我重新配置了下，用的模式没变，还是udp+obfs，但我换了端口，现在的情况就是用流量连接和wifi连接过段时间就会出现断流，日志仍然显示tcp error，请问有什么办法能解决嘛?谢谢了！

**Comment by emptysuns** [comment]
你使用的运营商QoS你该ip的UDP 连接吧
换其他ip试试，或者用faketcp

**Comment by e1lite** [comment]
> 你使用的运营商QoS你该ip的UDP 连接吧
> 换其他ip试试，或者用faketcp

好的，谢谢您，我试一下
