### ISSUE TITLE
hysteria on windows, no black screen

### ISSUE THREAD

**Issue by woodlyer** [emptysuns/Hi_Hysteria#222]
When running hysteria on windows, If use .bat to run it.  
A black window will show.  
Use this gui tool to run hysteria in the background.  

https://github.com/woodlyer/gostGUI

**Comment by emptysuns** [comment]
* v2rayN[windows]: https://github.com/2dust/v2rayN
* clash.verge[windows]: https://github.com/zzzgydi/clash-verge/releases
* nekoray[windwos]: https://github.com/MatsuriDayo/nekoray/releases

Unfortunately, that client has been stopped updating a year ago, and now it is recommended to use the following on windows.
