### ISSUE TITLE
本脚本不支持此系统,请将下方日志反馈给开发者

### ISSUE THREAD

**Issue by mailsex** [emptysuns/Hi_Hysteria#225]
本脚本不支持此系统,请将下方日志反馈给开发者
 
  _   _ _ _          __   _____  ___   ___ _   _ 
 | | | | | |_ _ _ __ \ \ / / _ \/ __| | __| | | |
 | |_| | |  _| '_/ _` \ V /|  _/\__ \_| _|| |_| |
  \___/|_|\__|_| \__,_|\_/ |_|  |___(_)___|\___/ 

                       Reliable Virtual Servers                                                  
Linux version 5.4.0-135-generic (buildd@lcy02-amd64-066) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 

你好，脚本在vps上无法运行，系统是UBUNTU-20.04，vps 是www.ultravps.eu。
请问是什么原因呢，有没有办法解决。

**Comment by emptysuns** [comment]
被你vps服务商修改了镜像banner，系统识别出问题了

**Comment by mailsex** [comment]
已解决。
