### ISSUE TITLE
用IPv6连接ssh安装HY失败，然后SSH被强制断线，再连只能用IPv4，IPv6怎么都连不上了。

### ISSUE THREAD

**Issue by SunnyGPT** [emptysuns/Hi_Hysteria#227]
->您选择的验证方式为:obfs 
请输入客户端名称备注(默认使用域名/IP区分,例如输入test,则名称为Hys-test): 

配置录入完成!
 
执行配置... 
net.core.rmem_max = 8000000
net.ipv4.ip_forward = 1

Session was closed
-------------------
ipv4可以正常安装使用，我想在IPv6环境下使用，服务器用的是亚马逊Lightsail Dibian11
![WX20230309-174620](https://user-images.githubusercontent.com/126902077/223984532-71c90a86-b3ca-4496-a2f4-e13ef26457a4.png)

**Comment by emptysuns** [comment]
你看看ipv6用国外机器能访问吗

**Comment by SunnyGPT** [comment]
> 你看看ipv6用国外机器能访问吗

用全局代理也访问不了只有IPv4可以访问，主要是ipv4连上ssh输入ping6 ipv6.google.com也不行了，没安装之前可以。

**Comment by emptysuns** [comment]
我看你执行配置时net.ipv4.ip_forward = 1应该用了端口跳跃
下一步为了ipv6转发，会配置net.ipv6.ip_forward = 1，但是到这里就中断了，这个参数启用是为了让iptables转发流量用的

我也实在无法定位问题所在
