### ISSUE TITLE
大佬，什么时候支持mac客户端啊，每次都靠clash for windows+终端命令，太难了

### ISSUE THREAD

**Issue by SunnyGPT** [emptysuns/Hi_Hysteria#229]
![WX20230309-233959](https://user-images.githubusercontent.com/126902077/224075553-eb6fc783-bdd5-43a8-8878-ae756f28430a.png)

**Comment by SunnyGPT** [comment]
下载生成的yaml文件，从Mac clash导入就是上面的错误

**Comment by emptysuns** [comment]
需要使用[clash.meta](https://github.com/MetaCubeX/Clash.Meta/releases/tag/Prerelease-Alpha)内核，自己替换一下

**Comment by SunnyGPT** [comment]
> 需要使用[clash.meta](https://github.com/MetaCubeX/Clash.Meta/releases/tag/Prerelease-Alpha)内核，自己替换一下

切换内核OK了，谢大佬指点！

**Comment by y0unghe** [comment]
> 需要使用[clash.meta](https://github.com/MetaCubeX/Clash.Meta/releases/tag/Prerelease-Alpha)内核，自己替换一下

在mac 用的ClashX, 怎么替换内核啊
