### ISSUE TITLE
关于自定义证书的问题

### ISSUE THREAD

**Issue by SunnyGPT** [emptysuns/Hi_Hysteria#230]
之前我安装了宝塔，再安装这个就冲突了。现在我用了干净的系统安装了这个，不知道能否直接部署wp博客。

**Comment by SunnyGPT** [comment]
之前是80还是443端口被占用了就安装不了，好像是证书那块，现在是先装好了歇斯底里，现在想装个网站

**Comment by emptysuns** [comment]
涉及到证书申请使用HTTP-01验证，需要占用80端口
你可以用工具申请证书，然后安装时指定证书位置即可

**Comment by SunnyGPT** [comment]
大佬，我用cloudflare生成的免费tls证书可以吗？但是只生成了key和pem，可以指点一下怎么转(需fullchain cert,提供完整证书链)吗？我查半天教程也没找到个清楚的

**Comment by SunnyGPT** [comment]
证书搞到了，放在root目录cy文件夹下面，但是./cy路径怎么填都不对啊

**Comment by SunnyGPT** [comment]
大佬，证书是我从letsencrypt.osfipin.com网站上申请的，明明放在服务器root目录的changyun文件夹下，为什么会安装日志报错提示不存在啊？
![Uploading WX20230327-004129.png…]()
![Uploading 2.png…]()

**Comment by SunnyGPT** [comment]
大佬，证书是我从letsencrypt.osfipin.com网站上申请的，明明放在服务器root目录的changyun文件夹下，为什么会安装日志报错提示不存在啊？
![WX20230327-004129](https://user-images.githubusercontent.com/126902077/227790900-b5304d08-54ec-4471-b063-25ef94953b2a.png)
![2](https://user-images.githubusercontent.com/126902077/227790903-84641383-c7ac-4e61-aa42-b15db3844509.png)

**Comment by SunnyGPT** [comment]
在线等大佬
