### ISSUE TITLE
v2rayN-With-Hysteria客户端问题

### ISSUE THREAD

**Issue by flowercoder** [emptysuns/Hi_Hysteria#231]
问题如下，当你导入你的json配置文件后，它会根据你v2rayn当前的监听端口产生相应的监听端口号在配置文件中，当你再要修改v2rayn的端口时，光改客户端的端口号是无法使用的，只能删除当先配置，重新导入，或是将配置文件内的端口号改成新的端口号。希望我描述的足够清楚。

**Comment by emptysuns** [comment]
你是指自动变更JSON里的socks5和http监听端口？

**Comment by flowercoder** [comment]
> 你是指自动变更JSON里的socks5和http监听端口？

v2rayn设置的端口号手动更改后，该Hysteria配置文件的端口号不会变。

**Comment by flowercoder** [comment]
> socks5

差不多是这个意思，希望端口号能跟着系统配置走。如果做不了的话，希望能在readme里标一下，我被这个问题困扰了挺久。

**Comment by emptysuns** [comment]
> > socks5
> 
> 差不多是这个意思，希望端口号能跟着系统配置走。如果做不了的话，希望能在readme里标一下，我被这个问题困扰了挺久。

问题是，只靠生成一个JSON文件又没有执行权限，如何更改代理地址呢，你不如去v2rayN去提这个需求

而且你安装完毕后，输出结果时有很长一段提示信息：

1* [v2rayN/nekoray] 使用hysteria core直接运行:
客户端配置文件输出至: /root/Hys-demo(v2rayN).json ( 直接下载生成的配置文件[推荐] / 自行复制粘贴下方配置到本地 )
**Tips:客户端默认只开启http(8888)、socks5(8889)代理!其他方式请参照hysteria文档自行修改客户端config.json**
