### ISSUE TITLE
请问默认申请的ACME证书路径在什么位置？

### ISSUE THREAD

**Issue by aclscn** [emptysuns/Hi_Hysteria#232]
请问默认申请的ACME证书路径在什么位置？

root@XXX:/etc/hihy# tree .
.
├── acl
│   └── hihyServer.acl
├── bin
│   └── appS
├── cert
├── conf
│   ├── hihy.conf
│   └── hihyServer.json
└── result
    ├── hihyClient.json
    ├── metaHys.yaml
    └── url.txt

**Comment by emptysuns** [comment]
你用hihy则是root用户运行的，在这个文件夹：
`/root/.local/share/certmagic/certificates/acme-v02.api.letsencrypt.org-directory/`

**Comment by Morris-Lucifer** [comment]
现在的hy2版本好像不在这个目录下面了
