### ISSUE TITLE
请问频繁出现这种情况，是端口被封了，还是怎么回事。

### ISSUE THREAD

**Issue by SunnyGPT** [emptysuns/Hi_Hysteria#233]
亚马逊两台服务器，一台用了二十天一台用了一个礼拜，Mac笔记本用着一直很稳定，但是自从昨天小米手机使用代理（通过WI-FI连接MAC笔记本的代理端口）之后半个小时，MAC客户端开始自己断网，重启客户端就会恢复正常，但没多久又会断网，开始频繁出现这个现象。切换服务器就会报以下错误。
![1679645982075](https://user-images.githubusercontent.com/126902077/227464388-02218520-7009-4ee3-857b-84843c2a1bcc.jpg)

**Comment by emptysuns** [comment]
被掐udp了吧，可以用socat看看
