### ISSUE TITLE
请教大佬证书问题

### ISSUE THREAD

**Issue by ryan12399** [emptysuns/Hi_Hysteria#234]
请教大佬，我看您文档里写用自签证书会有问题，那如果我用推荐证书，使用cloudflare去解析一个域名来申请证书的话，会不会大幅降低延迟和速度，因为我之前用过xray协议就使用过Cf来解析伪装，但速度和延迟下降的非常厉害，谢谢

**Comment by emptysuns** [comment]
.....不会，hysteria不能通过cloudflare代理流量，只能直连

**Comment by ryan12399** [comment]
谢谢大佬
