### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by jjyung168** [emptysuns/Hi_Hysteria#236]
[Network error]: Failed to get the latest version of hysteria in Github! 安装时老显示这个怎么办

**Comment by emptysuns** [comment]
ip太脏了被GitHub拉黑了

**Comment by 839781960** [comment]
> ip太脏了被GitHub拉黑了

有个问题，考虑加个自签吗openssl证书

**Comment by jjyung168** [comment]
我本地的 ip 太脏了？还是鸡子的 ip

**Comment by emptysuns** [comment]
> 我本地的 ip 太脏了？还是鸡子的 ip
你服务器ip...

> > ip太脏了被GitHub拉黑了
> 
> 有个问题，考虑加个自签吗openssl证书

现在带的自签不就是吗
