### ISSUE TITLE
因为小火箭太卡了，我换成了stash，但是无法连接

### ISSUE THREAD

**Issue by datougua** [emptysuns/Hi_Hysteria#238]
直接用obfs连不上，用auth_str明文密码不行，改成base64也不行。
配置文件是直接用大哥这个hihy导出的，电脑端用clash可以使用

**Comment by datougua** [comment]
alpn:
  - h3
  auth_str: 打码
  disable_mtu_discovery: true
  down: 110
  name: 打码
  port: 13636
  protocol: udp
  recv_window: 13631488
  recv_window_conn: 3407872
  server: 打码
  skip-cert-verify: false
  sni: 打码
  type: hysteria
  up: 22

**Comment by emptysuns** [comment]
没有iOS设备，有日志吗

**Comment by datougua** [comment]
已经解决了，是官方的配置文件有问题，auth_str不行，要删掉_str

**Comment by ydwg** [comment]
> 
啥意思啊 auth_str 改成 auth？
试了不行

**Comment by datougua** [comment]
大佬，我配置的可以，但是最近换了个vps，生成就不行了

[INFO] [10:27:30] [INIT] use config file: /private/var/mobile/Containers/Shared/AppGroup/3F289589-5DAC-4377-8657-9374457F7E97/stash/config.yaml
[INFO] [10:27:30] [API] start proxy server at port: 7890
[INFO] [10:27:30] [API] start stashsocks server
[INFO] [10:27:31] [CORE] stash core started, used memory: 13.3M
[INFO] [10:27:31] [API] network type changed to cellular, ipv4=true, ipv6=true, hotspot=false
[WARN] [10:27:32] [DPC] <TCP> connect 172.217.160.110:443 via PROXY match MATCH/ error: INTERNAL_ERROR (local): write udp [::]:60055->147.78.245.66:0: sendto: can't assign requested address
[WARN] [10:27:44] [DPC] <TCP> connect stocks-data-service.apple.com:443 via PROXY match RULE-SET(DOMAIN)/proxy error: INTERNAL_ERROR (local): write udp [::]:60583->147.78.245.66:0: sendto: can't assign requested address
[WARN] [10:27:44] [DPC] <TCP> connect stocks-data-service.apple.com:443 via PROXY match RULE-SET(DOMAIN)/proxy error: INTERNAL_ERROR (local): write udp [::]:65464->147.78.245.66:0: sendto: can't assign requested address
[WARN] [10:27:44] [DPC] <TCP> connect stocks-data-service.apple.com:443 via PROXY match RULE-SET(DOMAIN)/proxy error: INTERNAL_ERROR (local): write udp [::]:63257->147.78.245.66:0: sendto: can't assign requested address

**Comment by datougua** [comment]
> 

你看下你的yaml是不是多端口的，改成单端口应该就可以，stash现在可能还不支持多端口

**Comment by ydwg** [comment]
> 

感谢 我是多端口
