### ISSUE TITLE
安装完一会儿，就显示未正常运行。

### ISSUE THREAD

**Issue by eightsheep67** [emptysuns/Hi_Hysteria#24]
安装完，检测运行状态，显示dead！未正常运行。
重新启动hysteria，然后又正常运行，再测试一下又未正常运行

**Comment by emptysuns** [comment]
出现这个问题，大概率是你的用ACME无法申请证书导致的，尝试自签证书的方式吧，这个问题原因很多，很难下手，以后可能尝试不用它的内置申请了。
**不过反复横条确实是我脚本的问题*，这个是bug下个版本修复*

**Comment by eightsheep67** [comment]
> 出现这个问题，大概率是你的用ACME无法申请证书导致的，尝试自签证书的方式吧，这个问题原因很多，很难下手，以后可能尝试不用它的内置申请了。 **_不过反复横跳确实是我脚本的问题_，这个是bug下个版本修复***

自签wechat可以用了。

**Comment by emptysuns** [comment]
> > 出现这个问题，大概率是你的用ACME无法申请证书导致的，尝试自签证书的方式吧，这个问题原因很多，很难下手，以后可能尝试不用它的内置申请了。 **_不过反复横跳确实是我脚本的问题_，这个是bug下个版本修复***
> 
> 自签wechat可以用了。这个passwall有办法使用自签证书吗？

直接选上那个允许不安全，passwall在ui上不能加自签证书，你可以用nohup &起一个进程然后sokcs5套娃到passwall

**Comment by emptysuns** [comment]
[0.3.1](https://github.com/emptysuns/Hi_Hysteria/commit/6abcf44e92155a18da0b18cb1bc18d0b95a682f8)
