### ISSUE TITLE
大佬，如何设置用户只能访问指定域名？

### ISSUE THREAD

**Issue by SunnyGPT** [emptysuns/Hi_Hysteria#240]
大佬，如何设置用户启动代理之后，只能访问指定域名或名单域名？能在服务端完成配置最好，实在不行了再改客户端配置。

**Comment by emptysuns** [comment]
服务端配置ACL，只允许proxy允许的域名，然后drop all规则收底

**Comment by SunnyGPT** [comment]
大佬你的方案太牛哔了，不过我是ubuntu新手不知道怎么做，以下是我从ChatGPT4和Claude那里问来的具体教程，辛苦你帮我看下，哪个AI给的教程才是对的。
![GPT4](https://user-images.githubusercontent.com/126902077/234182875-621df497-a765-4fb7-9a3f-00d479b5103f.png)
![Claude](https://user-images.githubusercontent.com/126902077/234182892-7d3a9277-ec72-4b39-92e6-19bd99a43776.png)

**Comment by emptysuns** [comment]
都不对
我给你个例子吧，编辑`/etc/hihy/acl/hihyServer.acl`,把`google.com`.`youtube.com` 换成你自己想要的域名
```
proxy domain-suffix google.com
proxy domain-suffix youtube.com
block all udp/443
block all
```
然后,运行`hihy 5`重启服务器

**Comment by SunnyGPT** [comment]
> 都不对 我给你个例子吧，编辑`/etc/hihy/acl/hihyServer.acl`,把`google.com`.`youtube.com` 换成你自己想要的域名
> 
> ```
> proxy domain-suffix google.com
> proxy domain-suffix youtube.com
> block all udp/443
> block all
> ```
> 
> 然后,运行`hihy 5`重启服务器

大佬牛哔，如果想添加的域名使用了cloudflare机器人检查，是不是也要把机器人检查的域名加进去？

**Comment by emptysuns** [comment]
是，默认block all
