### ISSUE TITLE
大佬，ubuntu如何使用代理？

### ISSUE THREAD

**Issue by SunnyGPT** [emptysuns/Hi_Hysteria#242]
ubuntu命令行版，不是桌面版，主要是这个代理太牛哔了，根本停不下来，不想用x-ui，不想用别的。

**Comment by emptysuns** [comment]
.....都用ubuntu了，直接写个systemd守护进程启动客户端
因为hysteria提供socks5 inbound，启动客户端后直接设置系统代理就行了

**Comment by SunnyGPT** [comment]
> .....都用ubuntu了，直接写个systemd守护进程启动客户端 因为hysteria提供socks5 inbound，启动客户端后直接设置系统代理就行了

大佬666谢谢大佬，我在ubuntu上安装好歇斯底里之后，用windows服务器上运行v2ray或clash.meta都无法访问chat.openai.com，无限加载cloudflare 机器人检查，怎么点真人验证都会重新加载，但换成http透明代理就不会这样，连着换了三台windows服务器都不行（win10和mac没事），请问大佬到底是怎么回事呢，急着在服务器上用

**Comment by SunnyGPT** [comment]
> .....都用ubuntu了，直接写个systemd守护进程启动客户端 因为hysteria提供socks5 inbound，启动客户端后直接设置系统代理就行了

大佬，在线等， windows server服务器上用代理一直被cloudflare 机器人拦截，怎么搞定啊。

**Comment by SunnyGPT** [comment]
> 不知道

大佬，我找到原因了，和ipv6有关，如何在服务端设置只允许使用ipv4，不允许ipv6呢？还有如何添加规则，只允许特定IP连接呢？

**Comment by SunnyGPT** [comment]
已经找到了，客户端已有功能可以关闭ipv6
