### ISSUE TITLE
本脚本不支持此系统,请将下方日志反馈给开发者  Welcome to Alpine Linux 3.16  on an \m (\l) Linux version 5.15.85-1-pve (build@proxmox) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z)

### ISSUE THREAD

**Issue by aisuyi065** [emptysuns/Hi_Hysteria#244]
本脚本不支持此系统,请将下方日志反馈给开发者

Welcome to Alpine Linux 3.16
 on an \m (\l)
Linux version 5.15.85-1-pve (build@proxmox) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z)

**Comment by emptysuns** [comment]
Alpine 建议用nohup挂起运行不建议用脚本
