### ISSUE TITLE
[Network error]: Failed to get the latest version of hysteria in Github! 

### ISSUE THREAD

**Issue by FugitiveL** [emptysuns/Hi_Hysteria#245]
测试两台都这样。5.10晚开始的

**Comment by ddd-zero** [comment]
```
请选择:1
Ready to install.
 

Update.wait... 
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://ftp.debian.org/debian buster InRelease
Hit:3 http://ftp.debian.org/debian buster-updates InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
90 packages can be upgraded. Run 'apt list --upgradable' to see them.

Done. 
The Latest hysteria version: 
Download...
[Network error]: Failed to get the latest version of hysteria in Github! 
```

**Comment by shihuibei** [comment]
curl https://api.github.com/repos/apernet/hysteria/releases/latest
ip被github 限制了，需要改脚本增加github token就可以解决


wget -qO- -t1 -T2 --no-check-certificate --header='Authorization:your github token'  "https://api.github.com/repos/apernet/hysteria/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g'

**Comment by emptysuns** [comment]
下次更新会修复这个问题，不直接访问API获取版本号了

**Comment by emptysuns** [comment]
已修复

**Comment by alipapabi** [comment]
我的软件版本已经升级到0.4.8了，但是还是提示这个错误，有解决办法吗？

**Comment by emptysuns** [comment]
> 我的软件版本已经升级到0.4.8了，但是还是提示这个错误，有解决办法吗？

https://github.com/emptysuns/Hi_Hysteria/issues/251
有一个预料外的bug，请升级0.4.8.a已修复
