### ISSUE TITLE
这个脚本能支持几个配置？

### ISSUE THREAD

**Issue by eightsheep67** [emptysuns/Hi_Hysteria#25]
这个脚本能支持几个配置？
因为公司和家里的带宽不一样，我配置了两个端口，是都可以使用吗？但是查看配置好像只能看到最新配置的那个

**Comment by eightsheep67** [comment]
然后PASSWALL里面添加完了，显示超时，是正常的吗？？

**Comment by emptysuns** [comment]
目前就一个
按你的需求，两个可以"通用"...随便选一个用就行了
可以考虑以后增加一个功能提供"多配置共存"
