### ISSUE TITLE
[Warnning]:netfilter-persistent安装失败,但安装进度不会停止,只是您的PortHopping转发规则为临时规则,重启可能失效,是否继续使用临时规则?(y/N)

### ISSUE THREAD

**Issue by sleeeeeeepa** [emptysuns/Hi_Hysteria#250]
centos7 会出现这个  重启后PortHopping确实失效了,  有什么解决办法吗?

**Comment by emptysuns** [comment]
c7没有netfilter-persistent
c7用的是firewalld转发的，你的firewalld是否正常运行呢？

**Comment by sleeeeeeepa** [comment]
systemctl status firewalld
Unit firewalld.service could not be found.

也没...

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/9d8cab7d0764aa851920efb751fe69d8b871e301/server/install.sh#L1128-L1160
这个是检测逻辑
当检测不到firewalld才会使用netfilter-persistent做持久化
c7里面firewalld是默认启用的包，你无法找到它，说明你自己uninstall了

**Comment by sleeeeeeepa** [comment]
明白了。
