### ISSUE TITLE
[Network error]: Failed to get the latest version of hysteria in Github!

### ISSUE THREAD

**Issue by sleeeeeeepa** [emptysuns/Hi_Hysteria#251]
最新版还是出现这个错误

Update.wait... 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.wcupa.edu
 * extras: nyc.mirrors.clouvider.net
 * updates: forksystems.mm.fcix.net
No packages marked for update

Done. 
The Latest hysteria version: 
Download...
[Network error]: Failed to get the latest version of hysteria in Github!

**Comment by sleeeeeeepa** [comment]
0.4.8

**Comment by sleeeeeeepa** [comment]
通过 curl https://api.github.com/repos/apernet/hysteria/releases/latest 可以正常返回

**Comment by sleeeeeeepa** [comment]
用wget把脚本下载下来  按下图把首字母改成大写L就可以了   希望作者更新一下线上
![image](https://github.com/emptysuns/Hi_Hysteria/assets/26105843/ba671b1e-3b4f-47db-b44e-c6a3293580e6)

**Comment by sleeeeeeepa** [comment]
用命令临时修改
sed -i 's|grep location|grep Location|g' hysteria.sh

**Comment by emptysuns** [comment]
```
root@vps:~# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'
v1.3.5
root@vps:~# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep Location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'
root@vps:~# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep Location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'
root@vps:~# 
```

理论上就是小写，请问能否提供完整的log
```
curl --head -s https://github.com/apernet/hysteria/releases/latest
```

**Comment by sleeeeeeepa** [comment]
`[root@8564 ~]# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'
[root@8564 ~]# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep Location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'
v1.3.5
[root@8564 ~]# curl --head -s https://github.com/apernet/hysteria/releases/latest
HTTP/1.1 302 Found
Server: GitHub.com
Date: Wed, 14 Jun 2023 09:13:28 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
Location: https://github.com/apernet/hysteria/releases/tag/v1.3.5
Cache-Control: no-cache
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events *.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ wss://*.actions.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com objects-origin.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
Set-Cookie: _gh_sess=kjiatyf%2BbR4XYOhoeE1Qs1wgLQhW6jirsnc4sbsG92eFAfnYxAl5vqsw%2BW92STCe6qicf%2FqNikytbPuwaptFDVV35OUrAu%2FKw3wRB7wn09nDeneVOHoeF42qkyk6GBWKKs08Cd4Whbo%2FRUOEU1B84aTWAwWINAgkDPH5aiuOfg%2BWjfcQI5y8npIp00fwNbnSwvwkTyVsPtYu64zdvjxSZ9iD2BHaNZYdQPcv1K3sR5PnGoJ%2FSHvk3Yz6D12E3oZFvHWTedMjbrWIudKzyuYerg%3D%3D--dI%2FDy6bVsWA70a2C--RsLjblgQz7b4hbtPl%2FNRQA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.116841223.1686734053; Path=/; Domain=github.com; Expires=Fri, 14 Jun 2024 09:14:13 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 14 Jun 2024 09:14:13 GMT; HttpOnly; Secure; SameSite=Lax
Content-Length: 0
`

这就很尴尬了...

**Comment by sleeeeeeepa** [comment]
[root@8564 ~]# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'


[root@8564 ~]# curl --head -s https://github.com/apernet/hysteria/releases/latest | grep Location | grep -o 'tag/[^[:space:]]*' | sed 's/tag\///;s/ //g'
v1.3.5


[root@8564 ~]# curl --head -s https://github.com/apernet/hysteria/releases/latest
HTTP/1.1 302 Found
Server: GitHub.com
Date: Wed, 14 Jun 2023 09:13:28 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
Location: https://github.com/apernet/hysteria/releases/tag/v1.3.5
Cache-Control: no-cache
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events *.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ wss://*.actions.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com objects-origin.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
Set-Cookie: _gh_sess=kjiatyf%2BbR4XYOhoeE1Qs1wgLQhW6jirsnc4sbsG92eFAfnYxAl5vqsw%2BW92STCe6qicf%2FqNikytbPuwaptFDVV35OUrAu%2FKw3wRB7wn09nDeneVOHoeF42qkyk6GBWKKs08Cd4Whbo%2FRUOEU1B84aTWAwWINAgkDPH5aiuOfg%2BWjfcQI5y8npIp00fwNbnSwvwkTyVsPtYu64zdvjxSZ9iD2BHaNZYdQPcv1K3sR5PnGoJ%2FSHvk3Yz6D12E3oZFvHWTedMjbrWIudKzyuYerg%3D%3D--dI%2FDy6bVsWA70a2C--RsLjblgQz7b4hbtPl%2FNRQA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.116841223.1686734053; Path=/; Domain=github.com; Expires=Fri, 14 Jun 2024 09:14:13 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 14 Jun 2024 09:14:13 GMT; HttpOnly; Secure; SameSite=Lax
Content-Length: 0


这就很尴尬了

**Comment by H4Ha** [comment]
加一，同样遇到这个问题，希望大佬修复

**Comment by emptysuns** [comment]
> Location: https://github.com/apernet/hysteria/releases/tag/v1.3.5

这个是curl的不同版本的问题？
还是github的问题？
算了，写一个两者都判断吧，马上修复

**Comment by emptysuns** [comment]
已修复
[0.4.8.a](https://github.com/emptysuns/Hi_Hysteria/commit/cdc87fdb0f90740d82135efac9ee20767bc8feb4)
