### ISSUE TITLE
 本脚本不支持此系统,请将下方日志反馈给开发者

### ISSUE THREAD

**Issue by mailsex** [emptysuns/Hi_Hysteria#252]
用的这家的vps：https://www.ultravps.eu/en/
操作系统：DEBIAN-10

本脚本不支持此系统,请将下方日志反馈给开发者
 
  _   _ _ _          __   _____  ___   ___ _   _ 
 | | | | | |_ _ _ __ \ \ / / _ \/ __| | __| | | |
 | |_| | |  _| '_/ _` \ V /|  _/\__ \_| _|| |_| |
  \___/|_|\__|_| \__,_|\_/ |_|  |___(_)___|\___/ 

                       Reliable Virtual Servers                                                  
Linux version 4.19.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)

**Comment by mailsex** [comment]
已DD更换系统。解决问题。

**Comment by Wenbobobo** [comment]
咱也遇到了......

本脚本不支持此系统,请将下方日志反馈给开发者
 
Armbian 23.8.1 lunar \l  
Linux version 6.1.44-ophub (cc@fv-az412-791) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205, GNU ld (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 2.39.0.20221210) #1 SMP Wed Aug  9 06:33:22 EDT 2023 
Reinstall Complete!
