### ISSUE TITLE
很多Google服务无法正常使用，看了日志貌似是ACL规则的问题

### ISSUE THREAD

**Issue by shentong0722** [emptysuns/Hi_Hysteria#253]
最近很多Google服务无法正常使用了，点击下一步没有反应，人机验证永远过不去等，看了日志好像是相关的流量被ACL规则阻止了，作者能否检查一下？

**Comment by emptysuns** [comment]
ACL会屏蔽AD地址，应该不会影响正常服务
有没有详细的日志呢
