### ISSUE TITLE
申请证书失败 过程没有报错端口可正常访问

### ISSUE THREAD

**Issue by sleeeeeeepa** [emptysuns/Hi_Hysteria#254]
hihy版本为 : 0.4.8.a

执行配置... 
net.core.rmem_max = 80000000
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

Test config...

域名:101l.xxx.shop,申请证书失败!请查看服务器提供的面板防火墙是否开启(TCP:80,443)
域名是否正确解析到此ip(不要开CDN!)
如果无法满足以上两点,请重新安装使用自签证书. 

----------------------

各类配置如下

##### 系统版本
[root@9491 ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

##### 防火墙开放端口
[root@9491 ~]# firewall-cmd --list-ports
You're performing an operation over default zone ('public'),
but your connections/interfaces are in zone 'docker' (see --get-active-zones)
You most likely need to use --zone=docker option.

22/tcp 443/tcp 80/tcp 10121/tcp 10121/udp 10131/tcp 10131/udp

##### 防火墙状态
[root@9491 ~]#  systemctl status firewalld -l
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2023-06-25 04:39:33 EDT; 12min ago
     Docs: man:firewalld(1)
 Main PID: 2385 (firewalld)
    Tasks: 2
   Memory: 29.8M
   CGroup: /system.slice/firewalld.service
           └─2385 /usr/bin/python2 -Es /usr/sbin/firewalld --nofork --nopid

Jun 25 04:43:04 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 25 04:43:36 9491.com firewalld[2385]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Jun 25 04:43:37 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 25 04:43:37 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 25 04:43:57 9491.com firewalld[2385]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Jun 25 04:43:58 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 25 04:43:58 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 25 04:52:10 9491.com firewalld[2385]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Jun 25 04:52:11 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Jun 25 04:52:11 9491.com firewalld[2385]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

#### 使用外部网站测试端口开放情况
使用 while true; do nc -l 80; done 以后 可以访问端口  443同样
![image](https://github.com/emptysuns/Hi_Hysteria/assets/26105843/e3955f93-6bec-4a1f-a917-a807d8d0b8c6)

**Comment by emptysuns** [comment]
有时候一个域名尝试申请过多次也会报错，换个子域名试试呢
