### ISSUE TITLE
faketcp需要开放什么端口，是tcp端口还是udp端口

### ISSUE THREAD

**Issue by remember19890604** [emptysuns/Hi_Hysteria#255]
vps有防火墙安全组，开放了udp端口后，udp模式正常，但faketcp模式连不上

**Comment by emptysuns** [comment]
你觉得它为什么叫faketcp
肯定得开放tcp端口啊

**Comment by remember19890604** [comment]
> 你觉得它为什么叫faketcp 肯定得开放tcp端口啊

开放了tcp端口好像也不行，不知道是不是有什么干扰？

**Comment by emptysuns** [comment]
放个日志看看，客户端的
