### ISSUE TITLE
PASSWALL里显示超时

### ISSUE THREAD

**Issue by eightsheep67** [emptysuns/Hi_Hysteria#26]
换了一台机可以正常了，先配置了UDP协议的一个给小火箭，可以正常使用，然后在PASSWALL里面添加完了，显示超时。
又配置了一个FAKETCP，PASSWALL还是不能用。
不管是UDP模式还是FAKETCP都是超时。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/blob/main/md/others.md

**Comment by eightsheep67** [comment]
> https://github.com/emptysuns/Hi_Hysteria/blob/main/md/others.md

有的。我编译的最新的passwall 4.51-7，也把hysteria编译进去了，1.0.1版本。

**Comment by emptysuns** [comment]
```
systemctl stop hihys
/etc/hihys/appS -c /etc/hihys/config.json server
```

试试这个，看看server正常吗?

**Comment by eightsheep67** [comment]
我passwall用会10001端口的配置就正常了，虽然超时但是转成socks显示正常，负载均衡也可以用。
话说这个脚本要怎么样重新配置呢？卸载再重新安装我担心申请证书又超限了。。。

**Comment by eightsheep67** [comment]
而且很诡异，我主节点直接用这个hysteria节点没法用，一定要转成socks再添加到haproxy负载均衡，只选择了这个节点，然后主节点用负载均衡的就可以正常连接。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/9

比如这种情况?

**Comment by eightsheep67** [comment]
不是，应该是passwall的问题，这个节点我在小火箭一直可以用，passwall上用就是很奇怪，不过负载均衡能用就好，我本来就是为了弄成负载均衡的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: emptysuns ***@***.***&gt;
发送时间: 2022年3月22日 12:39
收件人: emptysuns/Hi_Hysteria ***@***.***&gt;
抄送: eightsheep ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [emptysuns/Hi_Hysteria] PASSWALL里显示超时 (Issue #26)





 
#9
 
比如这种情况?

**Comment by emptysuns** [comment]
那我到这就帮不了你了...
你可以寻求passwall社区和openwrt社区的帮助，因为我一直也在使用passwall没有出现过你的这种问题。
