### ISSUE TITLE
 FATAL   failed to parse server config   {"error": "2 error(s) decoding:\n\n* 'acl' expected a map, got 'string'\n* 'obfs' expected a map, got 'string'"}

### ISSUE THREAD

**Issue by iceraintsx** [emptysuns/Hi_Hysteria#265]
更新Core后重新启动异常，安装 hysteria也报错，具体信息如下：

配置录入完成!
 
执行配置... 
IPTABLES OPEN: tcp/80 
net.core.rmem_max = 80000000
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.eth0.autoconf = 0
net.ipv6.conf.eth0.accept_ra = 0
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

Test config...

未知错误: 请查看下方错误信息,并提交issue到github 
2023-09-02T06:58:52+01:00       INFO    server mode
2023-09-02T06:58:52+01:00       FATAL   failed to parse server config   {"error": "2 error(s) decoding:\n\n* 'acl' expected a map, got 'string'\n* 'obfs' expected a map, got 'string'"}

**Comment by crosspacific** [comment]
一模一样的错误。也是最近刚刚出现。

**Comment by emptysuns** [comment]
已修复，请升级成[0.4.9](https://github.com/emptysuns/Hi_Hysteria/commit/f524d5c158121678b6d07d68e46b78bd763550c0)
出现原因是v1和v2互不兼容，脚本会自动获取最新的hysteria版本，用hysteria v2执行了v1的配置

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/264
