### ISSUE TITLE
怎么修改配置？

### ISSUE THREAD

**Issue by wander555** [emptysuns/Hi_Hysteria#27]
修改/etc/hihys/config.json之后，然后hihys 选择5，似乎没有重新加载？

**Comment by emptysuns** [comment]
**刚才push了**`0.3.1`版本修了点bug,将配置文件夹改到`/etc/hihy`这儿了,而且**这是最后一次变更配置文件夹位置**

5选项本质上是利用systemctl重启hysteria而已,如果你没有使用过`0.3.1`请判断你是否成功修改配置吧 👍
