### ISSUE TITLE
甲骨文最近疯狂丢包……

### ISSUE THREAD

**Issue by eightsheep67** [emptysuns/Hi_Hysteria#28]
Hysteria对丢包线路是否也无能为力啊……
这个甲骨文韩国线路延迟波动很大，低得时候50左右，高得时候200左右，再高就是丢包了。
这个延迟设置得越大是流量消耗越大吗？对于性能有没有什么影响。

**Comment by emptysuns** [comment]
影响肯定有，有重传功能，丢多少包，就多消耗多少流量，比起传统tcp的协议，udp高丢包环境下效果更好。

那个延迟只是为了计算buffer size，尽可能照着你延迟最大的写就行了。
