### ISSUE TITLE
这个问题？？？

### ISSUE THREAD

**Issue by Potterli20** [emptysuns/Hi_Hysteria#3]
\033[32m下载完成！\033[0m
\033[42;37m开始配置: \033[0m
\033[32m请输入您的域名(不输入回车，则默认自签pan.baidu.com证书，不推荐):\033[0m
grpc.****.******
\033[32m请输入你想要开启的端口（此端口是server端口，请提前放行防火墙，建议10000-65535，回车随机）：\033[0m
2087
\033[32m请输入您到此服务器的平均延迟,关系到转发速度（回车默认200ms）:\033[0m

\n期望速度，请如实填写，这是客户端的峰值速度，服务端默认不受限。\033[31m期望过低或者过高会影响转发速度！\033[0m
\033[32m请输入客户端期望的下行速度:\033[0m

\033[32m请输入客户端期望的上行速度:\033[0m

\033[32m请输入混淆口令（相当于连接密钥）:\033[0m
potter-grpc
\033[32m配置录入完成！\033[0m
\033[42;37m执行配置...\033[0m
/dev/fd/63: line 62: 200 * 2 *  / 1000 * 1024 * 1024: syntax error: operand expected (error token is "/ 1000 * 1024 * 1024")

**Comment by emptysuns** [comment]
你输入期望上行下行速度呗，这个没做默认

**Comment by Potterli20** [comment]
> 你输入期望上行下行速度呗，这个没做默认
> 
> 而且我看在shell，诸如\033[32m \033[0m绿色没有很好被展示，请问你是用的sh运行的吗

是哈
sudo su root  #Change to the user root!
sh <(curl -fsSL https://git.io/hysteria.sh)

**Comment by emptysuns** [comment]
可能debian11 不认这个吧，没问题我关issue了
