### ISSUE TITLE
最新版本v2rayN已经支持Hysteria

### ISSUE THREAD

**Issue by idragonet** [emptysuns/Hi_Hysteria#31]
Hi_Hysteria能直接用上吗？（不启动Hi_Hysteria客户端）

![image](https://user-images.githubusercontent.com/9882118/160834198-5f945822-f6fb-49ee-90a6-e69cc53c7091.png)

**Comment by idragonet** [comment]
测试下粘贴JSON内容到v2rayN可以添加成功，但是无法上网。

**Comment by emptysuns** [comment]
1. 将cmd客户端文件夹下`acl`文件夹移动到**v2rayN的根目录**去，因为V2rayN不带分流功能，只能接着交给hysteria分流
2. 修改config.json下的http/socks5 代理端口改成v2rayN的，如下:
```
"http": {
"listen": "127.0.0.1:10809",
"timeout" : 300,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:10808",
"timeout": 300,
"disable_udp": false
},
```

终于有gui要支持了，现在应该处于测试阶段，甚至分流功能都没有只能这样接着套娃，以后等加入了一键链接导入和手动加入配置就好了。如果v2N等着它支持性很好的话，就考虑把cmd给移出项目了。

**Comment by idragonet** [comment]
> 1. V2rayN不带分流功能

V2rayN带分流功能，都用了2年了。

**Comment by idragonet** [comment]
![image](https://user-images.githubusercontent.com/9882118/160964155-217a9225-1cb4-444d-b695-56f0edc1ac75.png)
绕过大陆

**Comment by emptysuns** [comment]
> > 1. V2rayN不带分流功能
> 
> V2rayN带分流功能，都用了2年了。

那你试试把acl去掉还能分流吗？

**Comment by idragonet** [comment]
> 1. hysteria

哦！意思是V2rayN不支持hysteria分流。

现在遇到问题的V2rayN 用不了Hi_Hysteria。 先不说分流。

**Comment by emptysuns** [comment]
> 

照着我上面发的改就能用了

**Comment by 1304756868** [comment]
![QQ图片20220331200715](https://user-images.githubusercontent.com/23548300/161051300-4fe8a4ad-3623-4607-8617-5cf1ca2b48c2.png)

**Comment by emptysuns** [comment]
> ![QQ图片20220331200715](https://user-images.githubusercontent.com/23548300/161051300-4fe8a4ad-3623-4607-8617-5cf1ca2b48c2.png)

........不是提示你了吗，去下载core，放到v2rayN根目录。如果你是用的hihy脚本，根据如上修改一下，重新加入一下配置，就行了。

**Comment by bsdfz** [comment]
![image](https://user-images.githubusercontent.com/95695864/162795085-13f81f19-feed-40a1-bd0b-46bacb7f04ce.png)
不知哪里配置有错，导入v2rayN还是无法使用，在passwall里也无法使用，但在ios的小火箭却可以用

**Comment by QIN2DIM** [comment]
@bsdfz 重新把`protocal` 选择 `wechat-video`

**Comment by emptysuns** [comment]
> ![image](https://user-images.githubusercontent.com/95695864/162795085-13f81f19-feed-40a1-bd0b-46bacb7f04ce.png) 不知哪里配置有错，导入v2rayN还是无法使用，在passwall里也无法使用，但在ios的小火箭却可以用

https://github.com/emptysuns/Hi_Hysteria/issues/31#issuecomment-1083987589

请仔细看看我发的...
如果测试没问题的话，下次更新将取代cmd客户端，统一兼容v2rayN

**Comment by lstone1228** [comment]
在v2rayn里设置完路由模式也不能分流，直接全局代理。设置如下：
  "up": "20 Mbps",
  "up_mbps": 20,
  "down": "50 Mbps",
  "down_mbps": 50,
  "socks5": {
    "listen": "127.0.0.1:10808", 
    "timeout": 300,
    "disable_udp": false 
    },
  "http": {
    "listen": "127.0.0.1:10809",
    "timeout": 300,
    "disable_udp": false 
  },
  "obfs": "fkwall", 
  "server_name": "fkwall.eu.org", 
  "insecure": false, 
  "disable_mtu_discovery": false,
   "resolver": "8.8.8.8:53",
  "resolve_preference": "64" 
}
请问有办法解决吗？
<img width="1280" alt="hy" src="https://user-images.githubusercontent.com/33755427/167302871-449ccb3d-3263-496c-8da6-3d8bcadb7901.png">

**Comment by QIN2DIM** [comment]
你這個配置文件就離譜。。 @lstone1228

**Comment by emptysuns** [comment]
> 在v2rayn里设置完路由模式也不能分流，直接全局代理。设置如下： "up": "20 Mbps", "up_mbps": 20, "down": "50 Mbps", "down_mbps": 50, "socks5": { "listen": "127.0.0.1:10808", "timeout": 300, "disable_udp": false }, "http": { "listen": "127.0.0.1:10809", "timeout": 300, "disable_udp": false }, "obfs": "fkwall", "server_name": "fkwall.eu.org", "insecure": false, "disable_mtu_discovery": false, "resolver": "8.8.8.8:53", "resolve_preference": "64" } 请问有办法解决吗？ <img alt="hy" width="1280" src="https://user-images.githubusercontent.com/33755427/167302871-449ccb3d-3263-496c-8da6-3d8bcadb7901.png">

https://github.com/emptysuns/Hi_Hysteria/issues/31#issuecomment-1083987589

用了hihy之后照着这个改。ps: 下个版本就完全使用v2n了，不用再自己改了

**Comment by lstone1228** [comment]
> > 在v2rayn里设置完路由模式也不能分流，直接全局代理。设置如下： "up": "20 Mbps", "up_mbps": 20, "down": "50 Mbps", "down_mbps": 50, "socks5": { "listen": "127.0.0.1:10808", "timeout": 300, "disable_udp": false }, "http": { "listen": "127.0.0.1:10809", "timeout": 300, "disable_udp": false }, "obfs": "fkwall", "server_name": "fkwall.eu.org", "insecure": false, "disable_mtu_discovery": false, "resolver": "8.8.8.8:53", "resolve_preference": "64" } 请问有办法解决吗？ <img alt="hy" width="1280" src="https://user-images.githubusercontent.com/33755427/167302871-449ccb3d-3263-496c-8da6-3d8bcadb7901.png">
> 
> [#31 (comment)](https://github.com/emptysuns/Hi_Hysteria/issues/31#issuecomment-1083987589)
> 
> 用了hihy之后照着这个改。ps: 下个版本就完全使用v2n了，不用再自己改了

可以了，谢谢

**Comment by lstone1228** [comment]
> 你這個配置文件就離譜。。 @lstone1228

哪里有问题吗？哪里需要该？

**Comment by QIN2DIM** [comment]
@lstone1228 

![image](https://user-images.githubusercontent.com/62018067/167374078-ec533b8e-0abe-4a30-ba7e-0a39fc9f6f09.png)

**Comment by lstone1228** [comment]
> 

谢谢，我改一下看看

**Comment by mytangyh** [comment]
2022-05-12T19:40:41+08:00 [ERRO] [error:timeout: no recent network activity] Failed to initialize client
2022-05-12T19:40:41+08:00 [INFO] [retry:1] [interval:3] Retrying...
2022-05-12T19:40:49+08:00 [ERRO] [error:timeout: no recent network activity] Failed to initialize client
2022-05-12T19:40:49+08:00 [INFO] [retry:2] [interval:3] Retrying...
2022-05-12T19:40:57+08:00 [ERRO] [error:timeout: no recent network activity] Failed to initialize client
2022-05-12T19:40:57+08:00 [INFO] [retry:3] [interval:3] Retrying...
2022-05-12T19:41:05+08:00 [ERRO] [error:timeout: no recent network activity] Failed to initialize client
2022-05-12T19:41:05+08:00 [FATA] Out of retries, exiting...

报这个错 不知道什么原因
