### ISSUE TITLE
hax 纯Ipv6 部署不成功

### ISSUE THREAD

**Issue by xxx975** [emptysuns/Hi_Hysteria#32]
协议类型: udp 
其余设置默认

root@16328hax:~# systemctl status hihy
● hihy.service - hysteria:Hello World!
     Loaded: loaded (/etc/systemd/system/hihy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-04-03 20:04:15 CEST; 1min 49s ago
    Process: 17751 ExecStart=/etc/hihy/bin/appS --log-level warn -c /etc/hihy/conf/hihyServer.js>
   Main PID: 17751 (code=exited, status=1/FAILURE)

Apr 03 20:04:14 16328hax.localdomain systemd[1]: Started hysteria:Hello World!.
Apr 03 20:04:15 16328hax.localdomain appS[17751]: 2022-04-03T20:04:15+02:00 [FATA] [error:h>
Apr 03 20:04:15 16328hax.localdomain systemd[1]: hihy.service: Main process exited, code=ex>
Apr 03 20:04:15 16328hax.localdomain systemd[1]: hihy.service: Failed with result 'exit-cod>

**Comment by emptysuns** [comment]
`/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server`
手动运行这个看看日志

**Comment by xxx975** [comment]
2022-04-04T07:30:01+02:00 [INFO] [config:{Listen::11334 Protocol:udp ACME:{Domains:[hax.metrk.xyz] Email:pekora@hax.metrk.xyz DisableHTTPChallenge:false DisableTLSALPNChallenge:false AltHTTPPort:0 AltTLSALPNPort:0} CertFile: KeyFile: UpMbps:0 DownMbps:0 DisableUDP:false ACL: MMDB: Obfs: Auth:{Mode:password Config:[97 34 10 32 32 32 32 125]} ALPN:h3 PrometheusListen: ReceiveWindowConn:62956 ReceiveWindowClient:251624 MaxConnClient:4096 DisableMTUDiscovery:false Resolver:8.8.8.8:53 ResolvePreference:46 SOCKS5Outbound:{Server: User: Password:}}] Server configuration loaded
2022-04-04T07:30:01+02:00 [INFO] Password authentication enabled
2022-04-04T07:30:01+02:00 [INFO] [addr::11334] Server up and running

**Comment by emptysuns** [comment]
`Server up and running`
 能运行啊，`systemctl start hihy`再试试

**Comment by xxx975** [comment]
![Lily_2022年04月04日16时48分49秒](https://user-images.githubusercontent.com/19317570/161508431-b8b4bfca-e9cf-4bd3-ac92-6e5898d3c0cd.png)
#

**Comment by emptysuns** [comment]
直接运行12，重新来一遍

**Comment by xxx975** [comment]
试过2次了 依旧

**Comment by emptysuns** [comment]
> 试过2次了 依旧

我在hax上试过没问题，我只能想到是你证书的问题，试试自签吧，或者装上wgcf v4再试试

**Comment by xxx975** [comment]
vps 重置了一下, 已经服务端已经成功配置, 并且已运行
![1](https://user-images.githubusercontent.com/19317570/161955086-4cc5e543-d3d5-48d5-8e46-a2c185eaed95.png)

本地config.json已复制到 x:/hihysteria_cmd_0.3a/conf/

运行: back_start.bat

windows10系统代理状态:
![2](https://user-images.githubusercontent.com/19317570/161955274-7b969cd1-4c32-490f-a698-91d734110962.png)

但还是访问不了外网.

---------------------------

唯一改动本地.config.json 中server字段如下
  server: [ipv6]:13433   # 生成的json是没有ip的, 我手动填了一下vps的ipv6/

最终config.json如下
![4](https://user-images.githubusercontent.com/19317570/161956137-46ab92f8-a92f-47ff-8758-30a6097ee2fb.png)

**Comment by emptysuns** [comment]
服务端是没问题的
但是你的客户端没有v6你用了隧道，记得把config.json里的地址改成你隧道的v4地址。

而且用wechat-video模式的话，如果还不行，请先用iperf测试你隧道能否正常通行udp

**Comment by xxx975** [comment]
换了另一个网络, 支持ipv6, 
服务端:
![s](https://user-images.githubusercontent.com/19317570/162022495-36b0a176-645f-4e00-ac06-fe653b3dccfb.png)


客户端:

![c](https://user-images.githubusercontent.com/19317570/162022505-081011df-a91e-4235-bb44-a2bad8f9bb80.png)

看起来好像是通的

**Comment by emptysuns** [comment]
那客户端连不上，提示什么？

**Comment by xxx975** [comment]
服务器hihy是运行的, 
本地没有找到log记录啊. 
![1](https://user-images.githubusercontent.com/19317570/162154055-9f4d954c-5363-4df6-a40f-a4ddb7c6156a.png)

**Comment by emptysuns** [comment]
> 服务器hihy是运行的, 本地没有找到log记录啊. ![1](https://user-images.githubusercontent.com/19317570/162154055-9f4d954c-5363-4df6-a40f-a4ddb7c6156a.png)

那个cmd的话，run.bat看看前台日志

**Comment by emptysuns** [comment]
> > 服务器hihy是运行的, 本地没有找到log记录啊. ![1](https://user-images.githubusercontent.com/19317570/162154055-9f4d954c-5363-4df6-a40f-a4ddb7c6156a.png)
> 
> 那个cmd的话，run.bat看看前台日志

如果你是用的centos的话，请查看firewalld是否放行了该udp端口
hihy只会放行iptables，这在ufw上测试时是可行的。
**实际上我并没有在centos测试过脚本是否能正常打开防火墙的hysteria端口**
如果你hysteria client提示`[error:timeout: no recent network activity] Failed to initialize client`
用如下命令尝试打开firewalld:
`firewall-cmd --permanent --add-port=你的端口/udp`

如果还是不行，这里我就建议更换落地机了，因为udp的无连接特性，很多人会用它攻击，导致你的某一段网络做了限制udp的策略。

**Comment by xxx975** [comment]
hax的系统版本是Ubuntu 20.04 LTS

防火墙ufw， 
没做过特别设置。
root@1632869925hax:~# ufw status verbose
Status: inactive

![1](https://user-images.githubusercontent.com/19317570/162257430-9b33fba7-7765-4e7e-948e-8ddb4be4c823.png)

**Comment by emptysuns** [comment]
> hax的系统版本是Ubuntu 20.04 LTS
> 
> 防火墙ufw， 没做过特别设置。 root@1632869925hax:~# ufw status verbose Status: inactive
> 
> ![1](https://user-images.githubusercontent.com/19317570/162257430-9b33fba7-7765-4e7e-948e-8ddb4be4c823.png)

你这很显然能用啊....

**Comment by xxx975** [comment]
我也看不出问题在哪。 本地，服务器防火墙，都没毛病啊，就是连不上。
![1](https://user-images.githubusercontent.com/19317570/162487090-f2b6e7e4-048a-4cfb-8316-659252364860.png)

**Comment by emptysuns** [comment]
可能是ipv6 only的问题，只有ipv6的落地还是装个wgcf吧
