### ISSUE TITLE
今天手贱更新失败

### ISSUE THREAD

**Issue by only4freedom** [emptysuns/Hi_Hysteria#33]
Wait,test config...

kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill                 -l [sigspec]
未知错误:请手动运行:/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server                 
查看错误日志,反馈到issue!

------
之前用的好好的,我今天手贱重新升级.结果用不了

**Comment by emptysuns** [comment]
未知报错就直接运行那个“完全重置”选项

**Comment by only4freedom** [comment]
已经完全重置2次,甚至卸载重装了...
几天之前的脚本完全没问题... 
最新的脚本不行啊...

**Comment by only4freedom** [comment]
重装系统后一台VPS后,好了... 我再试试另外一台.

**Comment by emptysuns** [comment]
未知错误:请手动运行:/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server

如果还不行，打印hysteria日志贴到这里看看。
