### ISSUE TITLE
Error[OS Message]:s390x

### ISSUE THREAD

**Issue by handuck1984** [emptysuns/Hi_Hysteria#34]
Error[OS Message]:s390x

**Comment by emptysuns** [comment]
这么多人喜欢嫖ibm？
正好hy给了这个架构，下个版本加上，你如果迫切需要就自己从它release自己拉下来加上

**Comment by emptysuns** [comment]
[0.3.5](https://github.com/emptysuns/Hi_Hysteria/commit/bdd03bf62c469793f1aaa751d9f1537ee8f9cc3f) 兼容了此架构。

不过我在linuxONE提供的测试机上，能通过hihy能成功运行server，但在我本地网络测试client确怎么也连不上它，反而将client放到此server上却能成功连接，说明配置是没问题的.....

确保防火墙已经打开了，不知道哪里的问题，我猜测应该是linuxONE的外部防火墙会拦截一切未知流量？
