### ISSUE TITLE
请教：在服务器端该如何设置分流

### ISSUE THREAD

**Issue by yang12me** [emptysuns/Hi_Hysteria#35]
我有个VPS，用谷歌搜索时会跳出人机验证。

我想把谷歌流量分流到其他服务器。该如何设置？谢谢你。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/16

这个issue也提出来了，利用套娃到xray可以按照域名分流到warp。不过这样做有一个问题就是，需要再额外的再起一个xray进程和一个warp进程比较麻烦，而且在hysteria`1.0.2`以及之前的版本s5入一直有一个解析域名的问题来的，所以鸽了。
我这里建议先你使用https://github.com/fscarmen/warp的解决方案作为代替，我想等着hysteria支持geoip时再做打算。
