### ISSUE TITLE
rn的小鸡不能使用吗

### ISSUE THREAD

**Issue by codersyn** [emptysuns/Hi_Hysteria#37]
看过程是东西没有下载完全吗，首先是No packages marked for update，然后又是*netfilter-persistent/Error: Nothing to do
请选择:1
Ready to install.
 

Update.wait... 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: sjc.edge.kernel.org
 * extras: mirrors.raystedman.org
 * updates: mirrors.sonic.net
No packages marked for update

Done.
Install wget curl netfilter-persistent lsof 
*wget 
Installed.Ignore. 
*curl 
Installed.Ignore. 
*netfilter-persistent 
Error: Nothing to do
*lsof 
Installed.Ignore. 

Done. 
The Latest hysteria version:v1.0.3 
Download...

Download completed. 
开始配置: 
请输入您的域名(不输入回车,则默认自签wechat.com证书,不推荐):

**Comment by emptysuns** [comment]
`netfilter-persistent`本身是为了保存iptables规则，你如果没有防火墙就无视，我猜你的系统太老了，镜像过时了。
 手动换换apt/yum源吧

**Comment by codersyn** [comment]
![1650265594(1)](https://user-images.githubusercontent.com/22024145/163770099-916e8e6f-2f50-4022-90c2-545ecd5e7f16.jpg)
我换了阿里的源再试了下，还是连接不上，不知道哪里的问题。

**Comment by emptysuns** [comment]
> ![1650265594(1)](https://user-images.githubusercontent.com/22024145/163770099-916e8e6f-2f50-4022-90c2-545ecd5e7f16.jpg) 我换了阿里的源再试了下，还是连接不上，不知道哪里的问题。

https://github.com/emptysuns/Hi_Hysteria/blob/main/md/protocol.md

请**仔细阅读**一下

**Comment by codersyn** [comment]
![image](https://user-images.githubusercontent.com/22024145/163774496-b0526b1e-ad68-497d-81e6-d769423ec172.png)
换成udp也不行

**Comment by emptysuns** [comment]
不知道你说的这个“rn”是不是有面板防火墙，你先试试用iperf测试一下udp是不是通的吧

或者恭喜你中奖了: https://github.com/emptysuns/Hi_Hysteria/issues/9

**Comment by codersyn** [comment]
![image](https://user-images.githubusercontent.com/22024145/163781417-11a1f0fe-90ea-4e00-9af2-1b8da2c82954.png)
我没用过iperf，不知道是不是这样，如果是，那结果似乎是udp被阻断了？

**Comment by emptysuns** [comment]
> ![image](https://user-images.githubusercontent.com/22024145/163781417-11a1f0fe-90ea-4e00-9af2-1b8da2c82954.png) 我没用过iperf，不知道是不是这样，如果是，那结果似乎是udp被阻断了？

没办法，要么使用faketcp，要么放弃

**Comment by codersyn** [comment]
我发工单问客服，客服说他们不会阻止任何vps的端口，所以还是我操作出问题了吗，但是换个vps一步到位啥问题没有，就racknerd的出问题。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/9
