### ISSUE TITLE
如何和NGINX兼容？

### ISSUE THREAD

**Issue by lukemin** [emptysuns/Hi_Hysteria#38]
如何和NGINX兼容？ 80和 443被占用了，申请不了证书。

**Comment by emptysuns** [comment]
自签导入ca吧，共存不了

**Comment by lukemin** [comment]
要是在安装的过程可以填写自己申请的ca就好了。

**Comment by emptysuns** [comment]
> 要是在安装的过程可以填写自己申请的ca就好了。

不必要，你自己先自签，然后修改配置就行
