### ISSUE TITLE
用着还行就是acme签不下证书

### ISSUE THREAD

**Issue by six6pear** [emptysuns/Hi_Hysteria#4]
用着还行就是acme签不下证书

**Comment by emptysuns** [comment]
hysteria内置的ACME必须得用80/443端口进行challenge，不支持dns，请保证这两个端口的tcp的联通性。

如果无法访问，可以自行上传已经签发的证书，修改`/etc/hysteria/config.json`,删掉acme选项，加入如下：

```
"cert": "/home/ubuntu/my_cert.crt",
  "key": "/home/ubuntu/my_key.crt"
```

单做代理的话，没必要非得要签发的证书，自签的话导入CA设置`"insecure": false`，是一样的安全，我只是为了方便写的自签是“允许不安全链接”，其实这样不好，**可能**会被中间人攻击，但是这种情况微乎其微，自用的话无所谓的。
