### ISSUE TITLE
老大，请问openwrt下最新passwall运行hysteria的一些疑问

### ISSUE THREAD

**Issue by sontjer** [emptysuns/Hi_Hysteria#40]
1. passwall quic协议无效，都是无法连接，换faketcp则正常，会是isp的问题吗？
2. 能否有工具可以让中转机转发faketcp的流量？使用gost转发tcp/udp流量无效。
感谢！

**Comment by emptysuns** [comment]
1、passwall 默认检测用的是tcping，你要是udp协议肯定检测不了，取消勾选那个选项就行，显示超时但是能用

2、gost能转发，直接写`gost -L=tcp://:2222/192.168.1.1:22` 或者 ``gost -L=udp://:2222/192.168.1.1:22``(这里不写quic)
