### ISSUE TITLE
这个和kcptun在同线路下的速度区别大么？有测试嘛

### ISSUE THREAD

**Issue by zhezhe168** [emptysuns/Hi_Hysteria#42]
大佬，比较好的一个项目，可以省去使用第三方客户端组合的繁琐
有几个问题“
quic暴力发包，感觉和kcptun的udp发包差不多，区别在于协议不同，kcptun如果合理设置带宽，在没有运营商干扰的情况下，可以有效利用本地带宽的60%——70%，Hysteria的带宽利用率大概是多少，不知道作者有测试过么
另外，youtube测试图的drop不一定准确，因为如果本地显卡和CPU烂的话，跑4K的frame会drop掉很多

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/15

**Comment by zhezhe168** [comment]
嗯我看过这个，如果是协商重传机制的话，只要本地带宽小于vps带宽，那理论上会比kcptun稍微差些，所以想要个测试图对比下
