### ISSUE TITLE
新的断流报错问题

### ISSUE THREAD

**Issue by zhezhe168** [emptysuns/Hi_Hysteria#43]
测试了下，确实比kcptun在同等带宽下速度快一些，但断流后就连不上了
![image](https://user-images.githubusercontent.com/10943213/163954910-beacd353-17c5-4b1c-99f7-4cd855c91b56.png)

**Comment by emptysuns** [comment]
timeout？你这也不是用编译好的run的，我觉得你需要移步到［hysteria］（https://github.com/HyNetwork/hysteria/issues）

**Comment by zhezhe168** [comment]
我去看下，这个hysteria出来挺久了一直没玩过
openwrt哪个内核开始支持hysteria?
