### ISSUE TITLE
大佬为啥 提示申请证书失败

### ISSUE THREAD

**Issue by kksxsyj** [emptysuns/Hi_Hysteria#45]
按照步骤我输入域名后，没有出现提示域名绑定IP的提示，直接到端口设置了，输入完配置最后提示申请证书失败。端口还有IP解析都是没有问题的，我之前安装xui申请证书都是可以成功的，这次换的别的二级域名就出现了这种情况。

**Comment by languang666** [comment]
我也是

**Comment by emptysuns** [comment]
方便提供什么系统？是否保证80/443能被访问？

**Comment by crosspacific** [comment]
我觉得最好能提供一个选项，手动上传证书。先在服务器上传证书，然后安装的时候输入地址。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/issues/50
