### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sunhq7** [emptysuns/Hi_Hysteria#5]
大佬可以帮看下这个是啥问题吗
![image](https://user-images.githubusercontent.com/72604212/146733518-63afea6a-77d1-41a2-bbde-b334ac92eaf7.png)

**Comment by emptysuns** [comment]
ACME挑战失败，拿不到证书，确定80和443端口是不是放行的？

**Comment by emptysuns** [comment]
#4
