### ISSUE TITLE
在脚本中增加一个手动输入证书地址的功能

### ISSUE THREAD

**Issue by sdshdv** [emptysuns/Hi_Hysteria#50]
使用Nat机或者ipv6 only的机器会遇到无法自动申请证书的情况，这个时候只能通过手动用acme的DNS验证方式申请证书，然而这个脚本只要申请失败直接把配置文件都删了，想在配置文件里改证书地址都做不到，所以希望可以在申请的时候提供类似以下的选项：

1.自动申请证书（需要80/443开放）
2.自定义已存在的其他路径的证书

选2后:

请输入证书cert文件路径(需使用fullchain.cer): 
请输入证书key文件路径: 
请输入证书域名:

**Comment by sdshdv** [comment]
另外关于证书文件必须使用fullchain.cer的提醒，如果不使用fullchain证书会出现电脑可用手机不可用的现象

**Comment by emptysuns** [comment]
[0.3.6](https://github.com/emptysuns/Hi_Hysteria/commit/6f8f0e2a32873783af480f19b3f809f6b16157fd)
