### ISSUE TITLE
用hihy无法使用，连接被拒绝

### ISSUE THREAD

**Issue by Tylxer** [emptysuns/Hi_Hysteria#51]
用hihy启动的话，能连接但是无法使用。
但是用/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server这个命令启动就能正常使用
错误代码如下:
 [INFO] [addr:127.0.0.1:8889] SOCKS5 server up and running
2022-04-21T16:33:05+08:00 [INFO] [addr:127.0.0.1:8888] HTTP server up and running
2022-04-21T16:33:08+08:00 [DEBU] [src:127.0.0.1:60953] [dst:mtalk.google.com:5228] [action:Proxy] SOCKS5 TCP request
2022-04-21T16:33:08+08:00 [INFO] [src:127.0.0.1:60953] [dst:mtalk.google.com:5228] [error:connection rejected: dial tcp 172.253.122.188:5228: connect: permission denied] SOCKS5 TCP error

**Comment by emptysuns** [comment]
本质上hihy只是用`systemd`用来创建守护进程的，和你使用的`/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server`启动的区别，只在关掉了server端的日志，我觉得是有其他问题

**Comment by emptysuns** [comment]
本质上hihy只是用`systemd`用来创建守护进程的，和你使用的`/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server`启动的区别，只在关掉了server端的日志，我觉得是有其他问题

**Comment by emptysuns** [comment]
怪事，你用那个`完全重置所有`的选项重新来一遍呢?

**Comment by luckykeeper** [comment]
我今天重装了下系统，也遇到了这个问题
系统是 RockyLinux9 ，安装完成后正常使用，然而重启一下之后就寄了，和 Tylxer 一样的情况，试了 `/etc/hihy/bin/appS --log-level info -c /etc/hihy/conf/hihyServer.json server` 直接启动是没有问题的，用 systemd 就不行
尝试修改了下 hihy 的 systemd 文件，[Services] 指定 root 用户也不行
最后发现关闭 selinux 即可，所以是 selinux 的锅
@Tylxer 你可以试试关闭 selinux ，参考：

查看当前 selinux 状态，如果不是 Disabled 就是开着呢
```shell
getenforce
```

关闭 selinux （命令敲完之后需要你 reboot 下机器）
```shell
setenforce 0
sed -i "s/^SELINUX=.*$/SELINUX=disabled/" /etc/selinux/config
```

希望能够帮助到你 Tylxer
