### ISSUE TITLE
faketcp is not supported on this platform

### ISSUE THREAD

**Issue by GeXyu** [emptysuns/Hi_Hysteria#52]
[ERRO] [error:faketcp is not supported on this platform] Failed to initialize client

**Comment by GeXyu** [comment]
怎么解决呢 windows 10

**Comment by sdshdv** [comment]
只有linux系统且获得root权限的情况下可以使用faketcp，Windows，mac，ios，全部无法使用faketcp的

**Comment by GeXyu** [comment]
Thanks
