### ISSUE TITLE
申请证书失败!请查看服务器提供的面板防火墙是否开启(TCP:80,443)

### ISSUE THREAD

**Issue by liuwleo** [emptysuns/Hi_Hysteria#53]
确认过端口打开，同时域名解析正常。VPS(运营商：Racknerd)也正常工作。安装过程中有如下错误提示信息：

执行配置...
/usr/bin/hihy: line 597: iptables: command not found
/usr/bin/hihy: line 599: iptables: command not found
IPTABLES OPEN: tcp/80
/usr/bin/hihy: line 597: iptables: command not found
/usr/bin/hihy: line 599: iptables: command not found

请帮忙看看是什么问题。谢谢！

**Comment by emptysuns** [comment]
没有安装成功netfilter-persistent?
如果不带防火墙无视就行...估计是你的镜像里默认带的yum/apt源太老了
下个版本再改，使用系统默认防火墙吧，不强制安netfilter-persistent

**Comment by liuwleo** [comment]
> 没有安装成功netfilter-persistent?
> 
> 如果不带防火墙无视就行...估计是你的镜像里默认带的yum/apt源太老了
> 
> 下个版本再改，使用系统默认防火墙吧，不强制安netfilter-persistent

我刚尝试在另外一个VPS里安装，成功。两个VPS的系统不一样，这个就讲究么？另外源太老了，能有什么办法么？谢谢

**Comment by emptysuns** [comment]
> > 没有安装成功netfilter-persistent?
> > 如果不带防火墙无视就行...估计是你的镜像里默认带的yum/apt源太老了
> > 下个版本再改，使用系统默认防火墙吧，不强制安netfilter-persistent
> 
> 我刚尝试在另外一个VPS里安装，成功。两个VPS的系统不一样，这个就讲究么？另外源太老了，能有什么办法么？谢谢

系统的版本早就不被支持了，要么通过dd成lts版本，要么等hihy下个版本修复，以上都不想的话，那就自己打开防火墙起一个hysteria进程

**Comment by liuwleo** [comment]
目前不成功的是ubuntu20.04，能否细说一下如何dd到lts版本么？想尝试一下。谢谢。

**Comment by emptysuns** [comment]
先自签吧，信任证书后一样安全

**Comment by emptysuns** [comment]
[0.3.6](https://github.com/emptysuns/Hi_Hysteria/commit/6f8f0e2a32873783af480f19b3f809f6b16157fd)
