### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by Mochongli** [emptysuns/Hi_Hysteria#54]
![image](https://user-images.githubusercontent.com/36944889/164912794-6be06225-dac1-44cc-aa24-6a4ee9fb0a8b.png)

**Comment by emptysuns** [comment]
给出手动运行的日志吧

**Comment by Mochongli** [comment]
我把Centos7.9换成Ubuntu20就行了

**Comment by Mochongli** [comment]
> 给出手动运行的日志吧


我把Centos7.9换成Ubuntu20就行了

**Comment by emptysuns** [comment]
适配有问题吗？下次更新，我再查查兼容问题
