### ISSUE TITLE
如果有多个公网IP似乎不能识别

### ISSUE THREAD

**Issue by Mochongli** [emptysuns/Hi_Hysteria#55]
![image](https://user-images.githubusercontent.com/36944889/164998997-06cff67e-b180-409f-8969-9ebc43a3af6a.png)

**Comment by Mochongli** [comment]
![image](https://user-images.githubusercontent.com/36944889/164999035-ddc8362c-709a-4227-bb93-d3b4dc8e51af.png)

**Comment by Mochongli** [comment]
2a07:5740:600::8965:8718
2a07:5740:600::1a04:c1e8
2a07:5740:600::f7c4:c9e
2a07:5740:600::7c82:3f9f
2a07:5740:600::582d:af4e

**Comment by emptysuns** [comment]
会识别，这是你的问题

**Comment by Mochongli** [comment]
> 会识别，这是你的问题

大概是哪些问题
