### ISSUE TITLE
sagernet客户端该如何填写参数

### ISSUE THREAD

**Issue by sjnhnp** [emptysuns/Hi_Hysteria#6]
请问用你的脚本安装完后，
使用Android客户端 sagernet 不知道如何填写参数
（已安装hysteria的插件）

**Comment by emptysuns** [comment]
照着生成的config.json填写就行了

记得设置plugin可以被其他应用启动

**Comment by sjnhnp** [comment]
哎 按着填写 有些参数不知道该对应哪个

所以一直未能成功
