### ISSUE TITLE
请问3种模式怎么快速切换，不用重新跑脚本

### ISSUE THREAD

**Issue by cmazfuture** [emptysuns/Hi_Hysteria#60]
请问udp和wechat-video这2个模式修改哪里的配置文件切换？不修改其他参数，比如密码那些。也不用重新跑脚本配置一次。。
/root  和/etc/hihy目录 里都有config.json配置文件，不知道哪个是有效的。

如果能再脚本里面再增加一个选项就好了。只对3种模式进行切换并且重启Hysteria（如果需要重启才生效的话），其他那些参数就不用重新配置一次了

**Comment by emptysuns** [comment]
`/etc/hihy/conf`里，下次更新可以考虑加上切换模式的功能

**Comment by cmazfuture** [comment]
OJBK。收到，再请问下。证书的话，客户端怎么引用它呢？服务端已经配置好了的。 openwrt的passwall里的Hysteria没有证书选项。V2RAYN也没看到。

**Comment by emptysuns** [comment]
passwall不支持导入CA，只能允许不安全
v2n需要在目录创建一个文件夹`ca`，把签好的放到这个文件夹里
