### ISSUE TITLE
想问一下，为什么同样的机子，一台hihy内存占用多，其他的就很少呢？

### ISSUE THREAD

**Issue by eightsheep67** [emptysuns/Hi_Hysteria#62]
我甲骨文首尔、东京、圣何塞各有两个机子，每一台机器的hihy配置都一模一样。就东京其中一台，通过htop查看，hihy内存占用很高，一直就是保持在16%-20%之间。其他的机器hihy内存也就2-4%之间。

然后我以为时我之前弄了其他的不干净了，重新弄了个实例，干净安装，只apt upgrade了，装了hihy和探针。还是一样。

这个内存占用和什么有关系呢？丢包吗？

**Comment by emptysuns** [comment]
hysteria的问题，长期运行内存会逐渐累积，脚本安装时会自动添加一个定时规则，每天重启hysteria。
应该是你的定时任务被你删掉了，重新安装一下
