### ISSUE TITLE
你的博客的动画效果让浏览器太卡了

### ISSUE THREAD

**Issue by yanyuechuixue** [emptysuns/Hi_Hysteria#63]
https://blog.imoeq.com/hi_hysteria/
博客的动态效果太消耗资源了

**Comment by emptysuns** [comment]
Σ（ ° △ °|||）︴
感谢带佬关心，应该是你的cpu稍微脱离时代了，对这些资源处理的比较慢～
这个问题之前就注意到了，我也吃博客AD，自娱自乐觉得好看就完了（=￣ω￣=）

如果你要关注hihy请关注这个仓库就行了
