### ISSUE TITLE
请问，支持CDN吗？另外，使用使用ACME申请证书一直失败

### ISSUE THREAD

**Issue by cn-404-not-found** [emptysuns/Hi_Hysteria#64]
想隐藏真实IP，不知道这个能否支持CDN

另外使用使用ACME申请证书一直失败，80和443端口都是打开的，也按要求关闭了CDN，解析是正常的，在哪里可以看到安装日志呢？

**Comment by emptysuns** [comment]
不能过cdn，quic是经过魔改后的，no way

证书下不来是443/80被占用之类的问题，api访问不到你的主机验证不了，建议自签导入ca/上传证书的方式吧同样安全
