### ISSUE TITLE
shadowrocket无法使用

### ISSUE THREAD

**Issue by sjnhnp** [emptysuns/Hi_Hysteria#7]
0.2.6脚本，自签给wechat.com
sagernet可以正常使用，
ios 的 shadowrocket，「允许不安全连接」无论是否开启都无法使用，填写了peer：wechat.com，也没用。

**Comment by emptysuns** [comment]
`sagernet可以正常使用`
你该考虑一下你的shadowrocket是不是写错了
方便提供详细的配置截图吗

**Comment by sjnhnp** [comment]
没有写错，因为我是从你的0.2.5脚本升级上去的，
除了你更改的自签，其它的参数我都保持不变，而且sagernet，我也只是增加了 自签方面的参数。
