### ISSUE TITLE
能连上YouTube，但是看不了视频，VPS端返回tcp error,tcp eof

### ISSUE THREAD

**Issue by giodano0718** [emptysuns/Hi_Hysteria#73]
![youtube](https://user-images.githubusercontent.com/88591600/168576728-b844a434-dfbc-4bd3-a9c9-a367b5dbc4be.png)
 这个问题怎么破？

VPS端返回tcp request,tcp error,tcp eof，udp request,udp error,udp eof

**Comment by giodano0718** [comment]
有什么办法验证你说的这个问题吗？

**Comment by emptysuns** [comment]
把`/etc/hihy/conf/hihyServer.conf`里的acl那一项删掉，重启hysteria看看还error吗

**Comment by idragonet** [comment]
我的Oracle机器看YouTube正常。

**Comment by emptysuns** [comment]
> 有解决了吗？我也是同样的问题

https://github.com/emptysuns/Hi_Hysteria/issues/73#issuecomment-1127815658

试试这个呢？

**Comment by giodano0718** [comment]
这个问题解决了，但是很别扭，在软路由的防火墙规则里面放行
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
这么做就会导致我的ADGuardHome的客户端只有192.168.0.1，看不到局域网内的其他设备

请教各位大神，这个有更好的解决办法吗？我搞不懂里面的原理。

**Comment by yasuis** [comment]
我也是这个问题 但是奈飞和迪斯尼都正常 系统是ros+openwrt 软件ssrp 排查下来是ros的设置问题
