### ISSUE TITLE
进入部分网站时提示：重定向次数过多

### ISSUE THREAD

**Issue by CarmelShen** [emptysuns/Hi_Hysteria#77]
设置完成后，能顺利看YT1080P，但在进入部分网站时提示：

当前无法使用此页面
重定向次数过多。
若要解决此问题，请尝试[清除 Cookie]
ERR_TOO_MANY_REDIRECTS

请问有遇到过这个问题么？

**Comment by emptysuns** [comment]
这个是你**部分网站**的问题和hysteria无关
