### ISSUE TITLE
OS报错？

### ISSUE THREAD

**Issue by artmscn** [emptysuns/Hi_Hysteria#78]
Done.
Install wget curl lsof 
*wget 
Installed.Ignore. 
*curl 
Installed.Ignore. 
*lsof 
Installed.Ignore. 

Done. 
The Latest hysteria version:v1.0.4 
Download...
Error[OS Message]:i686
Please open a issue to https://github.com/emptysuns/Hi_Hysteria ! 

debian 9.
请问这是什么情况？？求解

**Comment by emptysuns** [comment]
`i686`你这架构目前不受hihy支持，这个u是从哪里淘来的，这也太落后于时代了吧？
等我下个次更新兼容这个吧

**Comment by artmscn** [comment]
> `i686`你这架构目前不受hihy支持，这个u是从哪里淘来的，这也太落后于时代了吧？ 等我下次更新兼容这个吧

哈哈，是超售王搬瓦工的vps.. 谢谢大佬！

**Comment by QIN2DIM** [comment]
换个机房呗…

**Comment by artmscn** [comment]
> 换个机房呗…

用vultr日本的试了下 似乎可以 正在研究。

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/86b08616d2714d129797ded0487161cae69c6a7f
