### ISSUE TITLE
关于 ping ，upload 和 download 值的自动生成

### ISSUE THREAD

**Issue by fscarmen** [emptysuns/Hi_Hysteria#79]
我想法是能否参照 vps body-check 脚本的数据来自动换算 upload 和 download 值，
关于 ping 值，则不是让用户填入数字，因为可能大多数用户并不清楚，而让用户输入本地的 IP 值 ，我们通过 vps 端 ping 本地而换算 ping 值
当然可以加入自动 检测/手动 输入选项，甚至在传参里处理。
我想这样更显脚本的“智能”。

**Comment by QIN2DIM** [comment]
这种“智能”是没必要的。我并不觉得 ping 都不会用的人会知道自己的 IP地址，搞不好会填个 192.168.0.1 或者 127.0.0.1 笑死。其次是网络状态取自木桶效应，vps的连接速度或者向国内几个主要节点的下行速率一般是远高于用户的本地带宽的。

**Comment by emptysuns** [comment]
**感谢给出的建议～**

1、关于这个upload和download速度设置，我觉得单靠脚本是很难做到“智能”的，因为对于client来说，在server没有限速的情况下，对udp的速度限制**只有**这两个参数，这意味着你可以设置的无限大，但这样会更容易碰到isp的udp墙，而且制约速度不仅仅只有vps的带宽大小，同样cpu的性能也是一个关键的因素（quic通病，hysteria就是fork的quic‘-go），而cpu的性能也取决于商家的**超售**多少，这就导致很难做一个量化的得到最佳带宽设置，这在调整hysteria参数时是很困难做到的。
而且用户能不断尝试安装，寻找属于自己本地合适的带宽，这是目前我认为的最佳解决办法，如果有其他的方法，欢迎提出。

2、接着ping的问题，这个让server去ping的思路很实用，但是有一个很重要的问题——**用户必须得具有公网ip**。
我相信使用hihy的绝大部分人是国内的，三大运营商都不会默认给用户分配公网ip，都是分配的被NAT后的共享ip（更有甚者移动对用户的流量也进行了透明代理）这就意味着对这些大部分的用户这种办法是行不通的，没办法从server主动获得到client的延迟，我觉得这种实现起来也有难度，所以选择让用户输入
