### ISSUE TITLE
Hysteria是不能用了吗？

### ISSUE THREAD

**Issue by Nebula-Yong** [emptysuns/Hi_Hysteria#8]
我试过官网的配置和你的脚本，客户端的反馈都是一样的，究竟是哪里出了问题？
![image](https://user-images.githubusercontent.com/63303837/150281954-2c2a81df-3e4c-499a-9c4b-0cce100c8247.png)
服务器状态
![image](https://user-images.githubusercontent.com/63303837/150295271-108029ef-f1f2-45f5-9d3e-280a583acd5e.png)

**Comment by Nebula-Yong** [comment]
vultr的服务器不存在防火墙问题，我都快折腾哭了，就想体验一下Hyperia体验怎么样，那位好心人帮帮我

**Comment by emptysuns** [comment]
> hysteria v0.9.1 开始支持faketcp，将hysteria的UDP传输过程伪装成TCP，可以躲过运营商和“比较专业”的IDC服务商的**QoS设备的对UDP的限速、阻断**。

vultr应该在机房有安全设备限制udp了，其他如此的还有DO，使用faketcp就行了

**Comment by Nebula-Yong** [comment]
It doesn't working as well.

**Comment by Nebula-Yong** [comment]
你自己还在用hyperia吗，还是你仅仅是之前试过

**Comment by emptysuns** [comment]
我肯定在用，而且全部都是hys
你的问题是vultr这家idc在搞事，这问题我也在digitaloceans碰到过，如果不理解厂商为什么这样做，请查一下udp flood攻击的影响。

**Comment by Nebula-Yong** [comment]
I am tired~ I have spended a whold day in it.It has made me hyperia. Thank you for your help heartly.Would you mind tell me which IDC do you used? I wanna try next time.Or tell me which vps provider can let me try Hyperia.

**Comment by emptysuns** [comment]
All I know so far is that do and vultr restrict hysteria, and this behavior is incomprehensible. 
Except these two should be fine.
