### ISSUE TITLE
建议删除默认配置中的 "disable_mtu_discovery": true 参数

### ISSUE THREAD

**Issue by Aspreadfire** [emptysuns/Hi_Hysteria#82]
经测试该配置在服务端有可能导致MTU被限制在1243KB，导致无法接受一些较大的包，典型的如游戏连接包。
出现该现象的系统版本为ubuntu20.04，VPS为oracle cloud提供。
"disable_mtu_discovery": true 参数出现在win10客户端上似乎无影响。

不知道该参数最早被添加进json是为了实现什么功能？

**Comment by emptysuns** [comment]
因为在长时间测试过程中，打开mtu探测会在一些线路不怎么好有丢包的线路中很频繁的断流，为了这些用户，选择关闭了mtu主动探测选择使用固定值。
不知道是不是quic-go带的bug，你可以关闭后找个高延迟/高丢包的环境试一试，欢迎反馈

**Comment by Aspreadfire** [comment]
> 因为在长时间测试过程中，打开mtu探测会在一些线路不怎么好有丢包的线路中很频繁的断流，为了这些用户，选择关闭了mtu主动探测选择使用固定值。 不知道是不是quic-go带的bug，你可以关闭后找个高延迟/高丢包的环境试一试，欢迎反馈

好的，感谢您的回复，我也奇怪为什么MTU会被锁定在一个不常用的固定值上。目前来说我自己的线路高峰丢包率大概在10%左右，关闭mtu主动探测并没有检测到断流现象（打游戏感知很明显）。
另外有一个猜测，很多VPS厂商默认的MTU是9000的巨型帧，关闭后导致的断流会不会与此有关。

**Comment by emptysuns** [comment]
不知道你延迟如何，我是丢包多+高延迟体感比较明显
在开启mtu探测情况时，如果是这种9000的巨型帧，网卡再设置一个很较低的发射速率，确实会导致发送帧的时间增长，对这种无连接的udp，体现出的就是断流吧...

那先根据你的需要手动开启mtu探测，我再观望看看，感谢建议～
