### ISSUE TITLE
搭建后socks5代理无法连接

### ISSUE THREAD

**Issue by slcf2003** [emptysuns/Hi_Hysteria#83]
你好，

我是根据教程在v2rayN里添加了节点，我习惯使用socks5，但是启动后一直提示TCP EOF，还有`error:connection rejected: dial tcp 154.85.102.32:443: connect: connection refused] [0mSOCKS5 TCP error`， 以及类似的i/o timeout和connect: network is unreachable。无法上网，火狐提示找不到此网站，但是切换到http代理就没有问题。我在v2rayN中使用vless+xray的节点时，socks5代理就没有问题。

**Comment by emptysuns** [comment]
我这里没问题...
