### ISSUE TITLE
客户端可以随意配置问题

### ISSUE THREAD

**Issue by teddy150420** [emptysuns/Hi_Hysteria#87]
搭建选择udp协议，客户端设置为wechat.udp都可以用，还有两个接收窗口空白或者随意设置也可以，完全跟服务器配置不同不影响使用，有点蒙😃

**Comment by teddy150420** [comment]
还有域名，也能随意设置，

**Comment by emptysuns** [comment]
域名问题是你关闭证书校验。
buffer设置客户端是客户端，服务器是服务器这俩没关系，唯一有关系是速度问题。
udp和wechat-video可以混用。
