### ISSUE TITLE
woiden安装错误

### ISSUE THREAD

**Issue by royaldeng2023** [emptysuns/Hi_Hysteria#88]
未知错误:请手动运行:/etc/hihy/bin/appS -c /etc/hihy/conf/hihyServer.json server

**Comment by emptysuns** [comment]
所以呢？日志呢？

**Comment by zyyysxd** [comment]
关闭apache2了么

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/86b08616d2714d129797ded0487161cae69c6a7f
