### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by imgblz** [emptysuns/Hi_Hysteria#89]
日志
[FATA] [file:/etc/hihy/conf/hihyServer.json] [error:json: cannot unmarshal object into Go value of type []uint8] Failed to parse client configuration

**Comment by emptysuns** [comment]
编码不对吧，你直接下载server生成的那个config.json，别copy了

**Comment by emptysuns** [comment]
https://github.com/emptysuns/Hi_Hysteria/commit/86b08616d2714d129797ded0487161cae69c6a7f
