### ISSUE TITLE
3.8.1的ACL访问国内网站有问题

### ISSUE THREAD

**Issue by dududuK** [emptysuns/Hi_Hysteria#92]
3.8.1的ACL访问国内网站有问题

**Comment by kinfaicheung** [comment]
会提示无法访问此网站
![633ff0962790911f8481326dab8ce7f](https://user-images.githubusercontent.com/53850896/177728588-d6fa1c84-e601-47fc-aac8-fc520d4a56dd.png)

**Comment by dududuK** [comment]
你可以在V2RAY上设置2个PAC规则，一个白名单模式，一个黑名单模式。然后测试打开国内网站。
