### ISSUE TITLE
ipv6有关问题

### ISSUE THREAD

**Issue by liuxyon** [emptysuns/Hi_Hysteria#96]
我已经安装测试, 
1.当优先ipv6时候,ipv6可以使用.但是ipv4访问很多网站打不开. 例如ipleak.net bgp.he.net 也就是ipv6和ipv4无法同时正常使用. 当ipv4优先时候,ipv6无法使用.
2. 如果我要给每个客户端分配固定公网ipv6地址,如何实现配置？
3. dns 不支持ipv6 dns?
4. 初次使用,顺带问个问题,如何给每个客户进行认证？还是一个配置文件全部用户都可以使用？如何区分认证用户？
5. 如果使用自签名证书,segernet无法使用.

**Comment by emptysuns** [comment]
1. 那个选项是调整server解析v4/v6优先级的，不存在无法使用的问题，怀疑是你网络环境问题，具体内容不知道
2. 你直接修改client的config，将地址换成你想要分配的ipv6地址，server监听的是端口，不是ip。例如`[fe80:xxxxxx:1]:123456`,`[fe80:xxxxxx:2]:123456`
3. hihy, server使用8.8.8.8，client使用119.29.29.29，按理来说支持同时解析域名的双栈ip
4. 区分认证用户需要提供不同密钥，修改server config`auth_str`值为多个密码`['pass1', 'pass0', 'pass2', ........]`
5. sagernet 目前不支持指定CA，需要开启允许不安全连接选项

**Comment by liuxyon** [comment]
“区分认证用户需要提供不同密钥，修改server config auth_str值”

意思是修改成这样对吗？
`"auth": {
    "mode": "password",
    "config": {
    "password": "xiyu", "xiyu2"
    }
},
`

**Comment by liuxyon** [comment]
“那个选项是调整server解析v4/v6优先级的，不存在无法使用的问题，怀疑是你网络环境问题，具体内容不知道”

服务器本身ipv6工作者,只是转换为Ipv6优先后，客户端无法访问ipv6. ipv4优先模式下，ipv6访问正常. 我不知道你调整了哪个参数？

**Comment by emptysuns** [comment]
> “那个选项是调整server解析v4/v6优先级的，不存在无法使用的问题，怀疑是你网络环境问题，具体内容不知道”
> 
> 服务器本身ipv6工作者,只是转换为Ipv6优先后，客户端无法访问ipv6. ipv4优先模式下，ipv6访问正常. 我不知道你调整了哪个参数？

什么也没有调整，只是把hy的这个选项修改了

**Comment by liuxyon** [comment]
“你直接修改client的config，将地址换成你想要分配的ipv6地址，server监听的是端口，不是ip。例如[fe80:xxxxxx:1]:123456,[fe80:xxxxxx:2]:123456”

这是目前客户端配置文件：在哪个参数下分配固定公网ipv6地址？意思是每个客户有独立公网ip,而不是Nat形式.
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 114.114.114.114
    - 223.5.5.5

proxies:
  - name: "Hys-b.xi.org"
    type: hysteria
    server: b.xi.org
    port: 50288
    auth_str: xiaoyu
    alpn: h3
    protocol: udp
    up: 125
    down: 750
    sni: b.xi.org
    skip-cert-verify: false
    recv_window_conn: 110100480
    recv_window: 440401920
    disable_mtu_discovery: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
     - Hys-b.xi.org

另外如果客户端只有ipv6网络,那么如何添加使用ipv6 dns?

**Comment by emptysuns** [comment]
`server: b.xi.org`改成`server: fe80:xxxxxxx::1`

**Comment by liuxyon** [comment]
> `server: b.xi.org`改成`server: fe80:xxxxxxx::1`

感觉这是 连接服务器的地址 对吗？ 我意思是分配给客户ip地址，不是指连接服务器地址.

**Comment by emptysuns** [comment]
> > `server: b.xi.org`改成`server: fe80:xxxxxxx::1`
> 
> 感觉这是 连接服务器的地址 对吗？ 我意思是分配给客户ip地址，不是指连接服务器地址.

？没明白你的意思，**什么叫分配给客户ipv6地址？**

**Comment by liuxyon** [comment]
> > > `server: b.xi.org`改成`server: fe80:xxxxxxx::1`
> > 
> > 
> > 感觉这是 连接服务器的地址 对吗？ 我意思是分配给客户ip地址，不是指连接服务器地址.
> 
> ？没明白你的意思，**什么叫分配给客户ipv6地址？**

例如 我有一个自己的网段 2602:fed:7020::/48，我将其中划分的网段 2602:fed:7020:a::/64 划分给vpn用.  将2602:fed:7020:a::1 2602:fed:7020:a::2 2602:fed:7020:a::3 等等分配给每个客户使用. 然后用户对外显示的ip地址就是2602:fed:7020:a::1 2602:fed:7020:a::2  2602:fed:7020:a::3 等等各自的ip.

**Comment by liuxyon** [comment]
参考 wireguard 是这样分配ip的

[Interface]
Address = 10.0.0.1/24
Address = 2602:fed:7020:a::/64
ListenPort = 62300
PrivateKey = 
mtu=1420
[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 10.0.0.102/32, 2602:fed:7020:a::102/128
