### ISSUE TITLE
脚本更新出现问题，虽然更新成功，但是配置都丢失了

### ISSUE THREAD

**Issue by lukemin** [emptysuns/Hi_Hysteria#98]
/usr/bin/hihy: line 916: it: command not found
/usr/bin/hihy: line 917: syntax error near unexpected token `fi'
/usr/bin/hihy: line 917: `	fi'
root@instance-20200816-1453:/home/ubuntu#

**Comment by emptysuns** [comment]
`12) 完全重置所有配置`尝试用选项12重置一下试试，不知道是哪个版本的bug，给的信息太少无法定位错误
