### ISSUE TITLE
增加绑定出口ip和接口

### ISSUE THREAD

**Issue by liuxyon** [emptysuns/Hi_Hysteria#99]
增加绑定出口ip和接口，目前脚本里没有这个

"bind_outbound": {
    "address": "5.6.7.8", // 绑定地址
    "device": "eth0" // 绑定设备 (通常需要 root)
  }

**Comment by emptysuns** [comment]
我认为没有必要添加此项，使用脚本的人，比如我是为了快速配置，省事方便。

如果想要绑定网卡这种，实现起来不麻烦但是没必要，真正有需求自己去看wiki，修改即可，不符合大多数脚本用户的需求。
